import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createTextOutputSession,outputPath,outputStorageKey,TextFileError} from '../../../src/text-output/index.ts';
import {prepareTextDocument,hashText} from '../../../src/text-output/model.ts';
const DAY={kind:'journal' as const,date:'2026-10-06',zone:'Asia/Shanghai'};
const ok=(r:any)=>{assert.equal(r.ok,true,JSON.stringify(r));return r.value;};
const utf8=(s:string)=>new TextEncoder().encode(s);

/** The session is production code; this explicit seam uses isolated actual OS files.
 * Native browser handles, IndexedDB and Web Locks are covered separately. */
async function harness(t:any){
  await fs.mkdir('test-results/v06-b9/files',{recursive:true});const root=await fs.mkdtemp(path.resolve('test-results/v06-b9/files/case-'));
  let epoch='epoch-old',revision=1,sequence=0,allowed=true,supported=true,requests=0,picks=0;
  const texts=new Map([[JSON.stringify(DAY),'初始输出\n']]),entries=new Map<string,any>(),listeners=new Set<()=>void>(),events:any[]=[],writes:any[]=[];
  const handle:any={kind:'directory',name:'isolated-test-directory'},locks=new Map<string,Promise<any>>();
  let failCopy=false,failWrite=false,failClose=false,failMetadata=false,failAllMetadata=false,afterClose:(()=>Promise<void>)|undefined,beforeWrite:(()=>Promise<void>)|undefined;
  const file=(parts:readonly string[])=>{const p=path.resolve(root,...parts);assert.ok(p.startsWith(root+path.sep));return p;};
  const repository:any={read:async(k:string)=>entries.get(k),keys:async(prefix='')=>[...entries.keys()].filter(k=>k.startsWith(prefix)),atomic:async(keys:string[],reduce:any)=>{const change=reduce(keys.map(k=>entries.get(k)),{epoch,revision,data:{version:5}});if(failAllMetadata&&change.writes?.length)throw Error('synthetic unavailable metadata store');if(failMetadata&&change.writes?.some((w:any)=>w.value.intent?.stage==='closed')){failMetadata=false;throw Error('synthetic metadata commit abort after close');}for(const w of change.writes??[])entries.set(w.key,w.value);return change.result;}};
  const runtime:any={supported:()=>supported,pickDirectory:async()=>{picks++;return handle;},permission:async(_h:any,request:boolean)=>{if(request){requests++;allowed=true;}return allowed?'granted':'denied';},
    read:async(_h:any,parts:string[])=>{try{return new Uint8Array(await fs.readFile(file(parts)));}catch(e:any){if(e.code==='ENOENT')return null;throw e;}},
    write:async(_h:any,parts:string[],bytes:Uint8Array,guard:any)=>{await guard();if(beforeWrite){const fn=beforeWrite;beforeWrite=undefined;await fn();}await guard();if(failCopy&&parts.includes('conflicts'))throw Error('synthetic copy failure');if(failWrite)throw Error('synthetic write failure');if(failClose)throw Error('synthetic close failure');await fs.mkdir(path.dirname(file(parts)),{recursive:true});await fs.writeFile(file(parts),bytes);writes.push({parts:[...parts],bytes:new Uint8Array(bytes)});if(afterClose){const fn=afterClose;afterClose=undefined;await fn();}},
    lock:async(k:string,work:any)=>{const previous=locks.get(k)??Promise.resolve();const pending=previous.catch(()=>{}).then(work);locks.set(k,pending);return pending;}};
  const source:any={context:async()=>({epoch,revision,v5:true,zone:DAY.zone}),dates:async()=>[...texts.keys()].map(k=>JSON.parse(k)),render:async(k:any)=>{if(k.epoch!==epoch)throw new TextFileError('WORKSPACE_REPLACED','epoch changed');const text=texts.get(JSON.stringify({kind:k.kind,date:k.date,zone:k.zone}))??'# 空日\n';return prepareTextDocument(text,k.kind==='journal'?{kind:'journal',token:{epoch,revision},inputFingerprint:await hashText(text)}:{kind:'maintenance',epoch,dayRevision:revision,inputFingerprint:await hashText(text)});},subscribe:(fn:any)=>{listeners.add(fn);return()=>listeners.delete(fn);},event:async(e:any)=>events.push(e)};
  const sessions:any[]=[];const make=()=>{const s=createTextOutputSession({repository,runtime,source,now:()=> '2026-10-06T01:00:00Z',id:()=>`id-${++sequence}`,debounceMs:100000});sessions.push(s);return s;};
  t.after(async()=>{for(const s of sessions)await s.close();});const s=make();await s.start();
  const connect=async(suffix:'md'|'txt'='md')=>ok(await s.connectTextDirectory({epoch,suffix}));
  const state=async(id?:string)=>ok(await s.readTextSyncState({bindingId:id??entries.get('text:active')}));
  const key=async()=> (await state()).outputs.find((o:any)=>o.key.kind==='journal'&&o.key.date===DAY.date).key;
  const disk=async(k?:any)=>runtime.read(handle,outputPath(k??await key(),entries.get('text:binding:'+entries.get('text:active')).suffix));
  const change=(text:string,date=DAY)=>{texts.set(JSON.stringify(date),text);revision++;for(const fn of listeners)fn();};
  const external=async(bytes:Uint8Array)=>{const p=file(outputPath(await key(),entries.get('text:binding:'+entries.get('text:active')).suffix));await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,bytes);};
  return {s,make,connect,state,key,disk,change,external,entries,events,writes,root,source,runtime,repository,notify:()=>{for(const fn of listeners)fn();},
    permissions:(value:boolean)=>{allowed=value;},supported:(value:boolean)=>{supported=value;},counts:()=>({requests,picks}),
    copyFailure:(v:boolean)=>{failCopy=v;},writeFailure:(v:boolean)=>{failWrite=v;},closeFailure:(v:boolean)=>{failClose=v;},metadataUnavailable:(v:boolean)=>{failAllMetadata=v;},metadataFailure:()=>{failMetadata=true;},afterClose:(fn:()=>Promise<void>)=>{afterClose=fn;},beforeWrite:(fn:()=>Promise<void>)=>{beforeWrite=fn;},replace:()=>{epoch='epoch-new';revision=1;for(const fn of listeners)fn();},epoch:()=>epoch};
}
test('B9 one queue coalesces newest source and records only verified UTF-8 bytes',async t=>{const h=await harness(t);await h.connect();h.change('中间\n');h.change('最新\n');await h.s.flush();assert.equal(new TextDecoder().decode(await h.disk()),'最新\n');const r=(await h.state()).outputs[0];assert.equal(r.status,'synced');assert.equal(r.lastSuccess.sha256,await hashText('最新\n'));assert.equal(h.writes.length,1);assert.equal(h.entries.get(outputStorageKey(r.key)).intent,null);});
test('I1 a projection invalidated during discovery automatically drains the queued newer source',async t=>{
  const h=await harness(t),render=h.source.render;
  let release!:()=>void,entered!:()=>void,first=true;
  const hold=new Promise<void>(r=>release=r),start=new Promise<void>(r=>entered=r);
  h.source.render=async(key:any)=>{if(first){first=false;entered();await hold;throw new TextFileError('SOURCE_STALE','projection changed during read');}return render(key);};
  const connecting=h.connect();await start;h.change('读取期间的最新版本\n');release();await connecting;await h.s.flush();
  assert.equal(new TextDecoder().decode(await h.disk()),'读取期间的最新版本\n');
  const row=(await h.state()).outputs[0];assert.equal(row.status,'synced');assert.equal(row.lastSuccess.source.token.revision,2);assert.equal(row.error,null);assert.equal(h.writes.length,1);
});
test('B9 maintenance and journal use the same writer but retain independent source versions',async t=>{const h=await harness(t);h.change('日志\n',{...DAY,kind:'maintenance'} as any);await h.connect();await h.s.flush();const rows=(await h.state()).outputs;assert.equal(rows.length,2);assert.deepEqual(rows.map((r:any)=>r.lastSuccess.source.kind).sort(),['journal','maintenance']);});
test('B9 external invalid UTF-8 bytes are copied exactly before restoring last success and latest',async t=>{const h=await harness(t);const b=await h.connect();await h.s.flush();const bytes=new Uint8Array([255,0,13,10,254]);await h.external(bytes);h.change('新业务\n');ok(await h.s.refreshTextFiles(b));await h.s.flush();const row=(await h.state()).outputs[0];assert.deepEqual(new Uint8Array(await fs.readFile(path.join(h.root,row.externalCopyPath))),bytes);assert.equal(new TextDecoder().decode(await h.disk()),'新业务\n');assert.equal(h.events.filter(e=>e.operation==='RestoreExternalText').length,1);});
test('B9 failed conflict copy prevents overwrite and explicit retry preserves original bytes',async t=>{const h=await harness(t);const b=await h.connect();await h.s.flush();await h.external(utf8('外部原文\r\n'));h.copyFailure(true);ok(await h.s.refreshTextFiles(b));assert.equal((await h.state()).connection.status,'conflict-copy-failed');assert.equal(new TextDecoder().decode(await h.disk()),'外部原文\r\n');h.copyFailure(false);ok(await h.s.retryTextOutput({key:await h.key()}));assert.equal(new TextDecoder().decode(await h.disk()),'初始输出\n');});
test('B9 first same-name external file is preserved and initialized without a restore claim',async t=>{const h=await harness(t);await h.connect();await h.external(utf8('已有文件'));await h.s.flush();assert.ok((await h.state()).outputs[0].externalCopyPath);assert.equal(h.events.some(e=>e.operation==='RestoreExternalText'),false);assert.equal(new TextDecoder().decode(await h.disk()),'初始输出\n');});
test('B9 permission failure keeps latest pending source and requires an explicit gesture',async t=>{const h=await harness(t);const b=await h.connect();await h.s.flush();h.permissions(false);h.change('权限失效期间\n');await h.s.flush();assert.equal((await h.state()).connection.status,'permission-required');h.change('失效后最新\n');await h.s.flush();assert.equal((await h.state()).outputs[0].pendingSource.token.revision,3);assert.equal(h.counts().requests,0);ok(await h.s.reconnectTextDirectory(b));await h.s.flush();assert.equal(new TextDecoder().decode(await h.disk()),'失效后最新\n');assert.equal(h.counts().requests,1);});
test('B9 disk/close failures never advance last success and retry current source',async t=>{const h=await harness(t);await h.connect();await h.s.flush();const old=(await h.state()).outputs[0].lastSuccess;h.closeFailure(true);h.change('待补写\n');await h.s.flush();assert.deepEqual((await h.state()).outputs[0].lastSuccess,old);h.closeFailure(false);ok(await h.s.retryTextOutput({key:await h.key()}));assert.equal(new TextDecoder().decode(await h.disk()),'待补写\n');});
test('B9 close-before-metadata-abort is reconciled after reopen without treating own bytes as external',async t=>{const h=await harness(t);const b=await h.connect();await h.s.flush();h.metadataFailure();h.change('已关闭但未登记\n');await h.s.flush();const row=(await h.state()).outputs[0];assert.equal(row.status,'reconcile-required');assert.equal(row.lastSuccess.text,'初始输出\n');assert.equal(h.entries.get(outputStorageKey(row.key)).intent.stage,'prepared');await h.s.close();const reopened=h.make();await reopened.start();ok(await reopened.reconnectTextDirectory(b));await reopened.flush();const r=ok(await reopened.readTextSyncState({bindingId:b.bindingId}));assert.equal(r.outputs[0].lastSuccess.text,'已关闭但未登记\n');assert.equal(r.outputs[0].externalCopyPath,null);});
test('B9 source changing during close drains the latest version without regressing file state',async t=>{const h=await harness(t);await h.connect();h.afterClose(async()=>h.change('关闭期间的新版本\n'));await h.s.flush();assert.equal(new TextDecoder().decode(await h.disk()),'关闭期间的新版本\n');assert.equal((await h.state()).outputs[0].lastSuccess.source.token.revision,2);});
test('B9 unavailable failure-state storage still reports reconcile-required and retains durable intent',async t=>{const h=await harness(t);await h.connect();await h.s.flush();h.change('文件已落盘而整个元数据存储不可写\n');h.afterClose(async()=>h.metadataUnavailable(true));await h.s.flush();const row=(await h.state()).outputs[0];assert.equal(row.status,'reconcile-required');assert.equal(row.lastSuccess.text,'初始输出\n');assert.equal(h.entries.get(outputStorageKey(row.key)).intent.stage,'prepared');assert.equal((await h.state()).connection.status,'reconcile-required');h.metadataUnavailable(false);ok(await h.s.retryTextOutput({key:row.key}));assert.equal((await h.state()).connection.status,'synced');});
test('B9 replacement before opening a stream blocks old writes; explicit resume uses a new namespace',async t=>{const h=await harness(t);const b=await h.connect();h.beforeWrite(async()=>h.replace());await h.s.flush();assert.equal(h.writes.length,0);assert.equal((await h.state()).connection.status,'paused-after-replace');const resumed=ok(await h.s.reconnectTextDirectory({...b,epoch:h.epoch()}));assert.equal(resumed.connectionVersion,2);await h.s.flush();assert.equal((await h.state()).outputs[0].key.epoch,'epoch-new');});
test('B9 replacement after close cannot publish old success as a new epoch state',async t=>{const h=await harness(t);await h.connect();h.afterClose(async()=>h.replace());await h.s.flush();const row=(await h.state()).outputs[0];assert.equal(row.lastSuccess,null);assert.equal(row.status,'paused-after-replace');assert.equal(h.entries.get(outputStorageKey(row.key)).intent.stage,'prepared');});
test('B9 changing suffix preserves md and starts an independently keyed txt output',async t=>{const h=await harness(t);const b=await h.connect();await h.s.flush();const oldkey=await h.key(),oldbytes=await h.disk();const next=ok(await h.s.reconnectTextDirectory({...b,suffix:'txt'}));await h.s.flush();assert.equal(next.connectionVersion,2);assert.deepEqual(new Uint8Array(await fs.readFile(path.join(h.root,...outputPath(oldkey,'md')))),oldbytes);assert.equal((await h.state()).connection.suffix,'txt');});
test('B9 source discovery repairs commit-before-queue gap and rewrites explicit empty output, without delete',async t=>{const h=await harness(t);await h.connect();await h.s.flush();await h.s.close();h.change('# 空日\n');const reopened=h.make();await reopened.start();await reopened.flush();assert.equal(new TextDecoder().decode(await h.disk()),'# 空日\n');});
test('B9 two sessions serialize through the same binding lock and converge on newest source',async t=>{const h=await harness(t);await h.connect();await h.s.flush();const other=h.make();await other.start();h.change('两窗口的新源\n');await Promise.all([h.s.flush(),other.flush()]);assert.equal(new TextDecoder().decode(await h.disk()),'两窗口的新源\n');assert.equal((await h.state()).outputs[0].lastSuccess.source.token.revision,2);});
test('B9 public refresh waits for jobs queued while another write is already active',async t=>{const h=await harness(t),b=await h.connect();let release!:()=>void,entered!:()=>void;const hold=new Promise<void>(r=>release=r),start=new Promise<void>(r=>entered=r);h.beforeWrite(async()=>{entered();await hold;});const active=h.s.flush();await start;h.change('活动写入期间新增的另一文件\n',{...DAY,kind:'maintenance'} as any);const refresh=h.s.refreshTextFiles(b);release();ok(await refresh);await active;const rows=(await h.state()).outputs;assert.equal(rows.length,2);assert.ok(rows.every((r:any)=>r.status==='synced'));});
test('B9 unsupported/manual download and disconnected queue never claim disk sync',async t=>{const h=await harness(t);h.supported(false);assert.equal((await h.s.connectTextDirectory({epoch:h.epoch(),suffix:'md'})).ok,false);assert.equal(h.counts().picks,0);assert.equal(ok(await h.s.prepareTextDownload(DAY)).text,'初始输出\n');assert.equal(h.entries.size,0);h.supported(true);const b=await h.connect();await h.s.flush();ok(await h.s.disconnectTextDirectory(b));h.change('断开期间\n');await h.s.flush();assert.equal((await h.state()).connection.status,'disconnected');assert.equal(new TextDecoder().decode(await h.disk()),'初始输出\n');});
test('B9 unchanged source notification never checks external files; explicit refresh does',async t=>{const h=await harness(t);const b=await h.connect();await h.s.flush();await h.external(utf8('外部改动'));const read=h.runtime.read;let reads=0;h.runtime.read=async(...args:any[])=>{reads++;return read(...args);};h.notify();await h.s.flush();assert.equal(reads,0);assert.equal(new TextDecoder().decode(await read(h.runtime.handle,outputPath(await h.key(),'md'))),'外部改动');ok(await h.s.refreshTextFiles(b));assert.ok(reads>0);assert.equal(new TextDecoder().decode(await h.disk()),'初始输出\n');});
