// 2G independent acceptance: production entry, fresh browser contexts, synthetic records only.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
const root=fileURLToPath(new URL('../../',import.meta.url));
const out=process.env.CARDGRID_2G_OUTPUT||path.join(os.tmpdir(),'cardgrid-2g-'+Date.now());
await fs.mkdir(out,{recursive:true});
const {chromium}=await import(process.env.CARDGRID_PLAYWRIGHT_MODULE||'playwright');
const server=await createServer({root,configFile:path.join(root,'vite.config.ts'),logLevel:'error',server:{host:'127.0.0.1',port:0}});
await server.listen();const url='http://127.0.0.1:'+server.httpServer.address().port+'/';
const browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})});
const results=[];const btn=(p,n)=>p.getByRole('button',{name:n,exact:true});
const row=(p,n)=>p.locator('.fan-card, .dayboard-row').filter({hasText:n});
async function state(p){return p.evaluate(async()=>{const {createWorkspaceStore}=await import('/src/store.ts');const s=createWorkspaceStore();try{return await s.read();}finally{s.close();}});}
async function check(name,fn){const context=await browser.newContext({timezoneId:'Asia/Shanghai',serviceWorkers:'block',viewport:{width:1280,height:900}});let p;
 try{p=await context.newPage();p.setDefaultTimeout(5000);await p.goto(url);await p.waitForLoadState('networkidle');const detail=await fn(p,context);results.push({name,status:'pass',detail});console.log('PASS',name);}
 catch(e){const entry={name,status:'fail',error:e.stack};if(p){entry.state=await state(p).catch(()=>null);entry.ui=await p.locator('body').innerText().catch(()=>null);await p.screenshot({path:path.join(out,name+'.png'),fullPage:true}).catch(()=>{});}results.push(entry);console.log('FAIL',name,e.message.split('\n')[0]);}
 finally{await context.close();}}
async function seed(p,kind='hand'){
 await p.evaluate(async kind=>{const fx=await import('/tests/fixtures/action/independent.ts');const {createWorkspaceStore}=await import('/src/store.ts');const {createWorkspaceClient}=await import('/src/workspace-client.ts');const s=createWorkspaceStore();
 let d=kind==='planned'||kind==='planned-fixed'?fx.planned():fx.hand();if(kind==='planned-fixed')d.planner.fixed=fx.fixed().planner.fixed;
 if(kind==='no-duration'){d.planner.instances[0].currentContent=fx.content(null);d.planner.instances[0].creationSnapshot=fx.content(null);}
 await s.atomic(()=>({write:fx.envelope(d),result:null}));
 if(kind==='fixed'){const c=createWorkspaceClient({store:s,now:()=>fx.AT});const submit=async(type,payload,id)=>{const load=await c.load();const r=await c.submit({commandId:id,expected:load.value.token,type,payload});if(!r.ok)throw Error(JSON.stringify(r));};
 const template={id:'monday',version:1,name:'合成固定模板',weekdays:[1],source:{kind:'manual'},entries:[{id:'x',title:'固定甲',start:'09:15',elapsedMinutes:30,definitionId:null},{id:'y',title:'固定乙',start:'10:00',elapsedMinutes:30,definitionId:null}]};
 await submit('SaveTemplate',{template,expectedVersion:null},'seed-template');await submit('PrepareDay',{date:'2026-09-28',zone:'Asia/Shanghai',templateId:'monday'},'seed-day');c.close();}else s.close();
 },kind);
 await p.reload({waitUntil:'networkidle'});await p.locator('nav').getByText('抽卡手牌').click();await p.getByRole('tab',{name:'当日',exact:true}).click();await p.getByLabel('日期',{exact:true}).fill('2026-09-28');
 await p.getByLabel('时区',{exact:true}).fill('Asia/Shanghai');await p.locator('.fan-card, .dayboard-row').first().waitFor();
}
async function actual(p){await row(p,'独立合成行动').getByRole('button',{name:'确认实际',exact:true}).click();const dlg=p.getByRole('dialog',{name:'确认实际发生'});await dlg.waitFor();await dlg.locator('.flow-actualrange').waitFor();return dlg;}
try{
 await check('G2-fixed-close-is-write-free',async p=>{await seed(p,'fixed');await row(p,'固定甲').getByRole('button',{name:'解锁并调整'}).click();const dlg=p.getByRole('dialog');await dlg.locator('.flow-candidate').waitFor();const before=await state(p);await btn(dlg,'取消').click();assert.deepEqual(await state(p),before);return{unchanged:true};});
 await check('G2-fixed-move-at-initial-focus',async p=>{await seed(p,'fixed');await p.getByLabel('默认落点').fill('11:00');await row(p,'固定甲').getByRole('button',{name:'解锁并调整'}).click();const dlg=p.getByRole('dialog');await dlg.locator('.flow-candidate.valid').waitFor();await btn(dlg,'确认排期').click();await dlg.waitFor({state:'hidden'});const d=(await state(p)).data;assert.equal(d.planner.fixed.find(f=>f.title==='固定甲').range.localStart,'2026-09-28T11:00');assert.equal(d.planner.plans.length,0);return{fixedMoved:true,noFakePlan:true};});
 await check('G2-fixed-change-dialog-focus',async p=>{await seed(p,'fixed');await row(p,'固定甲').getByRole('button',{name:'解锁并调整'}).click();const dlg=p.getByRole('dialog');await dlg.locator('.flow-candidate').waitFor();await dlg.getByLabel('落点时间').fill('11:00');await dlg.locator('.flow-candidate').filter({hasText:'T11:00'}).waitFor();await btn(dlg,'确认排期').click();await p.waitForTimeout(250);const d=(await state(p)).data;assert.equal(d.planner.fixed.find(f=>f.title==='固定甲').range.localStart,'2026-09-28T11:00','changing focus must not consume the new preview unlock');return{fixedMoved:true};});
 await check('G2-fixed-explicit-cancel',async p=>{await seed(p,'fixed');const before=await state(p);await row(p,'固定甲').getByRole('button',{name:'取消安排',exact:true}).click();assert.deepEqual(await state(p),before);await row(p,'固定甲').getByRole('button',{name:'再点一次确认取消'}).click();await row(p,'固定甲').waitFor({state:'hidden'});const d=(await state(p)).data;assert.equal(d.planner.fixed.find(f=>f.title==='固定甲').cancelled,true);assert.equal(d.planner.fixed.find(f=>f.title==='固定乙').cancelled,false);return{otherFixedPreserved:true};});
 await check('G2-actual-new-overlap-needs-new-ack',async p=>{await seed(p,'planned-fixed');const dlg=await actual(p);await dlg.locator('.flow-blockers').filter({hasText:'固定甲'}).waitFor();await dlg.locator('.flow-ack input').check();await dlg.getByLabel('开始时间',{exact:true}).fill('10:00');await dlg.getByLabel('结束时间',{exact:true}).fill('10:30');const before=await state(p);await btn(dlg,'确认实际').click();await p.waitForTimeout(250);const after=await state(p);assert.deepEqual(after,before,'old acknowledgement must not authorize a different interval and blocker');return{newAckRequired:true};});
 await check('G2-actual-minute-precision',async p=>{await seed(p,'planned');const dlg=await actual(p);await dlg.getByLabel('开始时间',{exact:true}).fill('09:02');await dlg.getByLabel('结束时间',{exact:true}).fill('09:19');await btn(dlg,'确认实际').click();await dlg.waitFor({state:'hidden'});const f=(await state(p)).data.planner.facts[0];assert.equal(f.actualRange.localStart,'2026-09-28T09:02');assert.equal(f.actualRange.localEnd,'2026-09-28T09:19');return{minutes:17};});
 await check('G2-no-duration-unplanned-actual-entry',async p=>{await seed(p,'no-duration');assert.equal(await row(p,'独立合成行动').getByRole('button',{name:/确认实际|记录实际/}).count(),1,'unplanned/no-duration action needs an actual recording entry');});
 await check('G2-future-actual-warning',async p=>{await seed(p,'planned');const dlg=await actual(p);await dlg.getByLabel('开始日期',{exact:true}).fill('2030-01-01');await dlg.getByLabel('结束日期',{exact:true}).fill('2030-01-01');assert.match(await dlg.innerText(),/尚未到达|未来.*不可修改|提前确认|结束时间尚未到达/,'future actual confirmation requires an explicit warning');});
 await check('G2-epoch-replacement-clears-dialog',async p=>{await seed(p,'planned');await actual(p);await p.evaluate(async()=>{const fx=await import('/tests/fixtures/action/independent.ts');const {createWorkspaceStore}=await import('/src/store.ts');const s=createWorkspaceStore();try{await s.atomic(()=>({write:fx.envelope(fx.planned(),'replacement-epoch',1),result:null}));}finally{s.close();}});await p.getByText('工作区已被替换，旧草稿和预览已清除。').waitFor();assert.equal(await p.getByRole('dialog').count(),0,'old instance selection/actual draft must be cleared after epoch replacement');});
 await check('G2-actual-storage-failure-retains-input',async p=>{await seed(p,'planned');const dlg=await actual(p);await dlg.getByLabel('开始时间',{exact:true}).fill('09:02');await dlg.getByLabel('结束时间',{exact:true}).fill('09:19');const before=await state(p);await p.evaluate(()=>{const orig=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...rest){if(mode==='readwrite'){IDBDatabase.prototype.transaction=orig;throw new DOMException('2G synthetic failure','QuotaExceededError');}return orig.call(this,names,mode,...rest);};});await btn(dlg,'确认实际').click();await dlg.getByRole('alert').waitFor();assert.deepEqual(await state(p),before);assert.equal(await dlg.getByLabel('开始时间',{exact:true}).inputValue(),'09:02');assert.equal(await dlg.getByLabel('结束时间',{exact:true}).inputValue(),'09:19');await btn(dlg,'确认实际').click();await dlg.waitFor({state:'hidden'});assert.equal((await state(p)).data.planner.facts.length,1);return{failureWriteFree:true,inputsRetained:true,retryOneFact:true};});
 await check('G2-double-confirm-produces-one-fact',async p=>{await seed(p,'planned');const dlg=await actual(p);await btn(dlg,'确认实际').dblclick();await dlg.waitFor({state:'hidden'});assert.equal((await state(p)).data.planner.facts.length,1);return{oneFact:true};});
 await check('G2-backup-restore-preserves-fact-data',async p=>{
  await seed(p,'planned');const dlg=await actual(p);await btn(dlg,'确认实际').click();await dlg.waitFor({state:'hidden'});
  await p.locator('nav').getByText('数据与备份').click();const first=p.waitForEvent('download');await btn(p,'下载完整备份').click();const a=await first;const text=await fs.readFile(await a.path(),'utf8');const saved=JSON.parse(text);
  await p.evaluate(async()=>{const {createWorkspaceClient}=await import('/src/workspace-client.ts');const c=createWorkspaceClient();try{const load=await c.load();const r=await c.submit({commandId:'later-capture',expected:load.value.token,type:'CreateCapture',payload:{text:'备份之后的合成输入',source:'2g'}});if(!r.ok)throw Error(JSON.stringify(r));}finally{c.close();}});
  await p.getByText('另一窗口已保存，已为你重新读取；当前输入仍保留。').waitFor();const next=p.waitForEvent('download');await btn(p,'下载完整备份').click();await next;
  await p.getByLabel('我已保存这份完整备份').check();await p.getByLabel('导入文件选择').setInputFiles({name:'2g-original-backup.json',mimeType:'application/json',buffer:Buffer.from(text)});await p.getByRole('heading',{name:'恢复预览'}).waitFor();
  await p.getByLabel('确认放弃未提交草稿并执行以上操作').check();await btn(p,'执行已预览操作').click();await p.getByText('已保存到本机').waitFor();const after=await state(p);assert.deepEqual(after.data,saved.data);assert.equal(after.data.planner.facts.length,1);return{exactDataRestored:true,newerCaptureRemoved:true,originalFactPreserved:true};
 });
 await check('G2-actual-DST-offset-selection',async p=>{await seed(p,'planned');await p.evaluate(async()=>{const {createWorkspaceStore}=await import('/src/store.ts');const s=createWorkspaceStore();try{await s.atomic(raw=>{const d=structuredClone(raw);d.data.settings.zone='America/New_York';d.data.planner.plans[0].range={startAt:'2026-09-28T13:00:00Z',endAt:'2026-09-28T13:30:00Z',zone:'America/New_York',localStart:'2026-09-28T09:00',localEnd:'2026-09-28T09:30',startOffset:'-04:00',endOffset:'-04:00'};return{write:d,result:null};});}finally{s.close();}});await p.reload({waitUntil:'networkidle'});await p.locator('nav').getByText('抽卡手牌').click();await p.getByRole('tab',{name:'当日',exact:true}).click();await p.getByLabel('日期',{exact:true}).fill('2026-09-28');const dlg=await actual(p);await dlg.getByLabel('开始日期',{exact:true}).fill('2026-11-01');await dlg.getByLabel('结束日期',{exact:true}).fill('2026-11-01');await dlg.getByLabel('开始时间',{exact:true}).fill('01:30');await dlg.getByLabel('结束时间',{exact:true}).fill('02:30');await btn(dlg,'确认实际').click();await dlg.getByRole('alert').waitFor();assert.ok(await dlg.getByRole('combobox').count()||await dlg.getByRole('radio').count()||await dlg.getByRole('button',{name:/-04:00|-05:00/}).count(),'DST ambiguous endpoints need usable explicit offset choices');});
}finally{await browser.close();await server.close();await fs.writeFile(path.join(out,'results.json'),JSON.stringify({at:new Date().toISOString(),results},null,2));console.log('Evidence:',out);}
console.log('2G independent:',results.filter(r=>r.status==='pass').length+'/'+results.length);if(results.some(r=>r.status==='fail'))process.exitCode=1;