// Run against a freshly built dist. No normal browser profile or real data is used.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {createHash} from 'node:crypto';
import {fileURLToPath, pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';

const repo = fileURLToPath(new URL('../../', import.meta.url));
const {chromium} = await import(process.env.CARDGRID_PLAYWRIGHT_MODULE || 'playwright');
const {emptyData, emptyConfig, validateData, backupPack, configPack, mergeConfig} = await import(new URL('../../src/workspace/legacy/domain.ts', import.meta.url));
const P = await import(new URL('../../src/workspace/legacy/planner.ts', import.meta.url));
const output = path.resolve(process.env.CARDGRID_G0_OUTPUT || path.join(os.tmpdir(), `cardgrid-g0-${Date.now()}`));
await fs.mkdir(output, {recursive:true});
const date = '2026-09-24';
const fixedNow = '2026-09-24T04:00:00.000Z';
const hash = value => createHash('sha256').update(typeof value==='string' ? value : JSON.stringify(value)).digest('hex');
const config = (suffix, title) => ({preferences:{...emptyConfig().preferences},categories:[{id:`cat-${suffix}`,name:title,color:'#336699'}],cards:[{id:`card-${suffix}`,title,kind:'temporary',minutes:20,categoryId:`cat-${suffix}`,parentId:null,steps:'合成完成标准',enabled:true}],schedules:[{id:`schedule-${suffix}`,name:title,entries:[{cardId:`card-${suffix}`,start:'08:00',minutes:20}]}]});
function makeFixture() {
  const d=emptyData(); d.config=config('base','原有配置');
  const p=d.planner; p.legacyImported=true;
  const block=(id,title,start,end,kind='fixed')=>({id,title,start,end,kind,task:'',cancelled:false});
  p.templates=[{id:'work',name:'工作日',weekdays:[1,2,3,4,5],blocks:[block('morning','上午工作',540,720),block('afternoon','下午工作',840,1080)]},{id:'rest',name:'周末',weekdays:[0,6],blocks:[block('free','自由活动',600,720,'flexible')]},{id:'special',name:'特殊日',weekdays:[],blocks:[block('special-block','特殊安排',900,1020,'flexible')]}];
  p.rules=[{id:'daily',name:'每日记录',title:'每日记录',weekdays:[0,1,2,3,4,5,6],status:'active',start:'2026-01-01',criteria:'记录一行',minimum:false,goals:[],projects:[]},{id:'weekday',name:'工作日锻炼',title:'工作日锻炼',weekdays:[1,2,3,4,5],status:'active',start:'2026-01-01',criteria:'运动20分钟',minimum:false,goals:[],projects:[]}];
  P.ensureDay(p,'2026-09-23'); P.putBlock(p,'2026-09-23',block('evening','晚间阅读',1200,1260,'flexible'),'2026-09-23');
  P.ensureDay(p,date); P.cancelBlock(p,date,'afternoon',date);
  p.tasks.push({...P.newTask('昨日未完成','2026-09-23'),id:'yesterday-task'});
  const a=P.createCapture(p,'未处理捕获A','fixture',fixedNow);
  const b=P.createCapture(p,'已归档捕获B','fixture',fixedNow); P.archiveCapture(p,b.id,date);
  const c=P.createCapture(p,'已转Card捕获C','fixture',fixedNow); P.resolveCapture(p,c.id,'手动任务A',date,date);
  d.planner=P.bootstrap(p,date);
  assert.equal(d.planner.tasks.length,4); assert.equal(d.planner.days.length,2);
  assert.equal(P.validatePlanner(d.planner).captures.find(x=>x.id===a.id).status,'unprocessed');
  return validateData(d);
}
const fixture=makeFixture();
const dist=path.join(repo,'dist');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=http.createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/__setup'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<!doctype html><title>Isolated G0 setup</title>');return}const file=path.resolve(dist,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(dist+path.sep)){res.writeHead(403).end();return}const bytes=await fs.readFile(file);res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(bytes)}catch{res.writeHead(404).end()}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})}).catch(error=>{server.close();throw error});
const records=[],sessions=new Set();
const seenErrors=[];
async function until(predicate, message='condition', timeout=7000){const end=Date.now()+timeout;do{const value=await predicate();if(value)return value;await new Promise(r=>setTimeout(r,30))}while(Date.now()<end);throw Error('Timeout: '+message)}
async function snapshot(page){return page.evaluate(async()=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('cardgrid-workspace');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});try{return await new Promise((ok,no)=>{const tx=db.transaction(['workspace','recovery'],'readonly'),data={};for(const [store,key,name] of [['workspace','current','current'],['recovery','previous','previous'],['recovery','pre-p1a','preP1a']]){const r=tx.objectStore(store).get(key);r.onsuccess=()=>data[name]=r.result??null}tx.oncomplete=()=>ok(data);tx.onabort=()=>no(tx.error)})}finally{db.close()}})}
async function seed(page,raw,version=3){await page.goto(origin+'/__setup');await page.evaluate(async({raw,version})=>{const db=await new Promise((ok,no)=>{const r=indexedDB.open('cardgrid-workspace',version);r.onupgradeneeded=()=>{r.result.createObjectStore('workspace');if(version===3)r.result.createObjectStore('recovery')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});await new Promise((ok,no)=>{const tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put(raw,'current');tx.oncomplete=ok;tx.onabort=()=>no(tx.error)});db.close()},{raw,version})}
async function ready(page){await page.getByRole('textbox',{name:'快速记录',exact:true}).waitFor();await until(async()=>(await snapshot(page)).current!==null,'bootstrap saved')}
async function session(data=fixture){const context=await browser.newContext({acceptDownloads:true,viewport:{width:1280,height:900},timezoneId:'Asia/Shanghai',serviceWorkers:'block'});sessions.add(context);await context.addInitScript(now=>{const RealDate=Date;globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:[now]))}static now(){return new RealDate(now).getTime()}}},fixedNow);context.on('page',p=>p.on('pageerror',e=>seenErrors.push(e.message)));const page=await context.newPage();if(data)await seed(page,{schemaVersion:3,revision:10,data});await page.goto(origin);await ready(page);return {context,page}}
async function nav(page,name){await page.locator('nav').getByRole('button',{name:new RegExp(name)}).click()}
async function reload(page){await page.getByRole('button',{name:'重新载入',exact:true}).click()}
async function saveCapture(page,text){await nav(page,'Today');const before=(await snapshot(page)).current.revision;await page.getByRole('textbox',{name:'快速记录',exact:true}).fill(text);await page.getByRole('button',{name:'放入 Inbox',exact:true}).click();await until(async()=>(await snapshot(page)).current.revision===before+1,'capture committed');assert.equal(await page.getByRole('textbox',{name:'快速记录',exact:true}).inputValue(),'')}
async function download(page,label){const [d]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:label,exact:true}).click()]);assert.equal(await d.failure(),null);const file=await d.path();return JSON.parse(await fs.readFile(file,'utf8'))}
async function preview(page,pack,mode){await page.getByLabel('导入文件选择').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pack))});await page.getByRole('dialog').waitFor();if(mode)await page.getByLabel('导入方式').selectOption(mode)}
async function confirmImport(page){const [d]=await Promise.all([page.waitForEvent('download'),page.getByRole('dialog').getByRole('button',{name:/备份当前并/}).click()]);assert.equal(await d.failure(),null);await page.getByRole('dialog').waitFor({state:'hidden'})}
async function assertConflict(page,before){await page.getByRole('status').filter({hasText:'本次没有覆盖'}).waitFor();assert.deepEqual(await snapshot(page),before,'conflict must preserve workspace and both recovery points')}
async function pair(){const s=await session();const other=await s.context.newPage();await other.goto(origin);await ready(other);return {...s,other}}
async function stale(){const s=await pair();await saveCapture(s.other,'另一个窗口的新记录');await s.page.getByRole('status').filter({hasText:'另一窗口已更新数据'}).waitFor();return {...s,before:await snapshot(s.page)}}
async function test(id,fn){if(process.env.CARDGRID_G0_CASE && id!==process.env.CARDGRID_G0_CASE)return;const started=Date.now(),oldErrors=seenErrors.length;try{const detail=await fn();assert.deepEqual(seenErrors.slice(oldErrors),[],'browser page errors');records.push({id,status:'pass',durationMs:Date.now()-started,detail});console.log('PASS',id)}catch(error){records.push({id,status:'fail',durationMs:Date.now()-started,error:error.stack});console.log('FAIL',id,error.message);for(const context of sessions){for(const [i,p] of context.pages().entries()){await p.screenshot({path:path.join(output,`${id}-${i}.png`),fullPage:true}).catch(()=>{})}}}finally{for(const context of sessions)await context.close();sessions.clear()}}
try{
 await test('A01-A04',async()=>{const {page}=await session(null);await nav(page,'数据与备份');const blank=await download(page,'下载完整备份');assert.equal(blank.kind,'backup');assert.equal(blank.data.planner.tasks.length,0);assert.equal(blank.data.planner.days.length,1);const {page:full}=await session();await nav(full,'数据与备份');const pack=await download(full,'下载完整备份');assert.deepEqual(pack.data,fixture);const before=(await snapshot(full)).current;await full.getByRole('button',{name:'清空工作台',exact:true}).click();await full.getByRole('dialog').getByRole('textbox').fill('清空');const clearPack=await download(full,'下载备份并清空');await full.getByRole('dialog').waitFor({state:'hidden'});assert.deepEqual(clearPack.data,fixture);const cleared=await snapshot(full);assert.deepEqual(cleared.current.data,emptyData());assert.equal(cleared.previous,null);assert.equal(cleared.preP1a,null);await preview(full,pack);await confirmImport(full);assert.deepEqual((await snapshot(full)).current.data,fixture);await full.reload();await ready(full);assert.deepEqual((await snapshot(full)).current.data,fixture);await nav(full,'数据与备份');assert.deepEqual(await download(full,'下载完整备份'),pack);await nav(full,'Inbox');assert.equal(await full.locator('.inbox-row').count(),1);await nav(full,'Schedule');assert.equal(await full.getByRole('button',{name:'编辑模板',exact:true}).count(),3);await full.screenshot({path:path.join(output,'restored.png'),fullPage:true});return {dataHash:hash(fixture),beforeRevision:before.revision,afterRevision:(await snapshot(full)).current.revision,days:2,cancelledBlocks:fixture.planner.days.find(x=>x.date===date).blocks.filter(x=>x.cancelled).length}});
 await test('A05',async()=>{const {page}=await session();await saveCapture(page,'建立恢复点');const saved=await snapshot(page);assert.deepEqual(saved.previous.raw.data,fixture);assert.equal(saved.previous.reason,'已放入收件箱');await nav(page,'数据与备份');const pack=await download(page,'导出恢复点');assert.deepEqual(pack.data,saved.previous.raw.data);await saveCapture(page,'恢复点以后的数据');await preview(page,pack);await confirmImport(page);assert.deepEqual((await snapshot(page)).current.data,fixture);return {recoveryDataHash:hash(pack.data),reason:saved.previous.reason}});
 await test('A06',async()=>{const context=await browser.newContext({acceptDownloads:true,timezoneId:'Asia/Shanghai',serviceWorkers:'block'});sessions.add(context);const page=await context.newPage();const old={schemaVersion:1,revision:7,config:config('legacy','旧版非空配置')};old.config.cards[0].kind='habit';await seed(page,old,1);await page.goto(origin);await ready(page);const upgraded=await snapshot(page);assert.equal(upgraded.current.schemaVersion,3);assert.deepEqual(upgraded.preP1a.raw,old);assert.deepEqual(upgraded.current.data.config,old.config);assert.equal(upgraded.current.data.planner.rules.length,1);assert.equal(upgraded.current.data.planner.tasks.length,1);await nav(page,'数据与备份');assert.deepEqual(await download(page,'导出 P1A 升级前原文'),old);await page.reload();await ready(page);assert.deepEqual(await snapshot(page),upgraded);return {rawHash:hash(old),version:3,legacyImported:upgraded.current.data.planner.legacyImported}});
 await test('A07-A08',async()=>{const {page}=await session();await nav(page,'数据与备份');assert.deepEqual((await download(page,'导出配置')).config,fixture.config);const incoming=config('new','新增配置');incoming.preferences.theme='night';incoming.categories.push({...fixture.config.categories[0],name:'同ID更新'});await preview(page,configPack(incoming),'merge');const shown=await page.locator('dialog .importsummary').innerText();assert.match(shown,/分类\s+1 → 2/);assert.match(shown,/卡片定义\s+1 → 2/);await confirmImport(page);let current=(await snapshot(page)).current.data;assert.deepEqual(current.config,mergeConfig(fixture.config,incoming));assert.deepEqual(current.planner,fixture.planner);await preview(page,configPack(config('new','替换配置')),'replace');const shownReplace=await page.locator('dialog .importsummary').innerText();assert.match(shownReplace,/卡片定义\s+2 → 1/);await confirmImport(page);current=(await snapshot(page)).current.data;assert.deepEqual(current.config,config('new','替换配置'));assert.deepEqual(current.planner,fixture.planner);return {mergePreview:shown,replacePreview:shownReplace}});
 await test('B01-B04',async()=>{const {page,other,before}=await stale();assert.equal(await page.getByText('另一个窗口的新记录',{exact:true}).count(),0);await new Promise(r=>setTimeout(r,10000));assert.deepEqual(await snapshot(page),before);assert.equal(await page.getByText('另一个窗口的新记录',{exact:true}).count(),0);await page.getByRole('status').filter({hasText:'另一窗口已更新数据'}).waitFor();await page.getByRole('textbox',{name:'快速记录',exact:true}).fill('旧窗口待保存');await page.getByRole('button',{name:'放入 Inbox',exact:true}).click();await assertConflict(page,before);assert.equal(await page.getByRole('textbox',{name:'快速记录',exact:true}).inputValue(),'旧窗口待保存');await reload(page);await until(async()=>await page.getByText('另一个窗口的新记录',{exact:true}).count()>0,'updated UI');await saveCapture(page,'重载后成功');await reload(other);await until(async()=>await other.getByText('重载后成功',{exact:true}).count()>0,'other UI updated');return {conflictRevision:before.current.revision,retryRevision:(await snapshot(page)).current.revision}});
 await test('B05-B06',async()=>{const {page,other,context}=await pair();for(const [tab,text] of [[page,'交替A1'],[other,'交替B1'],[page,'交替A2'],[other,'交替B2']]){await reload(tab);await saveCapture(tab,text)}const state=await snapshot(page);for(const title of ['交替A1','交替B1','交替A2','交替B2'])assert.equal(state.current.data.planner.captures.filter(x=>x.text===title).length,1);assert.equal(state.current.data.planner.history.filter(x=>x.type==='InboxItemCaptured').length-fixture.planner.history.filter(x=>x.type==='InboxItemCaptured').length,4);await other.close();await reload(page);await saveCapture(page,'关闭后捕获');await nav(page,'Schedule');await page.getByRole('button',{name:'＋ 添加当天安排',exact:true}).click();await page.getByLabel('安排名称',{exact:true}).fill('关闭后安排');await page.getByLabel('开始时间',{exact:true}).fill('19:00');await page.getByLabel('结束时间（可填 24:00）',{exact:true}).fill('19:30');await page.getByRole('button',{name:'保存当天安排',exact:true}).click();await page.getByLabel('安排名称',{exact:true}).waitFor({state:'hidden'});const newTab=await context.newPage();await newTab.goto(origin);await ready(newTab);assert.deepEqual(await snapshot(newTab),await snapshot(page));assert((await snapshot(newTab)).current.data.planner.days.find(x=>x.date===date).blocks.some(x=>x.title==='关闭后安排'));await nav(page,'数据与备份');await nav(newTab,'数据与备份');assert.deepEqual(await download(page,'下载完整备份'),await download(newTab,'下载完整备份'));await saveCapture(newTab,'新窗口通知测试');await page.getByRole('status').filter({hasText:'另一窗口已更新数据'}).waitFor();return {fourCapturesAndEvents:true,reopenedNotification:true}});
 for(const kind of ['capture','inbox','block','template','config','top3']) await test('C-'+kind,async()=>{const {page,before}=await stale();if(kind==='capture'){await page.getByLabel('快速记录',{exact:true}).fill('失败保留输入');await page.getByRole('button',{name:'放入 Inbox',exact:true}).click()}if(kind==='inbox'){await nav(page,'Inbox');await page.getByRole('button',{name:/未处理捕获A/}).click();await page.getByLabel('Card 标题',{exact:true}).fill('转换失败保留标题');await page.getByRole('button',{name:'转为 Card',exact:true}).click()}if(kind==='block'){await nav(page,'Schedule');await page.getByRole('button',{name:'编辑',exact:true}).first().click();await page.getByLabel('安排名称',{exact:true}).fill('安排失败保留草稿');await page.getByLabel('开始时间',{exact:true}).fill('10:00');await page.getByRole('button',{name:'保存当天安排',exact:true}).click()}if(kind==='template'){await nav(page,'Schedule');await page.getByRole('button',{name:'编辑模板',exact:true}).first().click();await page.getByLabel('日型名称',{exact:true}).fill('日型失败保留草稿');await page.getByLabel('周一',{exact:true}).uncheck();await page.getByRole('button',{name:'保存日型模板',exact:true}).click()}if(kind==='config'){await nav(page,'配置工坊');await page.getByLabel('主题').selectOption('night');await page.getByRole('button',{name:'保存配置',exact:true}).click()}if(kind==='top3')await page.getByRole('button',{name:'＋ 手动任务A',exact:true}).click();await assertConflict(page,before);if(kind==='capture')assert.equal(await page.getByLabel('快速记录',{exact:true}).inputValue(),'失败保留输入');if(kind==='inbox')assert.equal(await page.getByLabel('Card 标题',{exact:true}).inputValue(),'转换失败保留标题');if(kind==='block'){assert.equal(await page.getByLabel('安排名称',{exact:true}).inputValue(),'安排失败保留草稿');assert.equal(await page.getByLabel('开始时间',{exact:true}).inputValue(),'10:00');assert(await page.getByRole('button',{name:'＋ 添加当天安排',exact:true}).isDisabled());await page.getByRole('button',{name:'放弃草稿',exact:true}).click();assert.equal(await page.getByLabel('安排名称',{exact:true}).count(),0)}if(kind==='template'){assert.equal(await page.getByLabel('日型名称',{exact:true}).inputValue(),'日型失败保留草稿');assert.equal(await page.getByLabel('周一',{exact:true}).isChecked(),false)}if(kind==='config'){assert.equal(await page.getByLabel('主题').inputValue(),'night');assert(await page.getByText('有未保存修改',{exact:true}).isVisible());assert(await page.locator('.app.paper').count()===1)}if(kind==='top3'){assert(await page.getByRole('button',{name:'＋ 手动任务A',exact:true}).isEnabled());assert.equal(await page.locator('.top3item').filter({hasText:'手动任务A'}).count(),0)}if(kind==='inbox')await page.screenshot({path:path.join(output,'conflict-keeps-input.png'),fullPage:true});return {workspaceAndRecoveryUnchanged:true,revision:before.current.revision,confirmedError:'本次没有覆盖',draft:kind}});
 await test('transaction-abort',async()=>{const {page}=await session();const before=await snapshot(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const request=original.apply(this,args);if(this.name==='workspace'&&args[1]==='current'){this.transaction.abort();IDBObjectStore.prototype.put=original}return request}});await page.getByLabel('快速记录',{exact:true}).fill('中止事务后保留');await page.getByRole('button',{name:'放入 Inbox',exact:true}).click();await page.getByRole('status').filter({hasText:'保存失败，原数据已保留'}).waitFor();assert.deepEqual(await snapshot(page),before,'aborted workspace write must also roll back previous recovery update');assert.equal(await page.getByLabel('快速记录',{exact:true}).inputValue(),'中止事务后保留');await page.getByRole('button',{name:'放入 Inbox',exact:true}).click();await until(async()=>(await snapshot(page)).current.revision===before.current.revision+1,'retry after abort');assert.equal((await snapshot(page)).current.data.planner.captures.filter(x=>x.text==='中止事务后保留').length,1);return {atomicRollback:true,retryExactlyOnce:true}});
} finally {
 await browser.close();await new Promise(resolve=>server.close(resolve));
 const sourceHashes={};for(const name of ['src/domain.ts','src/planner.ts','src/planner-migration.ts','src/store.ts','src/main.tsx','src/today.tsx','src/schedule.tsx'])sourceHashes[name]=hash(await fs.readFile(path.join(repo,name),'utf8'));
 const result={selectedCase:process.env.CARDGRID_G0_CASE||null,executedAt:new Date().toISOString(),gitHead:execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),browserVersion:browser.version(),origin,fixedDate:date,fixtureHash:hash(fixture),sourceHashes,records};
 await fs.writeFile(path.join(output,'results.json'),JSON.stringify(result,null,2));
 console.log(`G0: ${records.filter(x=>x.status==='pass').length} passed, ${records.filter(x=>x.status==='fail').length} failed; ${output}`);
 if(!records.length||records.some(x=>x.status!=='pass'))process.exitCode=1;
}
