import test from 'node:test';
import assert from 'node:assert/strict';
import {b4Harness,ok,ref} from '../../support/v06/b4-fixtures.ts';
import {createV06JournalSession} from '../../../src/journal/v06-journal-session.ts';
import {catalog} from '../../support/v06/fixtures.ts';
const session=(h:any)=>createV06JournalSession(h.host,{date:'2026-10-06',zone:'Asia/Shanghai',debounceMs:100000,id:(()=>{let n=0;return()=>`note-command-${++n}`;})()});
test('B8 browsing/flush blank journal writes nothing; newest draft drains into one independently timestamped note',async()=>{const h=await b4Harness(),s=session(h);await s.start();const before=h.legacy.evidence();assert.equal(await s.flush(),true);assert.deepEqual(h.legacy.evidence(),before);s.edit('第一段');assert.equal(await s.flush(),true);const n=(await h.liveData()).journalNotes[0];s.edit('第二段');h.setNow('2026-10-06T01:00:00Z');assert.equal(await s.flush(),true);const after=(await h.liveData()).journalNotes[0];assert.equal(after.id,n.id);assert.equal(after.recordedAt,n.recordedAt);assert.equal(after.text,'第二段');assert.equal(after.version,2);await s.close();});
test('B8 edit during pending save drains latest text without creating a second note',async()=>{const h=await b4Harness();let release!:()=>void,started!:()=>void;const gate=new Promise<void>(r=>release=r),start=new Promise<void>(r=>started=r);let first=true;const host={...h.host,submit:async(cmd:any)=>{if(first){first=false;started();await gate;}return h.host.submit(cmd);}};const s=createV06JournalSession(host,{date:'2026-10-06',zone:'Asia/Shanghai',debounceMs:100000});await s.start();s.edit('先保存');const flush=s.flush();await start;s.edit('保存中补充');release();assert.equal(await flush,true);const notes=(await h.liveData()).journalNotes;assert.equal(notes.length,1);assert.equal(notes[0].text,'保存中补充');await s.close();});
test('B8 failure blocks date/page switch, preserves words; lost reply retries original creation before latest edit',async()=>{const h=await b4Harness(),s=session(h);await s.start();s.edit('旧日新感想');h.legacy.failNext();assert.equal(await s.changeDay('2026-10-05'),false);assert.equal(s.getSnapshot().date,'2026-10-06');assert.equal(s.getSnapshot().text,'旧日新感想');h.legacy.loseNextReply();assert.equal(await s.flush(),false);s.edit('最新感想');assert.equal(await s.flush(),true);assert.equal((await h.liveData()).journalNotes.length,1);assert.equal((await h.liveData()).journalNotes[0].text,'最新感想');assert.equal(await s.changeDay('2026-10-05'),true);assert.equal(s.getSnapshot().text,'');await s.close();});
test('B8 concurrent same-note edit never overwrites external content and retains draft for inspection',async()=>{const h=await b4Harness(),s=session(h);await s.start();s.edit('基线');await s.flush();const n=(await h.liveData()).journalNotes[0];s.edit('本窗口');await h.submit('SaveJournalNote',{id:n.id,expectedVersion:n.version,date:n.date,zone:n.zone,text:'另一窗口'});assert.equal(await s.flush(),false);assert.equal(s.getSnapshot().text,'本窗口');assert.equal((await h.liveData()).journalNotes[0].text,'另一窗口');s.discardDraft();await s.close();});
test('B8 replacement rejects old draft and refresh clears it; old full text stays separate from new notes',async()=>{const h=await b4Harness(),s=session(h);await s.start();s.edit('旧 epoch 草稿');await s.refresh();const old=JSON.stringify({format:'cardgrid',version:4,kind:'backup',dataFormat:'action-v4',data:h.old}),p=ok(await h.host.previewRestore({token:await h.token(),text:old}));ok(await h.host.submit({commandId:'restore-old',expected:await h.token(),type:'RestoreWorkspace',payload:{previewId:p.previewId,backup:await h.backup(),discardDraftsConfirmed:true}}));assert.equal(await s.flush(),false);assert.equal((await h.snapshot()).data.version,4);assert.deepEqual((await h.snapshot()).data.journalEntries,h.old.journalEntries);s.discardDraft();await s.close();});
test('B8 future note fails without any saved entry; old block editing retains exact creation metadata and history',async()=>{const h=await b4Harness(),s=session(h);await s.start();await s.changeDay('2026-10-07');s.edit('未来');assert.equal(await s.flush(),false);assert.equal((await h.liveData()).journalNotes.length,0);s.discardDraft();await s.changeDay('2026-10-04');const original=(await h.liveData()).journalEntries[0];await s.select({kind:'legacy',id:original.id,version:original.version});s.edit('旧正文编辑\r\n');await s.flush();const d=await h.liveData();assert.equal(d.journalEntries[0].createdAt,original.createdAt);assert.equal(d.planner.history.at(-1).before.text,original.text);assert.equal(d.journalNotes.length,0);await s.close();});
function logs(h:any){const partitions=new Map<string,unknown>();let failed=false;h.legacy.store.readMaintenance=async(key:string)=>structuredClone(partitions.get(key));h.legacy.store.atomicMaintenance=async(key:string,reduce:any)=>{if(failed)throw Error('log I/O synthetic');const c=reduce(structuredClone(partitions.get(key)));if('write' in c)partitions.set(key,structuredClone(c.write));return c.result;};return {partitions,fail:(value:boolean)=>{failed=value;}};}
test('B8 maintenance persists separately, failed logging does not fail business, and replay records one success',async()=>{const h=await b4Harness(),l=logs(h);await h.host.retryMaintenance();l.fail(true);const cmd=await h.command('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'私密全文，不进日志'});assert.equal((await h.host.submit(cmd)).ok,true);const input={epoch:(await h.token()).epoch,date:'2026-10-06',zone:'UTC'};assert.equal(ok(await h.host.readMaintenanceDay(input)).hasGaps,true);l.fail(false);await h.host.retryMaintenance();assert.equal(ok(await h.host.submit(cmd)).replayed,true);const day=ok(await h.host.readMaintenanceDay(input));assert.equal(day.events.filter(e=>e.operation==='SaveJournalNote'&&e.stage==='succeeded').length,1);assert.equal(day.hasGaps,false);assert.equal(JSON.stringify([...l.partitions]).includes('私密全文'),false);const backup=ok(await h.host.prepareBackup());assert.equal(backup.text.includes('sourceHistoryIds'),false);assert.equal(backup.text.includes('私密全文'),true);});
test('B8 page and exact list URL capture records request/blocked only, rejects stale URL and retains epoch partitions',async()=>{const h=await b4Harness();logs(h);await h.host.retryMaintenance();const token=await h.token();ok(await h.host.navigatePage({token,page:'journal',previousPage:'today'}));const open=ok(await h.host.openListUrl({token,entry:ref(catalog.catalogEntries[3])},()=>null));assert.equal(open.outcome,'blocked');const day=ok(await h.host.readMaintenanceDay({epoch:token.epoch,date:'2026-10-06',zone:'UTC'}));const urls=day.events.filter(e=>e.category==='url');assert.equal(urls.length,2);assert.deepEqual(urls.map(e=>e.details.outcome),['requested','blocked']);assert.equal(urls.some(e=>e.stage==='succeeded'),false);let calls=0;const stale=await h.host.openListUrl({token,entry:{id:'link-a',version:999}},()=>{calls++;});assert.equal(stale.ok,false);assert.equal(calls,0);});
