// B5 author evidence: existing neutral sphere + A4 matrix + formal Host / real IDB.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
const root=fileURLToPath(new URL('../../',import.meta.url)),output=process.env.CARDGRID_B5_OUTPUT||path.join(root,'test-results/v06-b5/browser');await fs.mkdir(output,{recursive:true});
const {chromium}=await import(process.env.CARDGRID_PLAYWRIGHT_MODULE||'playwright');
const server=await createServer({root,configFile:false,logLevel:'error',server:{host:'127.0.0.1',port:0},optimizeDeps:{noDiscovery:true,entries:[],include:['react','react-dom/client','react/jsx-dev-runtime','@js-temporal/polyfill','jsbi']},plugins:[{name:'b5-page',configureServer(vite){vite.middlewares.use((req,res,next)=>{if(req.url==='/__v06b5'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script type="module" src="/tests/browser/v06-b5-harness.tsx"></script>');}else next();});}}]});
await server.listen();const origin=`http://127.0.0.1:${server.httpServer.address().port}`,results=[];let browser;
const data=page=>page.evaluate(()=>cg.data());
const question=async(page,id='which-book')=>{await page.getByRole('button',{name:'决策答案',exact:true}).click();await page.getByLabel('选择问题').selectOption(id);await page.getByRole('button',{name:'翻牌抽取',exact:true}).waitFor();};
async function test(name,fn,options={}){if(process.env.CARDGRID_B5_ONLY&&!new RegExp(process.env.CARDGRID_B5_ONLY).test(name))return;const {entry='/__v06b5',...contextOptions}=options;const context=await browser.newContext({serviceWorkers:'block',timezoneId:'Asia/Shanghai',viewport:{width:1280,height:900},...contextOptions}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto(origin+entry);if(entry==='/__v06b5')await page.getByRole('group',{name:'候选行动牌堆'}).waitFor();else await page.locator('nav').getByRole('button',{name:/数据与备份/}).waitFor();const detail=await fn(page,context);assert.deepEqual(errors,[]);results.push({name,status:'pass',detail});console.log('PASS',name);await page.screenshot({path:path.join(output,`${name}.png`),fullPage:true});}catch(e){results.push({name,status:'fail',error:e.stack});console.error('FAIL',name,e);await page.screenshot({path:path.join(output,`${name}-failure.png`),fullPage:true}).catch(()=>{});}finally{await context.close();}}
try{
  browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})});
  await test('decision-navigation-cancel-and-no-hidden-action',async page=>{
    await question(page);const before=await data(page);await page.getByRole('button',{name:'翻牌抽取',exact:true}).click();await page.locator('.dm6-back strong').filter({hasText:'合成书目甲'}).waitFor();
    await page.getByRole('button',{name:'行动抽卡',exact:true}).click();await page.getByRole('button',{name:'决策答案',exact:true}).click();await page.locator('.dm6-back strong').filter({hasText:'合成书目甲'}).waitFor();assert.deepEqual((await data(page)).handCards,before.handCards);
    await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'翻牌抽取',exact:true}).waitFor();assert.deepEqual((await data(page)).handCards,before.handCards);
    await page.getByRole('button',{name:'翻牌抽取',exact:true}).click();await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByText('已加入本次手牌；',{exact:false}).waitFor();const after=await data(page);assert.equal(after.handCards.filter(c=>c.kind==='answer').length,1);assert.equal(after.handCards.filter(c=>c.kind==='action').length,0);
    await page.reload();await page.getByText('已保存本次牌：1 张',{exact:true}).waitFor();assert.deepEqual((await data(page)).handCards,after.handCards);return {realIdb:true,reopenFixed:true,cancelWrites:0};
  });
  for(const id of ['which-food','which-exercise'])await test(`${id}-explicit-owner-and-reload`,async page=>{await question(page,id);await page.getByRole('button',{name:'手选候选',exact:true}).click();await page.locator('.dm6-candidates button').click();await page.getByRole('button',{name:'同时拿行动牌',exact:true}).click();await page.getByText('已保存本次牌：2 张',{exact:true}).waitFor();const before=await data(page),a=before.handCards.find(c=>c.kind==='answer'),action=before.handCards.find(c=>c.kind==='action');assert.equal(action.ownerAction.id,a.answer.ownerAction.id);await page.reload();await page.getByText('已保存本次牌：2 张',{exact:true}).waitFor();assert.deepEqual((await data(page)).handCards,before.handCards);return {domain:id,explicitOwner:true};});
  await test('action-scope-two-keyboard-steps-and-exact-id',async page=>{
    await page.getByRole('button',{name:'行动球面',exact:true}).click();await page.getByText('请勾选至少一个行动牌堆。',{exact:true}).waitFor();await page.getByRole('checkbox',{name:'行动一',exact:true}).check();await page.getByRole('checkbox',{name:'行动二',exact:true}).check();await page.getByRole('button',{name:'行动球面',exact:true}).click();const sphere=page.getByRole('dialog',{name:'卡球面'});await sphere.waitFor();assert.equal(await sphere.locator('.sphere-card').count(),3);assert.equal(await sphere.locator('strong').count(),0);const selected=sphere.locator('[data-card-id="meal"]');await selected.focus();await page.keyboard.press('Enter');assert.equal(await sphere.locator('strong').count(),0);await page.keyboard.press('Enter');await sphere.getByRole('button',{name:'接受行动，加入手牌'}).click();await page.getByText('已保存本次牌：1 张',{exact:true}).waitFor();const actual=(await data(page)).handCards.find(c=>c.kind==='action');assert.equal(actual.ownerAction.id,'meal');return {deduplicated:3,exactAction:'meal',twoSteps:true};
  },{reducedMotion:'reduce'});
  await test('decision-real-idb-abort-keeps-choice-and-retries',async page=>{
    await question(page);await page.getByRole('button',{name:'翻牌抽取',exact:true}).click();await page.locator('.dm6-back strong').waitFor();const before=await data(page);
    await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;window.__b5Put=original;IDBObjectStore.prototype.put=function(...args){const r=original.apply(this,args);if(this.name==='workspace')this.transaction.abort();return r;};});
    await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByRole('alert').filter({hasText:'STORAGE_FAILED'}).waitFor();assert.deepEqual(await data(page),before);await page.evaluate(()=>{IDBObjectStore.prototype.put=window.__b5Put;});await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByText('已保存本次牌：1 张',{exact:true}).waitFor();return {abortAtomic:true,retrySameSelection:true};
  });
  await test('action-real-idb-lost-reply-retry-does-not-take-twice',async page=>{await page.getByRole('checkbox',{name:'行动一',exact:true}).check();await page.getByLabel('手选行动').selectOption('read');await page.getByRole('button',{name:'翻开行动',exact:true}).click();await page.evaluate(()=>cg.loseNext());await page.getByRole('button',{name:'接受行动，加入手牌',exact:true}).click();await page.getByRole('button',{name:'重试本次保存'}).waitFor();assert.equal((await data(page)).handCards.filter(c=>c.kind==='action').length,1);await page.getByRole('button',{name:'重试本次保存'}).click();await page.getByRole('button',{name:'重试本次保存'}).waitFor({state:'detached'});assert.equal((await data(page)).handCards.filter(c=>c.kind==='action').length,1);return {oneMaterial:true};});
  await test('decision-two-window-stale-answer-does-not-redraw',async(page,context)=>{await question(page);await page.getByRole('button',{name:'翻牌抽取',exact:true}).click();await page.locator('.dm6-back strong').waitFor();const other=await context.newPage();await other.goto(origin+'/__v06b5');await other.getByRole('checkbox',{name:'行动一',exact:true}).check();await other.getByLabel('手选行动').selectOption('meal');await other.getByRole('button',{name:'翻开行动',exact:true}).click();await other.getByRole('button',{name:'接受行动，加入手牌'}).click();await other.getByText('已保存本次牌：1 张',{exact:true}).waitFor();await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByRole('alert').filter({hasText:'REVISION_CONFLICT'}).waitFor();assert.equal((await data(page)).handCards.filter(c=>c.kind==='answer').length,0);return {staleRefused:true};});
  await test('decision-lost-reply-navigation-keeps-the-original-retry',async page=>{await question(page);await page.getByRole('button',{name:'翻牌抽取',exact:true}).click();await page.locator('.dm6-back strong').waitFor();await page.evaluate(()=>cg.loseNext());await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByRole('alert').filter({hasText:'STORAGE_FAILED'}).waitFor();await page.getByRole('button',{name:'行动抽卡',exact:true}).click();await page.getByRole('button',{name:'决策答案',exact:true}).click();await page.locator('.dm6-back strong').waitFor();await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByText('已加入本次手牌；',{exact:false}).waitFor();assert.equal((await data(page)).handCards.filter(c=>c.kind==='answer').length,1);return {navigationRetry:true,oneAnswer:true};});
  await test('legacy-upload-shares-64mib-input-gate-and-does-not-write',async page=>{
    const read=()=>page.evaluate(async()=>{const {createWorkspaceStore}=await import('/src/workspace/store.ts');const store=createWorkspaceStore();try{return (await store.read())??null;}finally{store.close();}});
    const before=await read();await page.locator('nav').getByRole('button',{name:/数据与备份/}).click();const file=page.getByLabel('导入文件选择');
    const pack={format:'cardgrid',version:4,kind:'backup',dataFormat:'action-v4',data:{placeholder:'x'.repeat(6*1024*1024)}};
    await file.setInputFiles({name:'large-invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pack))});
    await page.locator('.message[role="status"]').filter({hasText:/\$\.data/}).waitFor();assert.equal(await page.getByText('文件超过 5 MiB',{exact:true}).count(),0);assert.deepEqual(await read(),before);
    // Disk fixture avoids Playwright's 50 MB in-memory payload ceiling. The UI
    // rejects the actual 64 MiB + 1 byte File before reading its content.
    const oversized=path.join(output,'synthetic-over-input.json'),handle=await fs.open(oversized,'w');try{await handle.truncate(64*1024*1024+1);}finally{await handle.close();}
    await file.setInputFiles(oversized);await page.getByText('文件超过 64 MiB',{exact:true}).waitFor();assert.deepEqual(await read(),before);
    return {above5ReachesParser:true,inputBytes:64*1024*1024+1,inputOver64Rejected:true,noWrites:true};
  },{entry:'/'});
  await test('narrow-320-static-scope-and-manual-decision',async page=>{await page.getByRole('checkbox',{name:'空行动',exact:true}).check();await page.getByRole('button',{name:'行动球面',exact:true}).click();await page.getByText('所选牌堆没有可用行动。',{exact:true}).waitFor();await question(page,'which-food');await page.getByRole('button',{name:'手选候选',exact:true}).click();await page.locator('.dm6-candidates button').click();await page.getByRole('button',{name:'只取答案',exact:true}).click();await page.getByText('已保存本次牌：1 张',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);return {width:320};},{viewport:{width:320,height:900},reducedMotion:'reduce'});
}finally{await fs.writeFile(path.join(output,'results.json'),JSON.stringify(results,null,2));await browser?.close();await server.close();}
console.log(`B5 formal browser: ${results.filter(r=>r.status==='pass').length}/${results.length}`);if(results.some(r=>r.status==='fail'))process.exitCode=1;
