// Author walkthrough. Every case uses a new browser context and synthetic IDB.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
const root=fileURLToPath(new URL('../../',import.meta.url));
const output=process.env.CARDGRID_B78_OUTPUT||path.join(root,'test-results/v06-b78/browser');await fs.mkdir(output,{recursive:true});
const {chromium}=await import(process.env.CARDGRID_PLAYWRIGHT_MODULE||'playwright');
const server=await createServer({root,configFile:false,logLevel:'error',server:{host:'127.0.0.1',port:0},optimizeDeps:{noDiscovery:true,entries:[],include:['react','react-dom/client','react/jsx-dev-runtime','@js-temporal/polyfill','jsbi']},plugins:[{name:'b78',configureServer(v){v.middlewares.use((req,res,next)=>{if(req.url==='/__v06b78'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script type="module" src="/tests/browser/v06-b78-harness.tsx"></script>');}else next();});}}]});
await server.listen();const origin=server.resolvedUrls.local[0].replace(/\/$/,''),results=[];let browser;
const data=p=>p.evaluate(()=>cg.data());
const nav=(p,label)=>p.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:label,exact:true});
const dock=p=>p.getByRole('dialog',{name:'本次手牌',exact:true});
async function open(p){const b=p.getByRole('button',{name:/^手牌 \d+ 张，展开$/});if(await b.count())await b.click();await dock(p).waitFor();}
const composite=p=>dock(p).locator('li').filter({hasText:'阅读《合成书目甲》'});
const answer=p=>dock(p).locator('section').filter({has:p.getByRole('heading',{name:/答案牌/})}).locator('li');
async function place(p){await open(p);await composite(p).getByRole('button',{name:'打出',exact:true}).click();const d=p.getByRole('dialog',{name:'排期与重叠确认',exact:true});await d.waitFor();await d.getByRole('button',{name:'确认排期',exact:true}).click();await d.waitFor({state:'detached'});await p.getByRole('heading',{name:'已排计划（1）',exact:true}).waitFor();}
async function attach(p){await open(p);await answer(p).getByRole('button',{name:'打出',exact:true}).click();const d=p.getByRole('dialog',{name:'放置答案参考',exact:true});await d.waitFor();await d.getByRole('button',{name:'预览参考'}).click();await d.getByRole('button',{name:'确认放置参考'}).click();await d.waitFor({state:'detached'});await p.locator('[data-reference-id]').waitFor();}
async function run(name,fn,width=1280){const context=await browser.newContext({viewport:{width,height:900},timezoneId:'Asia/Shanghai',serviceWorkers:'block',reducedMotion:'reduce'}),p=await context.newPage(),errors=[];p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));try{await p.clock.setFixedTime(new Date('2026-10-06T00:12:00Z'));await p.goto(origin+'/__v06b78');await p.locator('.dial-svg').waitFor();await p.getByRole('button',{name:'手牌 2 张，展开'}).waitFor();const detail=await fn(p,context);assert.deepEqual(errors,[]);results.push({name,status:'pass',detail});console.log('PASS',name);await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});}catch(e){results.push({name,status:'fail',error:e.stack,pageErrors:errors,ui:await p.locator('body').innerText().catch(()=>'' )});console.error('FAIL',name,e);await p.screenshot({path:path.join(output,name+'-failure.png'),fullPage:true}).catch(()=>{});}finally{await context.close();}}
try{
  browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})});
  await run('today-reference-fact-journal-reload',async p=>{await open(p);const before=await data(p);await composite(p).getByRole('button',{name:'打出',exact:true}).click();const d=p.getByRole('dialog',{name:'排期与重叠确认'});await d.waitFor();await d.getByRole('button',{name:'取消',exact:true}).click();assert.deepEqual(await data(p),before);await place(p);await attach(p);const arranged=await data(p);assert.equal(arranged.planner.plans.length,1);assert.equal(arranged.referencePlacements.length,1);assert.equal(arranged.planner.facts.length,0);await p.locator('.dayboard-row').getByRole('button',{name:'确认实际',exact:true}).click();const actual=p.getByRole('dialog',{name:'确认实际发生',exact:true});await actual.waitFor();await actual.getByLabel('结束时间',{exact:true}).fill('09:25');await actual.getByRole('button',{name:'确认实际',exact:true}).click();await actual.waitFor({state:'detached'});await p.getByText(/已冻结：合成书目甲/).waitFor();const confirmed=await data(p);assert.equal(confirmed.factReferenceSnapshots.length,1);assert.equal(confirmed.planner.facts.length,1);await nav(p,'时间线日记').click();await p.getByRole('region',{name:'时间线日记'}).getByText(/已确认事实/).waitFor();const note=p.getByRole('textbox',{name:'独立感想',exact:true});await note.fill('本次独立感想');await p.getByRole('button',{name:'立即保存',exact:true}).click();await p.getByText('随记保存：已保存到本机',{exact:true}).waitFor();const saved=await data(p);assert.equal(saved.journalNotes.length,1);await p.reload();await p.locator('.dial-svg').waitFor();assert.deepEqual((await data(p)).planner.facts,saved.planner.facts);await nav(p,'时间线日记').click();await p.getByText(/本次独立感想/).waitFor();return {realIdb:true,planCount:1,factCount:1,automaticFromDial:true,notes:1};});
  await run('attached-retract-retains-reflection-and-library',async p=>{await place(p);await attach(p);await nav(p,'时间线日记').click();await p.getByRole('textbox',{name:'独立感想',exact:true}).fill('收回也保留');await p.getByRole('button',{name:'立即保存'}).click();await p.getByText('随记保存：已保存到本机').waitFor();const before=await data(p);await nav(p,'Today').click();await p.getByRole('button',{name:'撤回手牌',exact:true}).click();await p.getByRole('heading',{name:'已排计划（0）',exact:true}).waitFor();const after=await data(p);assert.equal(after.referencePlacements[0].state,'returned');assert.deepEqual(after.journalNotes,before.journalNotes);assert.deepEqual(after.actionCards,before.actionCards);await nav(p,'时间线日记').click();assert.equal(await p.getByRole('region',{name:'时间线日记'}).getByText(/ · 计划/).count(),0);return {returnedSameAnswer:true,notesUnchanged:true};});
  await run('independent-point-zero-occupancy-and-cross-page-gate',async p=>{await open(p);const before=await data(p);await answer(p).getByRole('button',{name:'打出',exact:true}).click();const dialog=p.getByRole('dialog',{name:'放置答案参考'});await dialog.getByLabel('位置').selectOption('point');await dialog.getByLabel('当地时点').fill('23:55');await dialog.getByRole('button',{name:'预览参考'}).click();await dialog.getByRole('button',{name:'确认放置参考'}).click();await dialog.waitFor({state:'detached'});await p.getByText(/独立时点 · 0 分钟/).waitFor();const after=await data(p);assert.deepEqual(after.planner.plans,before.planner.plans);await nav(p,'工坊').click();await p.locator('.we2').waitFor();assert.equal(await dock(p).getByRole('button',{name:'打出',exact:true}).count(),0);return {point:true,occupiedMinutes:0};});
  await run('journal-failure-blocks-navigation-same-request-recovery',async p=>{await nav(p,'时间线日记').click();await p.evaluate(()=>{const base=cg.store.atomic.bind(cg.store);let failed=false;cg.store.atomic=async r=>{if(!failed){failed=true;throw Error('synthetic journal write failure');}return base(r);};});await p.getByRole('textbox',{name:'独立感想',exact:true}).fill('不能丢失的草稿');await nav(p,'Today').click();await p.getByText('感想尚未保存，草稿保留在当前页面').waitFor();assert.equal(await p.getByRole('textbox',{name:'独立感想',exact:true}).inputValue(),'不能丢失的草稿');assert.equal((await data(p)).journalNotes.length,0);await nav(p,'Today').click();await p.locator('.dial-svg').waitFor();assert.equal((await data(p)).journalNotes.length,1);return {navigationHeld:true,retryCreatesOneNote:true};});
  await run('maintenance-real-idb-failure-retry-private-text-and-list-url',async p=>{await p.evaluate(()=>{const put=IDBObjectStore.prototype.put;window.undoLogFailure=()=>{IDBObjectStore.prototype.put=put;};IDBObjectStore.prototype.put=function(...a){const r=put.apply(this,a);if(this.name==='maintenance')this.transaction.abort();return r;};});await nav(p,'时间线日记').click();await p.getByRole('textbox',{name:'独立感想',exact:true}).fill('不应进入维护正文');await p.getByRole('button',{name:'立即保存'}).click();await p.getByText('随记保存：已保存到本机').waitFor();assert.equal((await data(p)).journalNotes.length,1);await nav(p,'维护日志').click();await p.getByText('存在未落库事件缺口').waitFor();await p.evaluate(()=>undoLogFailure());await p.getByRole('button',{name:'补写并刷新'}).click();await p.getByText('本批采集无已知缺口').waitFor();assert.equal(await p.getByRole('region',{name:'维护日志'}).getByText('不应进入维护正文').count(),0);await p.evaluate(async()=>{const d=await cg.data();return cg.host.openListUrl({token:await cg.token(),entry:cg.ref(d.catalogEntries.find(e=>e.id==='link-a'))},()=>null);});await p.getByRole('button',{name:'补写并刷新'}).click();await p.getByText(/OpenListUrl · requested/).waitFor();await p.getByText(/URL_OPEN_BLOCKED/).waitFor();await p.reload();await nav(p,'维护日志').click();await p.getByText(/OpenListUrl · requested/).waitFor();return {separateRealIdb:true,businessCommittedDuringLogAbort:true,privateTextAbsent:true,urlRequestOnly:true};});
  await run('two-window-journal-authority-and-backup-roundtrip',async(p,c)=>{await nav(p,'时间线日记').click();const other=await c.newPage();await other.goto(origin+'/__v06b78');await other.locator('.dial-svg').waitFor();await other.evaluate(async()=>cg.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'另一窗口保存'}));await p.getByText(/另一窗口保存/).waitFor();const value=await p.evaluate(async()=>{const d=await cg.data(),b=cg.ok(await cg.host.prepareBackup());return {data:d,text:b.text};});assert.deepEqual(JSON.parse(value.text).data,value.data);await p.reload();await nav(p,'时间线日记').click();await p.getByText(/另一窗口保存/).waitFor();return {broadcast:true,fullJsonIncludesNotes:true};});
  await run('default-entry-selects-v5-and-preserves-format-on-read',async p=>{const before=await data(p);await p.evaluate(async()=>{const raw=(await cg.evidence()).raw;const db=await new Promise((r,j)=>{const q=indexedDB.open('cardgrid-workspace',4);q.onupgradeneeded=()=>{for(const name of ['workspace','recovery','maintenance','text-output'])if(!q.result.objectStoreNames.contains(name))q.result.createObjectStore(name);};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});await new Promise((r,j)=>{const tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put(raw,'current');tx.oncomplete=r;tx.onabort=()=>j(tx.error);});db.close();});await p.goto(origin);await p.locator('.dial-svg').waitFor();await nav(p,'Today').waitFor();await p.getByRole('button',{name:'手牌 2 张，展开'}).waitFor();const actual=await p.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('cardgrid-workspace');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});const v=await new Promise(r=>{const q=db.transaction('workspace').objectStore('workspace').get('current');q.onsuccess=()=>r(q.result);});db.close();return v.data;});assert.deepEqual(actual,before);return {defaultEntry:true,noAutomaticMigration:true};});
  await run('default-v4-explicit-upgrade-cancel-and-exact-preservation',async p=>{await p.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('cardgrid-workspace',4);q.onupgradeneeded=()=>{for(const name of ['workspace','recovery','maintenance','text-output'])q.result.createObjectStore(name);};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});await new Promise((r,j)=>{const tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put({schemaVersion:4,epoch:'synthetic-v4-root',revision:5,mode:'current',dataFormat:'action-v4',lifecycleReceipt:null,data:cg.syntheticOld},'current');tx.oncomplete=r;tx.onabort=()=>j(tx.error);});db.close();});await p.goto(origin);const raw=()=>p.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('cardgrid-workspace');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});const v=await new Promise(r=>{const q=db.transaction('workspace').objectStore('workspace').get('current');q.onsuccess=()=>r(q.result);});db.close();return v;});await p.getByRole('button',{name:'预览通用卡牌升级',exact:true}).waitFor();for(let attempt=0;attempt<200;attempt++){if((await raw()).data.dailyCopies.length===1)break;await p.waitForTimeout(50);}const before=await raw();assert.equal(before.data.dailyCopies.length,1,'await legacy inventory initialization before measuring preview writes');await p.getByRole('button',{name:'预览通用卡牌升级',exact:true}).click();await p.getByRole('button',{name:'确认升级并丢弃旧草稿',exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'确认升级并丢弃旧草稿',exact:true}).isDisabled(),true);assert.deepEqual(await raw(),before);await p.getByRole('button',{name:'取消升级',exact:true}).click();assert.deepEqual(await raw(),before);await p.getByRole('button',{name:'预览通用卡牌升级',exact:true}).click();await p.getByRole('checkbox',{name:'升级前完整备份已保存'}).check();await p.getByRole('button',{name:'确认升级并丢弃旧草稿',exact:true}).click();await nav(p,'Today').waitFor();const after=await raw();assert.equal(after.data.version,5);assert.notEqual(after.epoch,before.epoch);assert.deepEqual(after.data.journalEntries,before.data.journalEntries);assert.deepEqual(after.data.planner.facts,before.data.planner.facts);return {explicitBackupConfirmation:true,cancelWrites:0,oldFactsAndJournalExact:true};});
  await run('a5-list-url-button-uses-formal-collector',async p=>{await nav(p,'工坊').click();await p.locator('.we2').waitFor();await p.locator('.act-card').filter({hasText:'独立清单'}).getByRole('button',{name:'管理成员'}).click();const panel=p.getByRole('dialog',{name:'独立清单 成员管理',exact:true});await panel.waitFor();await p.evaluate(()=>{window.open=()=>null;});const before=await data(p);await panel.getByRole('button',{name:'打开网址',exact:true}).click();await p.getByText('浏览器未能打开网址',{exact:true}).waitFor();assert.deepEqual(await data(p),before);await panel.getByRole('button',{name:'关闭',exact:true}).click();await nav(p,'维护日志').click();await p.getByText(/OpenListUrl · requested/).waitFor();await p.getByText(/URL_OPEN_BLOCKED/).waitFor();return {fromActualListButton:true,noBusinessWrites:true,noExternalBrowsingCapture:true};});
  await run('decision-keeps-fixed-answer-across-app-navigation',async p=>{await nav(p,'抽卡与决策').click();await p.getByRole('button',{name:'决策答案',exact:true}).click();await p.getByRole('combobox',{name:'选择问题',exact:true}).selectOption('which-book');await p.getByRole('button',{name:'翻牌抽取',exact:true}).click();await p.getByText('答案已固定：刷新或导航不会重新抽取；重抽是一次新的选择').waitFor();const before=await data(p);await nav(p,'时间线日记').click();await p.getByRole('textbox',{name:'独立感想',exact:true}).waitFor();await nav(p,'抽卡与决策').click();await p.getByRole('button',{name:'只取答案',exact:true}).waitFor();assert.deepEqual(await data(p),before);return {questionRemembered:true,noRerollOnNavigation:true,noBusinessWrites:true};});
  await run('narrow-keyboard-journal-and-dark-hand',async p=>{await p.evaluate(async()=>{const d=await cg.data();cg.ok(await cg.host.submit({commandId:crypto.randomUUID(),expected:await cg.token(),type:'SaveSettings',payload:{settings:{...d.settings,preferences:{...d.settings.preferences,theme:'night'}}}}));});await p.locator('.app.night').first().waitFor();await p.getByRole('button',{name:'手牌 2 张，展开'}).focus();await p.keyboard.press('Enter');await dock(p).waitFor();const colors=await dock(p).evaluate(e=>({bg:getComputedStyle(e).backgroundColor,fg:getComputedStyle(e).color}));assert.notEqual(colors.bg,'rgba(0, 0, 0, 0)');await nav(p,'时间线日记').click();await p.getByRole('button',{name:'关闭手牌'}).click();await p.getByRole('textbox',{name:'独立感想',exact:true}).fill('320px 键盘感想');await p.getByRole('button',{name:'立即保存'}).click();await p.getByText('随记保存：已保存到本机').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);return {width:320,keyboard:true,colors};},320);
}finally{await browser?.close();await server.close();await fs.writeFile(path.join(output,'results.json'),JSON.stringify({scope:'B7/B8 author regression, outside acceptance pending',passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results},null,2));}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
