// B6 author regression: synthetic DBs, real formal hand reads and legacy Today commands.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
import {hand,envelope} from '../fixtures/action/independent.ts';
const root=fileURLToPath(new URL('../../',import.meta.url)),output=process.env.CARDGRID_B6_OUTPUT||path.join(root,'test-results/v06-b6/browser');await fs.mkdir(output,{recursive:true});
const {chromium}=await import(process.env.CARDGRID_PLAYWRIGHT_MODULE||'playwright');
const server=await createServer({root,configFile:false,logLevel:'error',server:{host:'127.0.0.1',port:0},optimizeDeps:{noDiscovery:true,entries:[],include:['react','react-dom/client','react/jsx-dev-runtime','@js-temporal/polyfill','jsbi']},plugins:[{name:'b6-page',configureServer(vite){vite.middlewares.use((req,res,next)=>{if(req.url==='/__v06b6'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script type="module" src="/tests/browser/v06-b6-harness.tsx"></script>');}else next();});}}]});
await server.listen();const origin=server.resolvedUrls.local[0].replace(/\/$/,''),results=[];let browser;
const raw=p=>p.evaluate(()=>cg.evidence());
const dock=p=>p.getByRole('dialog',{name:'本次手牌',exact:true});
const open=async p=>{await p.getByRole('button',{name:/^手牌 \d+ 张，展开$/}).click();await dock(p).waitFor();};
async function writeLegacy(page,value,notify=false){await page.evaluate(async({value,notify})=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('cardgrid-workspace');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});await new Promise((r,j)=>{const t=db.transaction('workspace','readwrite');t.objectStore('workspace').put(value,'current');t.oncomplete=r;t.onabort=()=>j(t.error);});db.close();if(notify){const c=new BroadcastChannel('cardgrid-workspace:v4');c.postMessage({epoch:value.epoch,revision:value.revision});setTimeout(()=>c.close(),100);}}, {value,notify});}
const legacyRaw=page=>page.evaluate(async()=>{const db=await new Promise((r,j)=>{const q=indexedDB.open('cardgrid-workspace');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});const v=await new Promise((r,j)=>{const q=db.transaction('workspace').objectStore('workspace').get('current');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error);});db.close();return v;});
async function legacySetup(page){await page.goto(origin);await page.getByRole('button',{name:'重新载入',exact:true}).waitFor();const d=hand(),i=d.planner.instances[0];const data={...d,planner:{...d.planner,instances:[i,{...i,id:'i-other'}],handOrder:['i','i-other']}};await writeLegacy(page,envelope(data));await page.reload();await page.locator('.dial-svg').waitFor();}
async function run(name,fn,{entry='/__v06b6',viewport={width:1280,height:900}}={}){const context=await browser.newContext({viewport,timezoneId:'Asia/Shanghai',serviceWorkers:'block',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(8000);try{await page.clock.setFixedTime(new Date('2026-10-06T00:12:00Z'));await page.goto(origin+entry);await page.getByRole('button',{name:/^手牌 \d+ 张，展开$/}).waitFor();const detail=await fn(page,context);assert.deepEqual(errors,[]);results.push({name,status:'pass',detail});console.log('PASS',name);await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});}catch(e){results.push({name,status:'fail',error:e.stack,pageErrors:errors,ui:await page.locator('body').innerText().catch(()=>'' )});console.error('FAIL',name,e);await page.screenshot({path:path.join(output,name+'-failure.png'),fullPage:true}).catch(()=>{});}finally{await context.close();}}
try{
  browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})});
  await run('formal-all-kinds-cross-page-no-writes',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();const before=await raw(p);await open(p);assert.equal(await dock(p).locator('li').count(),5);for(const title of ['行动牌（2）','答案牌（1）','成品牌（1）','资源素材（1）'])await dock(p).getByRole('heading',{name:title,exact:true}).waitFor();for(const page of ['决策','日记','工坊']){await p.getByRole('button',{name:page,exact:true}).click();assert.equal(await dock(p).locator('li').count(),5);assert.equal(await dock(p).getByRole('button',{name:'打出',exact:true}).count(),0);}assert.deepEqual(await raw(p),before);return {kinds:4,persistentProjection:true,writes:0};});
  await run('preview-exact-duplicate-focus-escape',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await open(p);const rows=dock(p).locator('li').filter({hasText:'阅读《{对象}》'}),ids=await rows.evaluateAll(es=>es.map(e=>e.dataset.handId));assert.equal(ids.length,2);assert.notEqual(ids[0],ids[1]);await rows.nth(1).getByRole('button',{name:'预览',exact:true}).click();const detail=p.getByRole('dialog',{name:'手牌详情'});await detail.waitFor();assert.match(await detail.innerText(),new RegExp(ids[1]));await p.keyboard.press('Escape');await detail.waitFor({state:'detached'});assert.equal(await rows.nth(1).getByRole('button',{name:'预览'}).evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');await dock(p).waitFor({state:'detached'});assert.equal(await p.getByRole('button',{name:'手牌 5 张，展开'}).evaluate(e=>e===document.activeElement),true);return {exactIdentity:true,focusReturned:true};});
  await run('today-gated-intent-incomplete-and-resource',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await open(p);const before=await raw(p);await p.getByRole('button',{name:'Today',exact:true}).click();const buttons=dock(p).getByRole('button',{name:'打出',exact:true});assert.equal(await buttons.count(),5);assert.equal(await dock(p).locator('button:disabled').count(),3);const answer=dock(p).locator('section').filter({has:p.getByRole('heading',{name:'答案牌（1）',exact:true})}).locator('li');const id=await answer.getAttribute('data-hand-id');await answer.getByRole('button',{name:'打出',exact:true}).click();await p.getByText(`已选择本次 ID ${id}，尚未保存安排`,{exact:true}).waitFor();const intent=await p.evaluate(()=>handIntents);assert.equal(intent.length,1);assert.equal(intent[0].item.id,id);assert.deepEqual(await raw(p),before);await p.getByRole('button',{name:'日记',exact:true}).click();assert.equal(await dock(p).getByRole('button',{name:'打出',exact:true}).count(),0);return {validatedIntentOnly:true,noFalseSave:true};});
  await run('formal-consumption-removes-preview-and-retains-library',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await open(p);const answer=dock(p).locator('section').filter({has:p.getByRole('heading',{name:'答案牌（1）',exact:true})}).locator('li');await answer.getByRole('button',{name:'预览'}).click();const before=await raw(p);await p.evaluate(async()=>{const d=await cg.data(),a=d.handCards.find(c=>c.kind==='answer'&&c.state==='available'),b=d.handCards.find(c=>c.kind==='action'&&c.state==='available'),s=cg.ok(await cg.host.previewSynthesis({token:await cg.token(),inputs:[cg.ref(a),cg.ref(b)],resolutions:[]}));await cg.submit('ConfirmSynthesis',{previewId:s.previewId});});await p.getByRole('button',{name:'手牌 4 张，收起'}).waitFor();await p.getByRole('dialog',{name:'手牌详情'}).waitFor({state:'detached'});const after=await raw(p);assert.deepEqual(after.raw.data.actionCards,before.raw.data.actionCards);assert.deepEqual(after.raw.data.journalEntries,before.raw.data.journalEntries);return {atomicHandProjection:true};});
  await run('formal-two-window-update-and-reload',async(p,c)=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await open(p);const other=await c.newPage();await other.goto(origin+'/__v06b6');await other.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await other.evaluate(async()=>cg.submit('TakeEntryMaterial',{entry:cg.ref(cg.catalog.catalogEntries[3])}));await p.getByRole('button',{name:'手牌 6 张，收起'}).waitFor();const before=await raw(p);await p.reload();await p.getByRole('button',{name:'手牌 6 张，展开'}).waitFor();assert.deepEqual(await raw(p),before);return {broadcastAndReload:true};});
  await run('formal-read-failure-and-explicit-refresh-preserve-data',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await open(p);const before=await raw(p);await p.evaluate(()=>{window.savedHandRead=cg.host.readUnifiedHand;cg.host.readUnifiedHand=async()=>({ok:false,code:'STORAGE_FAILED',message:'注入查询故障',retry:'reload'});window.dispatchEvent(new Event('focus'));});await dock(p).getByRole('alert').filter({hasText:'注入查询故障'}).waitFor();assert.equal(await dock(p).locator('li').count(),0);await p.evaluate(()=>{cg.host.readUnifiedHand=window.savedHandRead;});await dock(p).getByRole('button',{name:'重新读取手牌',exact:true}).click();await p.getByRole('button',{name:'手牌 5 张，收起'}).waitFor();assert.equal(await dock(p).locator('li').count(),5);assert.deepEqual(await raw(p),before);return {readFailureSafe:true,explicitRefresh:true,writes:0};});
  await run('formal-epoch-replacement-clears-detail',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await open(p);await dock(p).locator('li').first().getByRole('button',{name:'预览'}).click();await p.evaluate(async()=>{const token=await cg.token(),backup=await cg.backup(),preview=cg.ok(await cg.host.previewRestore({token,text:cg.ok(await cg.host.prepareBackup()).text}));cg.ok(await cg.host.submit({type:'RestoreWorkspace',commandId:crypto.randomUUID(),expected:token,payload:{previewId:preview.previewId,backup,discardDraftsConfirmed:true}}));});await p.getByRole('dialog',{name:'手牌详情'}).waitFor({state:'detached'});assert.equal(await dock(p).locator('li').count(),5);return {oldPreviewCleared:true};});
  await run('narrow-320-keyboard-and-independent-list',async p=>{await p.getByRole('button',{name:'手牌 5 张，展开'}).waitFor();await p.getByRole('button',{name:'手牌 5 张，展开'}).focus();await p.keyboard.press('Enter');await dock(p).waitFor();await dock(p).locator('li').last().getByRole('button',{name:'预览'}).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:path.join(output,'narrow-320-expanded-detail.png'),fullPage:true});await p.keyboard.press('Escape');await p.getByRole('button',{name:'关闭手牌'}).click();assert.equal(await p.getByRole('button',{name:'手牌 5 张，展开'}).evaluate(e=>e===document.activeElement),true);return {width:320,noHorizontalOverflow:true};},{viewport:{width:320,height:640}});
  await run('default-app-float-non-today-readonly-and-reload',async p=>{await legacySetup(p);await open(p);const before=await legacyRaw(p);await p.locator('nav').getByRole('button',{name:/制卡工坊/}).click();assert.equal(await dock(p).locator('li').count(),2);assert.equal(await dock(p).getByRole('button',{name:'打出',exact:true}).count(),0);await dock(p).locator('li').nth(1).getByRole('button',{name:'预览'}).click();assert.match(await p.getByRole('dialog',{name:'手牌详情'}).innerText(),/i-other/);assert.deepEqual(await legacyRaw(p),before);await p.reload();await p.getByRole('button',{name:'手牌 2 张，展开'}).waitFor();assert.deepEqual(await legacyRaw(p),before);return {defaultEntry:true,writes:0};},{entry:'/'});
  await run('default-today-exact-duplicate-play-cancel-confirm-refresh',async p=>{await legacySetup(p);await p.getByLabel('日期',{exact:true}).fill('2026-10-06');await p.getByLabel('默认落点',{exact:true}).fill('09:00');await open(p);const before=await legacyRaw(p);const item=dock(p).locator('[data-hand-id="i-other"]');await item.getByRole('button',{name:'打出',exact:true}).click();const dialog=p.getByRole('dialog',{name:'排期与重叠确认',exact:true});await dialog.waitFor();assert.deepEqual(await legacyRaw(p),before);await dialog.getByRole('button',{name:'关闭',exact:true}).click();await item.getByRole('button',{name:'打出',exact:true}).click();await dialog.getByRole('button',{name:'确认排期',exact:true}).click();await dialog.waitFor({state:'detached'});await p.getByRole('button',{name:'手牌 1 张，收起'}).waitFor();const after=await legacyRaw(p);assert.equal(after.data.planner.plans[0].instanceId,'i-other');assert.deepEqual(after.data.planner.handOrder,['i']);await p.reload();assert.deepEqual(await legacyRaw(p),after);return {realIdb:true,exactId:'i-other',cancelWrites:0,confirmedPlans:1};},{entry:'/'});
  await run('default-night-hand-surface-readable',async p=>{await legacySetup(p);const fixture=await legacyRaw(p);fixture.data.settings.preferences.theme='night';await writeLegacy(p,fixture);await p.reload();await p.locator('.app.night').waitFor();await open(p);const colors=await dock(p).evaluate(e=>{const s=getComputedStyle(e);return {background:s.backgroundColor,foreground:s.color};});const values=c=>c.match(/\d+/g).map(Number).slice(0,3),brightness=c=>values(c).reduce((a,b)=>a+b,0)/3;assert.ok(brightness(colors.background)<100);assert.ok(brightness(colors.foreground)>150);assert.equal(await dock(p).locator('li').count(),2);return {theme:'night',colors};},{entry:'/'});
  await run('default-narrow-empty-hand-close-focus',async p=>{await open(p);await dock(p).getByText('手牌为空。',{exact:false}).waitFor();assert.equal(await dock(p).getByRole('button',{name:'打出',exact:true}).count(),0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.keyboard.press('Escape');assert.equal(await p.getByRole('button',{name:'手牌 0 张，展开'}).evaluate(e=>e===document.activeElement),true);return {empty:true,width:320};},{entry:'/',viewport:{width:320,height:640}});
}finally{await browser?.close();await server.close();await fs.writeFile(path.join(output,'results.json'),JSON.stringify({scope:'B6 author walkthrough; B7 formal Today seam not an accepted plan',passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results},null,2));}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
