// Author evidence: fresh browser contexts, synthetic DB names, no personal profiles/data.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
const root=fileURLToPath(new URL('../../',import.meta.url)),output=process.env.CARDGRID_B4_OUTPUT||path.join(root,'test-results/v06-b4/browser');await fs.mkdir(output,{recursive:true});
const {chromium}=await import(process.env.CARDGRID_PLAYWRIGHT_MODULE||'playwright');
const server=await createServer({root,configFile:false,server:{host:'127.0.0.1',port:0},optimizeDeps:{noDiscovery:true,entries:[],include:['@js-temporal/polyfill','jsbi']},plugins:[{name:'b4-isolated',configureServer(vite){vite.middlewares.use((req,res,next)=>{if(req.url==='/__b4'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>B4 isolated storage checks</title>');}else next();});}}],logLevel:'error'});
await server.listen();const origin=`http://127.0.0.1:${server.httpServer.address().port}`,results=[];let browser;
try{
  browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})});
  async function pageIn(context,name='b4-synthetic'){const page=await context.newPage();await page.goto(origin+'/__b4');await page.evaluate(async name=>{const {installB4}=await import('/tests/browser/v06-b4-harness.ts');globalThis.cg=installB4(name);},name);return page;}
  async function check(name,fn){const context=await browser.newContext({serviceWorkers:'block',timezoneId:'Asia/Shanghai'}),started=Date.now();try{const detail=await fn(context);results.push({name,status:'pass',durationMs:Date.now()-started,detail});console.log('PASS',name);}catch(e){results.push({name,status:'fail',error:e.stack});console.error('FAIL',name,e);await context.pages().at(-1)?.screenshot({path:path.join(output,`failure-${name}.png`)}).catch(()=>{});}finally{await context.close();}}
  await check('db-v3-to-v4-adds-slots-without-business-migration',async ctx=>{const p=await pageIn(ctx);const r=await p.evaluate(async()=>{
    cg.host.close();const open=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('old-db',3);r.onupgradeneeded=()=>{r.result.createObjectStore('workspace');r.result.createObjectStore('recovery');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
    const db=await open(),old={schemaVersion:4,epoch:'old-epoch',revision:2,lifecycleReceipt:null,mode:'current',dataFormat:'action-v4',data:(await import('/src/workspace/format.ts')).emptyWorkspaceData()};
    await new Promise((resolve,reject)=>{const tx=db.transaction('workspace','readwrite');tx.objectStore('workspace').put(old,'current');tx.oncomplete=resolve;tx.onabort=reject;});db.close();
    const S=await import('/src/workspace/store.ts'),s=S.createWorkspaceStore({name:'old-db'});const loaded=await s.read();s.close();const fresh=await new Promise(resolve=>{const r=indexedDB.open('old-db',4);r.onsuccess=()=>resolve(r.result);});const stores=[...fresh.objectStoreNames];fresh.close();return {old,loaded,stores};});
    assert.deepEqual(r.loaded,r.old);assert.deepEqual(r.stores,['maintenance','recovery','text-output','workspace']);return {businessUnchanged:true,stores:r.stores};});
  await check('real-synthesis-abort-at-recovery-and-current-rolls-back-all',async ctx=>{const p=await pageIn(ctx);const r=await p.evaluate(async()=>{await cg.setup();const s=await cg.synthesis();const failures=[];for(const name of ['recovery','workspace'])failures.push(await cg.abort(s.command,name));const result=cg.ok(await cg.host.submit(s.command)),after=await cg.evidence(),replay=cg.ok(await cg.host.submit(s.command));return {failures,result,after,replay,final:await cg.evidence()};});for(const f of r.failures){assert.equal(f.result.code,'STORAGE_FAILED');assert.deepEqual(f.after,f.before);}assert.equal(r.replay.replayed,true);assert.deepEqual(r.after,r.final);return {aborts:2,atomicCollections:['inputs','output','instances','history','receipt','previous']};});
  await check('lost-real-commit-reply-reload-replays-receipt-without-session',async ctx=>{const p=await pageIn(ctx);const r=await p.evaluate(async()=>{await cg.setup();const s=await cg.synthesis();cg.loseNext();const failed=await cg.host.submit(s.command);const after=await cg.evidence();cg.host.invalidateCapabilities();const replay=cg.ok(await cg.host.submit(s.command));return {failed,after,replay,final:await cg.evidence()};});assert.equal(r.failed.code,'STORAGE_FAILED');assert.equal(r.replay.replayed,true);assert.deepEqual(r.after,r.final);return {persistedReplay:true};});
  await check('two-real-windows-compete-notify-and-preserve-winning-commit',async ctx=>{const a=await pageIn(ctx),b=await pageIn(ctx);await a.evaluate(()=>cg.setup());const command=await a.evaluate(()=>cg.command('TakeEntryMaterial',{entry:cg.ref(cg.catalog.catalogEntries[0])}));const pair=await Promise.all([a.evaluate(c=>cg.host.submit(c),command),b.evaluate(c=>cg.host.submit({...c,commandId:'other-window'}),command)]);assert.equal(pair.filter(r=>r.ok).length,1);assert.equal(pair.find(r=>!r.ok).code,'REVISION_CONFLICT');await b.waitForFunction(()=>cg.external>0);return {winner:pair.find(r=>r.ok).value.token,conflict:pair.find(r=>!r.ok).code};});
  await check('replacement-epoch-invalidates-preview-old-and-v5-backups-restore-exactly',async ctx=>{const p=await pageIn(ctx);const r=await p.evaluate(async()=>{const old=await cg.setup(),s=await cg.synthesis(),before=await cg.data(),oldText=JSON.stringify({format:'cardgrid',version:4,kind:'backup',dataFormat:'action-v4',data:old});let preview=cg.ok(await cg.host.previewRestore({token:await cg.token(),text:oldText}));const cmd={commandId:'restore-old',type:'RestoreWorkspace',expected:await cg.token(),payload:{previewId:preview.previewId,backup:await cg.backup(),discardDraftsConfirmed:true}};cg.ok(await cg.host.submit(cmd));const restoredOld=await cg.data(),stale=await cg.host.submit(s.command);preview=cg.ok(await cg.host.previewRestore({token:await cg.token(),text:JSON.stringify(cg.backupV5(before))}));cg.ok(await cg.host.submit({commandId:'restore-v5',type:'RestoreWorkspace',expected:await cg.token(),payload:{previewId:preview.previewId,backup:await cg.backup(),discardDraftsConfirmed:true}}));return {old,restoredOld,stale,before,restoredV5:await cg.data()};});assert.deepEqual(r.old,r.restoredOld);assert.deepEqual(r.before,r.restoredV5);assert.equal(r.stale.code,'WORKSPACE_REPLACED');return {v4Exact:true,v5Exact:true,stale:r.stale.code};});
  await check('committed-data-survives-page-reload-with-original-journal-bytes',async ctx=>{let p=await pageIn(ctx);await p.evaluate(async()=>{await cg.setup();await cg.answer(true);await cg.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-05',zone:'Asia/Shanghai',text:'补记\r\n  文本'});});const before=await p.evaluate(()=>cg.evidence());await p.close();p=await pageIn(ctx);const after=await p.evaluate(()=>cg.evidence());assert.deepEqual(after,before);return {notes:after.raw.data.journalNotes.length,legacyText:after.raw.data.journalEntries[0].text};});
  await check('active-json-exact-boundary-and-oversize-abort-real-idb',async ctx=>{const p=await pageIn(ctx);const r=await p.evaluate(async()=>{
    await cg.setup();const before=await cg.evidence(),large='容'.repeat(2*1024*1024);const accepted=await cg.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:large});const note=(await cg.data()).journalNotes[0],above5=await cg.evidence();
    const backup=cg.ok(await cg.host.prepareBackup());const restore=cg.ok(await cg.host.previewRestore({token:await cg.token(),text:backup.text}));
    // Updating retains the previous full text in history: the active package gate counts BOTH.
    const cmd=await cg.command('SaveJournalNote',{id:note.id,expectedVersion:note.version,date:note.date,zone:note.zone,text:'x'.repeat(cg.MAX_BACKUP_BYTES)}),oversize=await cg.host.submit(cmd);const after=await cg.evidence();
    const exact=structuredClone(above5.raw.data),noteHead=exact.journalNotes[0],historyHead=exact.planner.history.find(h=>h.entity.kind==='journal-note'&&h.entity.id===noteHead.id).after;
    noteHead.text='';historyHead.text='';if((cg.MAX_BACKUP_BYTES-cg.activeBytes(exact))%2)exact.workspaceId+='x';
    noteHead.text='b'.repeat((cg.MAX_BACKUP_BYTES-cg.activeBytes(exact))/2);historyHead.text=noteHead.text;cg.validateDataV5(exact);
    const start=performance.now(),prepared=cg.ok(await cg.host.previewRestore({token:await cg.token(),text:JSON.stringify(cg.backupV5(exact))}));
    const exactCommand={commandId:'restore-exact-boundary',type:'RestoreWorkspace',expected:await cg.token(),payload:{previewId:prepared.previewId,backup:await cg.backup(),discardDraftsConfirmed:true}};
    cg.ok(await cg.host.submit(exactCommand));const exactBytes=cg.activeBytes(await cg.data()),exactDurationMs=performance.now()-start;
    exact.workspaceId+='x';const tooBig=cg.ok(await cg.host.previewRestore({token:await cg.token(),text:JSON.stringify(cg.backupV5(exact))}));const beforeRejected=await cg.evidence();
    const rejected=await cg.host.submit({commandId:'restore-one-byte-over',type:'RestoreWorkspace',expected:await cg.token(),payload:{previewId:tooBig.previewId,backup:await cg.backup(),discardDraftsConfirmed:true}});
    const afterRejected=await cg.evidence();
    return {activeBytes:cg.activeBytes(above5.raw.data),accepted,oversize,unchanged:JSON.stringify(after)===JSON.stringify(above5),restoreVersion:restore.data.version,maxActive:cg.MAX_BACKUP_BYTES,maxInput:cg.MAX_INPUT_BYTES,exactBytes,exactDurationMs,oneByteOver:rejected,oneByteOverUnchanged:JSON.stringify(beforeRejected)===JSON.stringify(afterRejected)};
  });assert.ok(r.activeBytes>5*1024*1024);assert.equal(r.oversize.code,'DATA_TOO_LARGE');assert.equal(r.unchanged,true);assert.equal(r.restoreVersion,5);assert.equal(r.exactBytes,32*1024*1024);assert.equal(r.oneByteOver.code,'DATA_TOO_LARGE');assert.equal(r.oneByteOverUnchanged,true);return r;});
  await check('strict-v5-month-and-year-scale-through-formal-host',async ctx=>{const p=await pageIn(ctx);const r=await p.evaluate(async()=>{
    await cg.setup();const seed=await cg.data(),{scaleData}=await import('/tests/support/v06/b4-capacity.ts'),rows=[];
    for(const days of [31,365]){const data=scaleData(seed,days),t=performance.now();cg.validateDataV5(data);const validationMs=performance.now()-t,text=JSON.stringify(cg.backupV5(data)),start=performance.now();
      const preview=cg.ok(await cg.host.previewRestore({token:await cg.token(),text})),backup=await cg.backup();cg.ok(await cg.host.submit({commandId:`restore-${days}-days`,type:'RestoreWorkspace',expected:await cg.token(),payload:{previewId:preview.previewId,backup,discardDraftsConfirmed:true}}));
      const read=await cg.data();rows.push({days,bytes:cg.activeBytes(read),validationMs,restoreAndReadMs:performance.now()-start,notes:read.journalNotes.length,facts:read.planner.facts.length});
    }return rows;
  });for(const row of r){assert.ok(row.bytes<32*1024*1024);assert.equal(row.notes,row.days*4);assert.equal(row.facts,row.days*6);}return r;});
}finally{await browser?.close();await server.close();await fs.writeFile(path.join(output,'results.json'),JSON.stringify({at:new Date().toISOString(),origin,results},null,2));}
console.log(`B4 real IndexedDB: ${results.filter(r=>r.status==='pass').length}/${results.length}; ${output}`);if(results.some(r=>r.status!=='pass'))process.exitCode=1;
