// Author evidence: native OPFS streams + handle serialization + IDB + Web Locks.
// The fixture chooser and permission-failure seam are explicitly not OS-dialog tests.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
const root=fileURLToPath(new URL('../../',import.meta.url)),output=process.env.CARDGRID_B9_OUTPUT||path.join(root,'test-results/v06-b9/browser');await fs.mkdir(output,{recursive:true});
const {chromium}=await import(process.env.CARDGRID_PLAYWRIGHT_MODULE||'playwright');
const server=await createServer({root,configFile:false,logLevel:'error',server:{host:'127.0.0.1',port:0},optimizeDeps:{noDiscovery:true,entries:[],include:['react','react-dom/client','react/jsx-dev-runtime','@js-temporal/polyfill','jsbi']},plugins:[{name:'b9',configureServer(v){v.middlewares.use((req,res,next)=>{if(req.url==='/__v06b9'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div><script type="module" src="/tests/browser/v06-b9-harness.tsx"></script>');}else next();});}}]});
await server.listen();const origin=server.resolvedUrls.local[0].replace(/\/$/,''),results=[];let browser;
const files=p=>p.getByRole('region',{name:'文本文件',exact:true});
const nav=(p,label)=>p.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:label,exact:true});
const text=p=>p.evaluate(async()=>new TextDecoder().decode(new Uint8Array(await b9.bytes())));
const state=p=>p.evaluate(()=>b9.state());
async function flush(p){await p.evaluate(()=>b9.files.flush());}
async function open(p){await p.clock.setFixedTime(new Date('2026-10-06T00:12:00Z'));await p.goto(origin+'/__v06b9');await p.locator('.dial-svg').waitFor();await nav(p,'时间线日记').click();await files(p).waitFor();}
async function clickFile(p,label,method){await p.evaluate(method=>{const original=b9.files[method];b9.files[method]=(...args)=>{window.uiRequest=original(...args);b9.files[method]=original;return window.uiRequest;};},method);await files(p).getByRole('button',{name:label,exact:true}).click();await p.evaluate(()=>window.uiRequest);await flush(p);}
async function connect(p){await files(p).getByRole('button',{name:'连接文本目录',exact:true}).click();await p.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='连接文本目录'&&!b.disabled)&&!!document.querySelector('section[aria-label="文本文件"]')?.textContent?.includes('目录连接 '));await flush(p);}
async function run(name,fn,width=1280){const c=await browser.newContext({viewport:{width,height:900},timezoneId:'Asia/Shanghai',serviceWorkers:'block',reducedMotion:'reduce',acceptDownloads:true}),p=await c.newPage(),errors=[];p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));try{await open(p);const detail=await fn(p,c);assert.deepEqual(errors,[]);results.push({name,status:'pass',detail});console.log('PASS',name);await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});}catch(e){results.push({name,status:'fail',error:e.stack,pageErrors:errors,ui:await p.locator('body').innerText().catch(()=>'' )});console.error('FAIL',name,e);await p.screenshot({path:path.join(output,name+'-failure.png'),fullPage:true}).catch(()=>{});}finally{await c.close();}}
try{
  browser=await chromium.launch({headless:true,...(process.env.CARDGRID_CHROME_PATH?{executablePath:process.env.CARDGRID_CHROME_PATH}:{})});
  await run('native-streams-handle-idb-reload',async p=>{await connect(p);const before=await p.evaluate(()=>cg.evidence());const note=p.getByRole('textbox',{name:'独立感想',exact:true});await note.fill('写入真实浏览器文件流');await p.getByRole('button',{name:'立即保存',exact:true}).click();await p.getByText('随记保存：已保存到本机',{exact:true}).waitFor();await flush(p);assert.match(await text(p),/写入真实浏览器文件流/);assert.equal((await state(p)).connection.status,'synced');const backup=await p.evaluate(()=>cg.host.prepareBackup());assert.equal(backup.value.text.includes('text:binding'),false);assert.equal(backup.value.text.includes('lastSuccess'),false);const fingerprint=(await state(p)).outputs.find(r=>r.key.kind==='journal'&&r.key.zone==='Asia/Shanghai'&&r.key.date==='2026-10-06').lastSuccess.sha256;await p.reload();await p.locator('.dial-svg').waitFor();await flush(p);assert.match(await text(p),/写入真实浏览器文件流/);const after=await p.evaluate(()=>cg.evidence());assert.notDeepEqual(after.raw,before.raw);return {nativeHandleSurvivesReload:true,actualByteSha256:fingerprint,businessAndRecoverySeparate:true};});
  await run('external-original-bytes-preserve-restore',async p=>{await connect(p);const before=await p.evaluate(()=>cg.evidence());const bytes=[255,0,13,10,254,65];await p.evaluate(bytes=>b9.external(bytes),bytes);await clickFile(p,'主动刷新文件','refreshTextFiles');assert.deepEqual(await p.evaluate(()=>b9.conflict()),bytes);assert.deepEqual(await p.evaluate(()=>cg.evidence()),before);assert.equal((await state(p)).connection.status,'synced');return {originalBytesExact:true,workspaceUnchanged:true,conflictPath:(await state(p)).outputs.find(r=>r.externalCopyPath).externalCopyPath};});
  await run('conflict-copy-failure-holds-original-retry',async p=>{await connect(p);const external=[...new TextEncoder().encode('外部文本\r\n')];await p.evaluate(async bytes=>{await b9.external(bytes);b9.copyFailure(true);},external);await clickFile(p,'主动刷新文件','refreshTextFiles');assert.equal((await state(p)).connection.status,'conflict-copy-failed');assert.equal(await text(p),'外部文本\r\n');await p.evaluate(()=>b9.copyFailure(false));const row=await p.evaluate(()=>b9.row());await p.evaluate(key=>b9.files.retryTextOutput({key}),row.key);await flush(p);assert.deepEqual(await p.evaluate(()=>b9.conflict()),external);assert.notEqual(await text(p),'外部文本\r\n');return {nativeOriginalRetained:true,explicitCopyRetry:true};});
  await run('permission-seam-main-save-independent',async p=>{await connect(p);const old=await text(p);await p.evaluate(()=>b9.denied(true));await p.getByRole('textbox',{name:'独立感想',exact:true}).fill('目录权限失效时仍保存业务');await p.getByRole('button',{name:'立即保存',exact:true}).click();await p.getByText('随记保存：已保存到本机',{exact:true}).waitFor();await flush(p);assert.equal((await state(p)).connection.status,'permission-required');assert.equal(await text(p),old);assert.equal((await p.evaluate(()=>b9.counts())).requests,0);await clickFile(p,'重新授权并补写','reconnectTextDirectory');assert.match(await text(p),/目录权限失效时仍保存业务/);return {permissionFailureInjection:true,noAutomaticPrompt:true,businessSaved:true};});
  await run('real-idb-abort-after-native-close-reconcile',async p=>{await connect(p);await p.evaluate(()=>{window.undoMetadata=b9.metadataAbort();});await p.evaluate(()=>b9.note('文件已关闭，登记事务中止'));await flush(p);const row=await p.evaluate(()=>b9.row());assert.equal(row.status,'reconcile-required');assert.doesNotMatch(row.lastSuccess.text,/登记事务中止/);assert.match(await text(p),/登记事务中止/);await p.evaluate(()=>undoMetadata());await p.reload();await p.locator('.dial-svg').waitFor();await nav(p,'时间线日记').click();await files(p).waitFor();await files(p).getByRole('button',{name:'重新授权并补写',exact:true}).click();await flush(p);const r=await p.evaluate(()=>b9.row());assert.equal(r.status,'synced');assert.match(r.lastSuccess.text,/登记事务中止/);assert.equal(r.externalCopyPath,null);return {actualIdbAbort:true,nativeCloseCompleted:true,intentSurvivesReload:true};});
  await run('replace-pauses-old-namespace-explicit-resume',async p=>{await connect(p);const old=await p.evaluate(()=>b9.connection());const oldtext=await text(p);await p.evaluate(async()=>{const token=await cg.token(),b=await cg.backup(),source=JSON.stringify(cg.backupV5(await cg.data())),preview=cg.ok(await cg.host.previewRestore({token,text:source}));cg.ok(await cg.host.submit({commandId:crypto.randomUUID(),expected:token,type:'RestoreWorkspace',payload:{previewId:preview.previewId,backup:b,discardDraftsConfirmed:true}}));});await flush(p);assert.equal((await state(p)).connection.status,'paused-after-replace');assert.equal(await text(p),oldtext);await nav(p,'时间线日记').click();await clickFile(p,'确认继续为当前工作区写入','reconnectTextDirectory');const next=await p.evaluate(()=>b9.connection());assert.notEqual(next.epoch,old.epoch);assert.equal(next.connectionVersion,old.connectionVersion+1);return {oldFilesKept:true,newEpochNeedsExplicitResume:true};});
  await run('two-windows-web-lock-newest-wins',async(p,c)=>{await connect(p);const q=await c.newPage();await open(q);const release=p.evaluate(async()=>{window.lockGateRelease=null;await navigator.locks.request('CardGrid:text-output:'+ (await b9.connection()).bindingId,async()=>{window.lockHeld=true;await new Promise(r=>{window.lockGateRelease=r;});});});await p.waitForFunction(()=>window.lockHeld===true);await p.evaluate(()=>b9.note('锁占用期间的新业务'));const first=p.evaluate(()=>b9.files.flush()),second=q.evaluate(()=>b9.files.flush());await p.evaluate(()=>lockGateRelease());await Promise.all([release,first,second]);assert.match(await text(p),/锁占用期间的新业务/);assert.equal((await state(q)).connection.status,'synced');return {nativeWebLocksAcrossPages:true,newestSourceConverges:true};});

  await run('cross-date-move-retract-native-files',async p=>{await connect(p);await p.evaluate(async()=>{const s=await cg.synthesis();cg.ok(await cg.host.submit(s.command));const d=await cg.data(),c=d.handCards.find(c=>c.kind==='composite'),i=d.planner.instances.find(i=>i.id===c.actionInstanceId),v=cg.ok(await cg.host.previewPlacement({token:await cg.token(),date:'2026-10-06',zone:'Asia/Shanghai',focusMinuteOfDay:540,subject:{kind:'hand',instanceId:i.id,version:i.version}}));cg.ok(await cg.host.submit({commandId:crypto.randomUUID(),expected:v.token,type:'CommitPlacement',payload:{previewId:v.previewId,candidateId:v.candidates[0].id,acknowledgedOverlap:v.candidates[0].acknowledgementId??null}}));await b9.note('移时收回仍保留的感想');});await flush(p);assert.match(await text(p),/计划 ·/);const library=await p.evaluate(()=>cg.data().then(d=>d.actionCards));await p.evaluate(async()=>{const d=await cg.data(),plan=d.planner.plans[0],v=cg.ok(await cg.host.previewPlacement({token:await cg.token(),date:'2026-10-07',zone:'Asia/Shanghai',focusMinuteOfDay:0,subject:{kind:'plan',planId:plan.id,version:plan.version}}));cg.ok(await cg.host.submit({commandId:crypto.randomUUID(),expected:v.token,type:'CommitPlacement',payload:{previewId:v.previewId,candidateId:v.candidates[0].id,acknowledgedOverlap:v.candidates[0].acknowledgementId??null}}));});await flush(p);assert.doesNotMatch(await text(p),/计划 ·/);assert.match(await text(p),/移时收回仍保留的感想/);const moved=await p.evaluate(async()=>new TextDecoder().decode(new Uint8Array(await b9.bytes('journal','2026-10-07'))));assert.match(moved,/计划 ·/);await p.evaluate(async()=>{const d=await cg.data(),plan=d.planner.plans[0];cg.ok(await cg.host.submit({commandId:crypto.randomUUID(),expected:await cg.token(),type:'RetractPlan',payload:{planId:plan.id,version:plan.version}}));});await flush(p);const empty=await p.evaluate(async()=>new TextDecoder().decode(new Uint8Array(await b9.bytes('journal','2026-10-07'))));assert.match(empty,/当天无自动安排、参考或感想/);assert.deepEqual(await p.evaluate(()=>cg.data().then(d=>d.actionCards)),library);return {oldAndNewDaysRewritten:true,lastSegmentBecomesEmptyFile:true,notesAndLibraryRetained:true};});
  await run('business-commit-without-notification-reopen-repairs',async p=>{await connect(p);await p.evaluate(()=>b9.files.close());await p.evaluate(()=>b9.note('提交成功而文件队列未收到通知'));assert.doesNotMatch(await text(p),/未收到通知/);await p.reload();await p.locator('.dial-svg').waitFor();await flush(p);assert.match(await text(p),/未收到通知/);return {realBusinessCommit:true,closedQueueMissesNotification:true,startupSourceDiscoveryRepairs:true};});
  await run('manual-download-unsupported-320px',async p=>{await p.evaluate(()=>b9.unsupported());await nav(p,'备份与恢复').click();await files(p).getByText(/此浏览器不支持目录自动写入/).waitFor();assert.equal(await files(p).getByRole('button',{name:'连接文本目录'}).isEnabled(),false);const download=p.waitForEvent('download');await files(p).getByRole('button',{name:'下载本日日记文本',exact:true}).click();const d=await download;await d.saveAs(path.join(output,'manual-journal.md'));const content=await fs.readFile(path.join(output,'manual-journal.md'),'utf8');assert.ok(content.includes('2026-10-06'));assert.equal(content.includes('\r'),false);assert.equal(await p.evaluate(()=>b9.files.readActiveTextConnection().then(r=>r.value)),null);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);return {realDownload:true,unsupportedDoesNotClaimSynced:true,width:320};},320);
}finally{if(browser)await browser.close();await server.close();await fs.writeFile(path.join(output,'report.json'),JSON.stringify({evidence:'author; native OPFS and IDB; chooser and permission failure are explicit seams; external OS chooser remains pending',origin,results},null,2));}
if(results.some(r=>r.status==='fail'))process.exitCode=1;
