import test from 'node:test';
import assert from 'node:assert/strict';
import {b4Harness,ok,ref} from '../../support/v06/b4-fixtures.ts';
import {catalog,AT} from '../../support/v06/fixtures.ts';
import {projectUnifiedHand,materialDockItems,legacyDockItems,createV06HandSession} from '../../../src/daily/model.ts';
import type {DataV5} from '../../../src/workspace/v06.ts';
const load=async(h:Awaited<ReturnType<typeof b4Harness>>)=>ok(await h.host.loadV5()).data;
async function action(h:Awaited<ReturnType<typeof b4Harness>>){await h.submit('TakeActionMaterial',{action:ref(catalog.actionCards[0])});return (await load(h)).handCards.at(-1)!;}
async function restore(h:Awaited<ReturnType<typeof b4Harness>>){const backup=await h.backup(),p=ok(await h.host.previewRestore({token:await h.token(),text:ok(await h.host.prepareBackup()).text}));ok(await h.host.submit({type:'RestoreWorkspace',commandId:'b6-restore',expected:await h.token(),payload:{previewId:p.previewId,backup,discardDraftsConfirmed:true}}));}
test('B6 formal hand read is detached and has no writes, draws, history or receipts',async()=>{const h=await b4Harness();await action(h);const before=h.legacy.evidence(),items=ok(await h.host.readUnifiedHand({token:await h.token()})).data;assert.equal(items.length,1);assert.equal(items[0].unavailableReason,'INCOMPLETE');(items[0].card as {version:number}).version=55;assert.deepEqual(h.legacy.evidence(),before);assert.equal(h.randomCalls(),0);});
test('B6 duplicates retain independent exact IDs and versions in the float',async()=>{const h=await b4Harness();await action(h);await action(h);const items=materialDockItems(projectUnifiedHand(await load(h),AT));assert.equal(items.length,2);assert.equal(items[0].title,items[1].title);assert.notEqual(items[0].key,items[1].key);assert.notEqual(items[0].id,items[1].id);assert.deepEqual(items.map(i=>i.version),[1,1]);});
test('B6 answer and resource are separate kinds; resource cannot execute',async()=>{const h=await b4Harness();await h.answer();await h.submit('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[3])});const items=ok(await h.host.readUnifiedHand({token:await h.token()})).data;assert.equal(items[0].card.kind,'answer');assert.equal(items[0].usableInToday,true);assert.equal(items[1].card.kind,'entry');assert.equal(items[1].usableInToday,false);});
test('B6 composite replaces both inputs without removing originals or old journal',async()=>{const h=await b4Harness({acceptOld:true}),a=await h.answer(),b=await action(h),before=await load(h),p=ok(await h.host.previewSynthesis({token:await h.token(),inputs:[ref(a),ref(b)],resolutions:[]}));await h.submit('ConfirmSynthesis',{previewId:p.previewId});const data=await load(h),items=projectUnifiedHand(data,AT);assert.equal(items.some(i=>i.card.id===a.id||i.card.id===b.id),false);assert.equal(items.find(i=>i.card.id===p.output.id)?.usableInToday,true);assert.deepEqual(data.actionCards,before.actionCards);assert.deepEqual(data.journalEntries,before.journalEntries);});
test('B6 placed answer leaves hand and explicit retract returns the same ID',async()=>{const h=await b4Harness(),a=await h.answer(),p=ok(await h.host.previewReference({token:await h.token(),draft:{answer:ref(a),mode:'point',local:{date:'2026-10-06',time:'12:00',zone:'Asia/Shanghai'}}}));await h.submit('CommitReferencePlacement',{previewId:p.previewId});assert.equal(ok(await h.host.readUnifiedHand({token:await h.token()})).data.length,0);const r=(await load(h)).referencePlacements[0];await h.submit('RetractReference',{reference:ref(r)});assert.equal(ok(await h.host.readUnifiedHand({token:await h.token()})).data[0].card.id,a.id);});
test('B6 active plans, facts, withdrawn and consumed entities never duplicate the hand',async()=>{const h=await b4Harness(),a=await action(h),data=await load(h),id=a.kind==='action'?a.actionInstanceId:'';for(const reason of ['plan','fact','withdrawn','consumed'] as const){const draft=structuredClone(data);if(reason==='plan')draft.planner.plans=[{instanceId:id,status:'active'} as DataV5['planner']['plans'][number]];else if(reason==='fact')draft.planner.facts=[{instanceId:id} as DataV5['planner']['facts'][number]];else if(reason==='withdrawn')draft.planner.instances=draft.planner.instances.map(i=>({...i,state:'withdrawn'}));else draft.handCards=draft.handCards.map(c=>({...c,state:'consumed',consumedBy:'output'}));assert.equal(projectUnifiedHand(draft,AT).length,0,reason);}});
test('B6 exact expiry is blocked without changing data or creating a clock history',async()=>{const h=await b4Harness({acceptOld:true}),data=await load(h),expires=data.handCards[0].expiresAt!;const before=structuredClone(data);assert.equal(projectUnifiedHand(data,expires)[0].unavailableReason,'MATERIAL_EXPIRED');assert.deepEqual(data,before);});
test('B6 empty hand and unmapped legacy Instances are preserved as read models',async()=>{const h=await b4Harness();assert.deepEqual(projectUnifiedHand(await load(h),AT),[]);const old=await b4Harness({acceptOld:true});assert.equal(legacyDockItems(old.old).length,1);const s=createV06HandSession(old.host);ok(await s.start());assert.equal(s.getSnapshot().view?.items.length,1);assert.equal(s.getSnapshot().view?.items[0].selection.kind,'material');s.close();});
test('B6 preview provenance remains frozen after original catalog edits',async()=>{const h=await b4Harness(),a=await h.answer();const before=materialDockItems(ok(await h.host.readUnifiedHand({token:await h.token()})).data)[0];await h.submit('SaveCatalogEntry',{entry:{...catalog.catalogEntries[0],version:2,title:'后来改名'},expectedVersion:1});const after=materialDockItems(ok(await h.host.readUnifiedHand({token:await h.token()})).data)[0];assert.deepEqual(after,before);assert.equal(after.title,a.answer.entry.title);});
test('B6 session publishes immutable snapshots, no data ownership or Host close',async()=>{const h=await b4Harness(),s=createV06HandSession(h.host);await h.answer();ok(await s.start());const state=s.getSnapshot();assert.throws(()=>{(state.view!.items as unknown as unknown[]).push({});});s.close();assert.equal(s.getSnapshot().view,null);assert.equal((await h.host.loadV5()).ok,true);});
test('B6 non Today preparePlay rejects before reads and without writes',async()=>{const h=await b4Harness(),s=createV06HandSession(h.host),before=h.legacy.evidence();const result=await s.preparePlay({isToday:false,token:await h.token(),key:'forged',version:1});assert.equal(!result.ok&&result.code,'INVALID_INPUT');assert.deepEqual(h.legacy.evidence(),before);s.close();});
test('B6 Today intent uses exact ID and carries live token but never saves an arrangement',async()=>{const h=await b4Harness(),a=await h.answer(),s=createV06HandSession(h.host);ok(await s.start());const view=s.getSnapshot().view!,before=h.legacy.evidence(),r=ok(await s.preparePlay({isToday:true,token:view.token,key:`material:${a.id}`,version:a.version}));assert.equal(r.item.id,a.id);assert.deepEqual(r.token,view.token);assert.deepEqual(h.legacy.evidence(),before);s.close();});
test('B6 old revisions and replacement epochs cannot play cached cards',async()=>{const h=await b4Harness(),s=createV06HandSession(h.host);await h.answer();ok(await s.start());const view=s.getSnapshot().view!,input={isToday:true,token:view.token,key:view.items[0].key,version:1};await action(h);let r=await s.preparePlay(input);assert.equal(!r.ok&&r.code,'REVISION_CONFLICT');await restore(h);r=await s.preparePlay(input);assert.equal(!r.ok&&r.code,'WORKSPACE_REPLACED');s.close();});
test('B6 forged IDs, wrong versions and incomplete action cannot produce a play intent',async()=>{const h=await b4Harness(),a=await action(h),s=createV06HandSession(h.host);ok(await s.start());const token=s.getSnapshot().view!.token;for(const [key,version,code] of [[`material:${a.id}`,2,'ENTRY_STALE'],['material:absent',1,'ENTRY_STALE'],[`material:${a.id}`,1,'REQUIRED_FIELD_EMPTY']] as const){const r=await s.preparePlay({isToday:true,token,key,version});assert.equal(!r.ok&&r.code,code);}s.close();});
test('B6 late read after close cannot republish a prior workspace',async()=>{const h=await b4Harness();let release:()=>void=()=>{};const gate=new Promise<void>(r=>{release=r;});const s=createV06HandSession({...h.host,loadV5:async()=>{await gate;return h.host.loadV5();}});const pending=s.start();s.close();release();assert.equal((await pending).ok,false);assert.equal(s.getSnapshot().view,null);});
test('B6 a delayed older refresh cannot overwrite the newer snapshot',async()=>{const h=await b4Harness();let count=0,release:()=>void=()=>{};const gate=new Promise<void>(r=>{release=r;});const s=createV06HandSession({...h.host,loadV5:async()=>{const result=await h.host.loadV5();if(++count===1)await gate;return result;}});const first=s.refresh();await new Promise(r=>setTimeout(r,0));await h.answer();ok(await s.refresh());release();assert.equal((await first).ok,false);assert.equal(s.getSnapshot().view!.items.length,1);s.close();});
