import type {ConfigV2, ConfigV3} from '../../workspace/index.ts';
type ConfigPackage = ConfigV2 | ConfigV3;
import {validateDefinitionConfig} from '../../workspace/codec.ts';
type Props={readOnly:boolean;draft:ConfigPackage|null;editor:'form'|'json';json:string;busy:boolean;
 setDraft:(value:ConfigPackage)=>void;setEditor:(value:'form'|'json')=>void;setMessage:(value:string)=>void;setJson:(value:string)=>void;
 changeSettings:(value:ConfigV2['config']['settings'])=>void;saveSettings:()=>Promise<void>;previewFile:(value:string)=>Promise<void>;setTab:(value:'data')=>void;};
export function ConfigurationPanel({readOnly,draft,editor,json,busy,setDraft,setEditor,setMessage,setJson,changeSettings,saveSettings,previewFile,setTab}:Props){return <>{readOnly?<p>旧配置只读，请先导出并升级。</p>:draft&&<>
 <div className="segmented"><button aria-pressed={editor==='form'} onClick={()=>{try{const parsed=JSON.parse(json);validateDefinitionConfig(parsed);setDraft(parsed);setEditor('form');}catch(error){setMessage((error as Error).message);}}}>界面配置</button><button aria-pressed={editor==='json'} onClick={()=>setEditor('json')}>文字配置 JSON</button></div>
 {editor==='form'?<section className="panel"><h2>工作台偏好</h2><div className="formgrid"><label>主题<select value={draft.config.settings.preferences.theme} onChange={e=>changeSettings({...draft.config.settings,preferences:{...draft.config.settings.preferences,theme:e.target.value as 'paper'|'night'}})}><option value="paper">纸白与松绿</option><option value="night">夜间</option></select></label><label>显示密度<select value={draft.config.settings.preferences.density} onChange={e=>changeSettings({...draft.config.settings,preferences:{...draft.config.settings.preferences,density:e.target.value as 'comfortable'|'compact'}})}><option value="comfortable">舒适</option><option value="compact">紧凑</option></select></label><label>记录时区<input aria-label="记录时区" value={draft.config.settings.zone??''} placeholder="例如 Asia/Shanghai" onChange={e=>changeSettings({...draft.config.settings,zone:e.target.value||null})}/></label>{(['startHour','endHour','defaultMinutes'] as const).map((key,i)=><label key={key}>{['开始小时','结束小时','短任务指导分钟'][i]}<input type="number" value={draft.config.settings.preferences[key]} onChange={e=>changeSettings({...draft.config.settings,preferences:{...draft.config.settings.preferences,[key]:Number(e.target.value)}})}/></label>)}</div><button className="primary" disabled={busy} onClick={()=>void saveSettings()}>保存偏好</button><p>定义 {draft.config.definitions.length} · 模板 {draft.config.templates.length} · 例行 {draft.config.rules.length}</p><p className="muted">行动定义可在“行动定义”页面编辑；此处高级 JSON 使用同一套校验规则。</p></section>:<section className="panel"><h2>完整定义配置</h2><textarea className="json" aria-label="JSON配置" value={json} onChange={e=>setJson(e.target.value)}/><button className="primary" disabled={busy} onClick={()=>{void previewFile(json);setTab('data');}}>预览配置导入</button></section>}</>}
 </>;}
