import test from 'node:test';
import assert from 'node:assert/strict';
import {b4Harness,ok,ref} from '../../support/v06/b4-fixtures.ts';
import {catalog} from '../../support/v06/fixtures.ts';
import {createV06DecisionSession} from '../../../src/workspace/v06-decision-session.ts';
import {createV06ActionSession} from '../../../src/drawing/v06-action-session.ts';
import {createFormalCatalogEditor} from '../../../src/workshop/formal-catalog-editor.ts';

const decision=ref(catalog.decisionCards[0]);
async function setup(){const h=await b4Harness({acceptOld:true});for(const deck of [
  {id:'actions-one',name:'行动一',memberIds:['read','meal']},
  {id:'actions-two',name:'行动二',memberIds:['read','train']},
  {id:'actions-empty',name:'空行动',memberIds:[]},
])await h.submit('SaveDeck',{deck:{...deck,version:1,deckKind:'action',parentDeckId:null,source:{kind:'manual'}},expectedVersion:null});return h;}
const data=async(h:Awaited<ReturnType<typeof b4Harness>>)=>ok(await h.host.loadV5()).data;
async function draw(session:ReturnType<typeof createV06DecisionSession>,d=decision){const p=ok(await session.previewDecisionDraw({decision:d,choice:{kind:'random'}}));return {decision:d,entry:ref(p.selected.entry),alsoTakeAction:false};}
async function restore(h:Awaited<ReturnType<typeof b4Harness>>){const b=ok(await h.host.prepareBackup()),p=ok(await h.host.previewRestore({token:b.token,text:b.text}));return ok(await h.host.submit({type:'RestoreWorkspace',commandId:crypto.randomUUID(),expected:b.token,payload:{previewId:p.previewId,discardDraftsConfirmed:true,backup:{token:b.token,dataFingerprint:b.dataFingerprint,fileSavedConfirmed:true}}}));}

test('B5 reading candidates allocates no draw, card, history or receipt',async()=>{const h=await setup(),s=createV06DecisionSession(h.host),before=await data(h);assert.equal(ok(await s.listDecisionCandidates({decision})).candidates.length,1);assert.equal(ok(await s.readDecisionDraw!({decision})),null);assert.equal(h.randomCalls(),0);assert.deepEqual(await data(h),before);s.close();});
test('I1 changing questions while the previous read is in flight returns both exact candidate sets',async()=>{
  const h=await setup(),before=await data(h);let release!:()=>void,entered!:()=>void,first=true;
  const hold=new Promise<void>(r=>release=r),start=new Promise<void>(r=>entered=r);
  const s=createV06DecisionSession({...h.host,readDecisionCandidates:async input=>{if(first){first=false;entered();await hold;}return h.host.readDecisionCandidates(input);}});
  const books=s.listDecisionCandidates({decision});await start;
  const meals=s.listDecisionCandidates({decision:ref(catalog.decisionCards.find(d=>d.id==='which-food')!)});
  release();assert.deepEqual(ok(await books).candidates.map(c=>c.entry.id),['book-a']);assert.deepEqual(ok(await meals).candidates.map(c=>c.entry.id),['food-a']);
  assert.equal(h.randomCalls(),0);assert.deepEqual(await data(h),before);s.close();
});
test('I1 action scope observes a deck imported through the same Host after session start',async()=>{
  const h=await setup(),s=createV06ActionSession(h.host);ok(await s.start());
  await h.submit('SaveDeck',{deck:{id:'same-window-import',version:1,name:'新牌堆',deckKind:'action',memberIds:['train'],parentDeckId:null,source:{kind:'manual'}},expectedVersion:null});
  const until=Date.now()+2000;while(!s.getSnapshot().decks.some(d=>d.id==='same-window-import')&&Date.now()<until)await new Promise(r=>setTimeout(r,5));
  ok(s.setDeckIds(['same-window-import']));assert.deepEqual(s.getSnapshot().candidates.map(c=>c.id),['train']);s.close();
});
test('I1 formal editor replays an uncertain create before validating the committed entity head',async()=>{
  const h=await setup();let lost=true;const ids:string[]=[];
  const editor=createFormalCatalogEditor({...h.host,submit:async command=>{ids.push(command.commandId);const result=await h.host.submit(command);if(result.ok&&lost){lost=false;throw Error('lost reply after commit');}return result;}});
  const draft={...catalog.catalogEntries[0],id:'same-create',title:'只保存一次'},input={draft,expectedVersion:null};
  assert.equal((await editor.saveEntry(input)).ok,false);
  assert.equal((await editor.saveEntry({...input,draft:{...draft,id:'another-create'}})).ok,false);
  const result=ok(await editor.saveEntry(input));assert.equal(result.entry.id,draft.id);
  const current=await data(h);assert.equal(current.catalogEntries.filter(e=>e.id===draft.id).length,1);assert.equal(current.catalogEntries.some(e=>e.id==='another-create'),false);
  assert.equal(new Set(ids).size,1);assert.equal(current.commandReceipts.filter(r=>r.commandId===ids[0]).length,1);h.host.close();
});
test('B5 repeated read, navigation-style reopen and detached views keep one fixed selection',async()=>{const h=await setup(),s=createV06DecisionSession(h.host);const p=ok(await s.previewDecisionDraw({decision,choice:{kind:'random'}}));const before=await data(h);(p.selected.entry as {title:string}).title='伪改';await s.listDecisionCandidates({decision});assert.equal(ok(await s.readDecisionDraw!({decision}))?.selected.entry.title,'合成书目甲');assert.equal(h.randomCalls(),1);assert.deepEqual(await data(h),before);s.close();});
test('B5 redraw is an explicit new selection and cancel cannot accept the old answer',async()=>{const h=await setup(),s=createV06DecisionSession(h.host);await draw(s);const input=await draw(s);assert.equal(h.randomCalls(),2);ok(await s.cancelDecisionDraw!());assert.equal((await s.acceptDecisionAnswer(input)).ok,false);assert.equal((await data(h)).handCards.filter(c=>c.kind==='answer').length,0);s.close();});
test('B5 answer-only accept and repeated reply never add a hidden owner action',async()=>{const h=await setup(),s=createV06DecisionSession(h.host);const input=await draw(s),r=ok(await s.acceptDecisionAnswer(input));assert.equal(r.answer.kind,'answer');assert.equal(r.action,null);const before=await data(h);assert.deepEqual(ok(await s.acceptDecisionAnswer(input)),r);assert.deepEqual(await data(h),before);s.close();});
test('B5 explicitly taking the action is atomic and frozen snapshots survive original edits',async()=>{const h=await setup(),s=createV06DecisionSession(h.host),input={...await draw(s),alsoTakeAction:true};const r=ok(await s.acceptDecisionAnswer(input));assert.equal(r.action?.kind,'action');const old=await data(h),source=old.catalogEntries.find(e=>e.id===input.entry.id)!;await h.submit('SaveCatalogEntry',{entry:{...source,version:2,title:'后改'},expectedVersion:1});assert.equal((await data(h)).handCards.find(c=>c.id===r.answer.id)?.kind,'answer');assert.equal(r.answer.kind==='answer'&&r.answer.answer.entry.title,'合成书目甲');assert.equal(old.handCards.length+0,(await data(h)).handCards.length);s.close();});
for(const domain of ['which-book','which-food','which-exercise'])test(`B5 ${domain} uses the same formal session and field mapping`,async()=>{const h=await setup(),s=createV06DecisionSession(h.host),d=ref(catalog.decisionCards.find(d=>d.id===domain)!);const input=await draw(s,d),r=ok(await s.acceptDecisionAnswer(input));assert.equal(r.answer.kind,'answer');if(r.answer.kind==='answer')assert.deepEqual(r.answer.answer.fieldValues,[{fieldId:'subject',value:r.answer.answer.entry.title}]);s.close();});
test('B5 no-preview or forged entry cannot be accepted',async()=>{const h=await setup(),s=createV06DecisionSession(h.host);assert.equal((await s.acceptDecisionAnswer({decision,entry:{id:'book-a',version:1},alsoTakeAction:false})).ok,false);const input=await draw(s),r=await s.acceptDecisionAnswer({...input,entry:{id:'food-a',version:1}});assert.equal(!r.ok&&r.code,'INVALID_INPUT');s.close();});
test('B5 external revision invalidates a revealed answer without silently drawing a replacement',async()=>{const h=await setup(),s=createV06DecisionSession(h.host),input=await draw(s);await h.submit('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[3])});const r=await s.acceptDecisionAnswer(input);assert.equal(!r.ok&&r.code,'REVISION_CONFLICT');assert.equal(h.randomCalls(),1);assert.equal((await data(h)).handCards.filter(c=>c.kind==='answer').length,0);s.close();});
test('B5 storage failure retains the same command and blocks mode change, redraw and cancel',async()=>{const h=await setup();let fail=true;const ids:string[]=[];const s=createV06DecisionSession({...h.host,submit:async command=>{ids.push(command.commandId);if(fail)return {ok:false,code:'STORAGE_FAILED',message:'injected',retry:'same-command'};return h.host.submit(command);}});const input=await draw(s);assert.equal((await s.acceptDecisionAnswer(input)).ok,false);assert.equal((await s.cancelDecisionDraw!()).ok,false);assert.equal((await s.previewDecisionDraw({decision,choice:{kind:'random'}})).ok,false);assert.equal((await s.acceptDecisionAnswer({...input,alsoTakeAction:true})).ok,false);fail=false;ok(await s.acceptDecisionAnswer(input));assert.equal(ids.length,2);assert.equal(ids[0],ids[1]);assert.equal((await data(h)).handCards.filter(c=>c.kind==='answer').length,1);s.close();});
test('B5 lost reply after commit is replayed without an extra answer or action',async()=>{const h=await setup();let lose=true;const ids:string[]=[];const s=createV06DecisionSession({...h.host,submit:async command=>{ids.push(command.commandId);const r=await h.host.submit(command);if(r.ok&&lose){lose=false;throw Error('lost reply');}return r;}});const input={...await draw(s),alsoTakeAction:true};assert.equal((await s.acceptDecisionAnswer(input)).ok,false);ok(await s.acceptDecisionAnswer(input));assert.equal(new Set(ids).size,1);const current=await data(h);assert.equal(current.handCards.filter(c=>c.kind==='answer').length,1);assert.equal(current.commandReceipts.filter(r=>r.commandId===ids[0]).length,1);s.close();});
test('B5 double accept is serialized and a replacement epoch invalidates cached success',async()=>{const h=await setup(),s=createV06DecisionSession(h.host),input=await draw(s);const r=await Promise.all([s.acceptDecisionAnswer(input),s.acceptDecisionAnswer(input)]);assert.equal(r.filter(r=>r.ok).length,1);await restore(h);const after=await s.acceptDecisionAnswer(input);assert.equal(!after.ok&&after.code,'WORKSPACE_REPLACED');s.close();});
test('B5 empty or paused decisions return an explicit failure with no material',async()=>{const h=await setup(),s=createV06DecisionSession(h.host);const d=catalog.decisionCards[0];await h.submit('SaveDecisionCard',{decision:{...d,version:2,deckIds:['empty-list']},expectedVersion:1});const r=await s.previewDecisionDraw({decision:{id:d.id,version:2},choice:{kind:'random'}});assert.equal(!r.ok&&r.code,'ENTRY_UNAVAILABLE');assert.equal((await data(h)).handCards.filter(c=>c.kind==='answer').length,0);s.close();});
test('B5 closing an in-flight preview drops the late result without accepting anything',async()=>{const h=await setup();let release:()=>void=()=>{};const gate=new Promise<void>(r=>{release=r;});let entered:()=>void=()=>{};const started=new Promise<void>(r=>{entered=r;});const s=createV06DecisionSession({...h.host,selectDecisionEntry:async input=>{entered();await gate;return h.host.selectDecisionEntry(input);}});const p=s.previewDecisionDraw({decision,choice:{kind:'random'}});await started;s.close();release();assert.equal((await p).ok,false);assert.equal((await data(h)).handCards.filter(c=>c.kind==='answer').length,0);});
test('B5 action scope requires explicit action decks, deduplicates shared members and excludes resource decks',async()=>{const h=await setup(),s=createV06ActionSession(h.host);ok(await s.start());assert.equal(s.getSnapshot().candidates.length,0);assert.equal((await s.openSphere()).ok,false);ok(s.setDeckIds(['actions-one','actions-two']));assert.deepEqual(s.getSnapshot().candidates.map(c=>c.id),['read','meal','train']);assert.equal(s.setDeckIds(['books']).ok,false);assert.deepEqual(s.getSnapshot().deckIds,['actions-one','actions-two']);s.close();});
test('B5 empty and paused action candidates are explained and never auto-select another deck',async()=>{const h=await setup(),s=createV06ActionSession(h.host);const a=catalog.actionCards[0];await h.submit('SaveActionCardV5',{actionCard:{...a,version:2,status:'paused'},expectedVersion:1});ok(await s.start());ok(s.setDeckIds(['actions-one']));assert.deepEqual(s.getSnapshot().candidates.map(a=>a.id),['meal']);ok(s.setDeckIds(['actions-empty']));assert.equal((await s.openSphere()).ok,false);assert.deepEqual(s.getSnapshot().deckIds,['actions-empty']);s.close();});
test('B5 action two-tap locking retains the exact presented ID and cannot accept a back',async()=>{const h=await setup(),s=createV06ActionSession(h.host);ok(await s.start());ok(s.setDeckIds(['actions-one']));ok(await s.openSphere());s.present('meal');s.present('read');assert.equal(s.getSnapshot().selected?.id,'meal');assert.equal((await s.accept()).ok,false);s.reveal('read');assert.equal(s.getSnapshot().phase,'presented');s.reveal('meal');const result=ok(await s.accept());assert.equal(result.card.kind==='action'&&result.card.ownerAction.id,'meal');const before=await data(h);ok(await s.accept());assert.deepEqual(await data(h),before);s.close();});
test('B5 action refresh and detached immutable view keep a presented card until explicit scope change',async()=>{const h=await setup(),s=createV06ActionSession(h.host);ok(await s.start());ok(s.setDeckIds(['actions-one']));s.present('read');const view=s.getSnapshot();assert.throws(()=>{(view.candidates as unknown as {id:string}[]).push({id:'forged'});});ok(await s.refresh());assert.equal(s.getSnapshot().selected?.id,'read');ok(s.setDeckIds(['actions-two']));assert.equal(s.getSnapshot().phase,'idle');assert.equal((await s.accept()).ok,false);s.close();});
test('B5 action accepting after another write refuses the old scope snapshot',async()=>{const h=await setup(),s=createV06ActionSession(h.host);ok(await s.start());ok(s.setDeckIds(['actions-one']));s.present('read');s.reveal();await h.submit('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[3])});const r=await s.accept();assert.equal(!r.ok&&r.code,'REVISION_CONFLICT');assert.equal((await data(h)).handCards.filter(c=>c.kind==='action').length,0);s.close();});
test('B5 action lost reply and storage failure use the original named command',async()=>{const h=await setup();let mode='fail';const ids:string[]=[];const s=createV06ActionSession({...h.host,submit:async command=>{ids.push(command.commandId);if(mode==='fail')return {ok:false,code:'STORAGE_FAILED',message:'injected',retry:'same-command'};const r=await h.host.submit(command);if(mode==='lose'){mode='normal';throw Error('lost');}return r;}});ok(await s.start());ok(s.setDeckIds(['actions-one']));s.present('meal');s.reveal();assert.equal((await s.accept()).ok,false);assert.equal(s.cancel(),false);assert.equal(s.setDeckIds(['actions-two']).ok,false);mode='lose';assert.equal((await s.retry()).ok,false);ok(await s.retry());assert.equal(new Set(ids).size,1);assert.equal((await data(h)).handCards.filter(c=>c.kind==='action').length,1);s.close();});
test('B5 action explicit repeated taking creates different materials and preserves daily records',async()=>{const h=await setup(),s=createV06ActionSession(h.host);const before=await data(h);ok(await s.start());ok(s.setDeckIds(['actions-one']));s.present('read');s.reveal();const first=ok(await s.accept());ok(await s.openSphere());s.present('read');s.reveal();const second=ok(await s.accept());assert.notEqual(first.card.id,second.card.id);const after=await data(h);assert.deepEqual(after.dailyCopies,before.dailyCopies);assert.deepEqual(after.archiveLogs,before.archiveLogs);assert.deepEqual(after.generationLedger,before.generationLedger);assert.deepEqual(after.journalEntries,before.journalEntries);s.close();});
test('B5 manual answers use a deduplicated deck union and preserve the exact source',async()=>{const h=await setup(),s=createV06DecisionSession(h.host),second={...catalog.catalogEntries[0],id:'book-b',title:'合成书目乙'};await h.submit('SaveCatalogEntry',{entry:second,expectedVersion:null});await h.submit('SaveDeck',{deck:{...catalog.decks[0],id:'books-extra',memberIds:['book-a','book-b']},expectedVersion:null});await h.submit('SaveDecisionCard',{decision:{...catalog.decisionCards[0],version:2,deckIds:['books','books-extra']},expectedVersion:1});const d={id:decision.id,version:2};assert.equal(ok(await s.listDecisionCandidates({decision:d})).candidates.length,2);const p=ok(await s.previewDecisionDraw({decision:d,choice:{kind:'manual',entry:ref(second)}}));assert.equal(h.randomCalls(),0);assert.deepEqual(p.selected.sourceDecks,[{id:'books-extra',version:1}]);const r=ok(await s.acceptDecisionAnswer({decision:d,entry:ref(second),alsoTakeAction:false}));assert.equal(r.answer.kind==='answer'&&r.answer.answer.entry.id,'book-b');s.close();});
test('B5 paused decisions reject draws and accepted cancellation never retracts saved cards',async()=>{const h=await setup(),s=createV06DecisionSession(h.host);ok(await s.acceptDecisionAnswer(await draw(s)));const before=await data(h);ok(await s.cancelDecisionDraw!());assert.deepEqual(await data(h),before);await h.submit('SaveDecisionCard',{decision:{...catalog.decisionCards[0],version:2,status:'paused'},expectedVersion:1});const r=await s.previewDecisionDraw({decision:{id:decision.id,version:2},choice:{kind:'random'}});assert.equal(!r.ok&&r.code,'ENTRY_UNAVAILABLE');s.close();});
test('B5 cached action success cannot cross a restore epoch',async()=>{const h=await setup(),s=createV06ActionSession(h.host);ok(await s.start());ok(s.setDeckIds(['actions-one']));s.present('read');s.reveal();ok(await s.accept());await restore(h);const r=await s.accept();assert.equal(!r.ok&&r.code,'WORKSPACE_REPLACED');s.close();});
test('B5 navigation during an uncertain decision save preserves the fixed draft and original retry',async()=>{const h=await setup();let lose=true;const s=createV06DecisionSession({...h.host,submit:async command=>{const r=await h.host.submit(command);if(r.ok&&lose){lose=false;throw Error('lost');}return r;}});const input=await draw(s);assert.equal((await s.acceptDecisionAnswer(input)).ok,false);ok(await s.listDecisionCandidates({decision}));assert.equal(ok(await s.readDecisionDraw!({decision}))?.selected.entry.id,input.entry.id);ok(await s.acceptDecisionAnswer(input));assert.equal((await data(h)).handCards.filter(c=>c.kind==='answer').length,1);s.close();});
