import test from 'node:test';
import assert from 'node:assert/strict';
import {b4Harness,ok} from '../../support/v06/b4-fixtures.ts';
import {createV06Host} from '../../../src/workspace/v06-host.ts';
import {decodeArchiveZip,encodeArchiveZip,archiveCapacity} from '../../../src/workspace/archive-zip.ts';
import {backupV5,validateDataV5} from '../../../src/workspace/v5-format.ts';
import {catalog} from '../../support/v06/fixtures.ts';
async function fixture(options:Parameters<typeof b4Harness>[0]={}){const base=await b4Harness(options),store=base.legacy.store,packages=new Map<string,unknown>();let saved:Blob|null=null,sequence=0,at='2026-10-06T02:00:00Z',picks=0;
  store.readMonthlyArchive=async key=>packages.get(key);store.listMonthlyArchiveIndex=async()=>[...packages].filter(([key])=>key.startsWith('index:')).map(([,value])=>value);
  store.atomicMonthlyArchive=async(keys,reduce)=>{let staged:readonly {key:string;value:unknown}[]=[];const result=await store.atomic(raw=>{const change=reduce(keys.map(key=>packages.get(key)),raw);staged=change.archiveWrites??[];return change;});for(const w of staged)packages.set(w.key,w.value);return result;};
  const host=createV06Host({store,now:()=>at,id:()=>`b11-${++sequence}`,archiveRuntime:{async pickSavedArchive(){picks++;if(!saved)throw Error('no external file');return saved;}}}),token=async()=>ok(await host.loadV5()).token;
  const submit=async(type:any,payload:any,commandId=`b11-c-${++sequence}`)=>ok(await host.submit({...(['ConfirmActual','AppendAnnotation','GenerateDailyCopies','ArchiveDueCopies','SaveTemplate','PrepareDay','CancelFixed'].includes(type)?{}:{contractVersion:'v06-p0-1'}),commandId,expected:await token(),type,payload} as any));
  const note=async(date:string,text:string)=>submit('SaveJournalNote',{id:null,expectedVersion:null,date,zone:'Asia/Shanghai',text});
  const preview=async(month='2026-09')=>ok(await host.archivePort.previewMonthlyArchive({token:await token(),month,zone:'Asia/Shanghai'}));
  async function prepared(month='2026-09'){const p=await preview(month),artifact=ok(await host.archivePort.exportMonthlyArchive({token:p.token,previewId:p.previewId}));saved=new File([await artifact.zip.arrayBuffer()],artifact.filename,{type:'application/zip'});const v=ok(await host.archivePort.verifySavedArchive({token:p.token,exportId:artifact.exportId})),clear=ok(await host.archivePort.previewArchiveClear({token:p.token,previewId:p.previewId,verificationId:v.verificationId}));return {p,artifact,v,clear,command:{contractVersion:'v06-p0-1',commandId:`clear-${++sequence}`,expected:p.token,type:'CommitMonthlyArchive',payload:{previewId:p.previewId,verificationId:v.verificationId,clearPreviewId:clear.clearPreviewId,removalConfirmed:true}} as const};}
  return {base,host,store,packages,token,submit,note,preview,prepared,setNow(v:string){at=v;},setExternal(v:Blob){saved=v;},picks:()=>picks};
}
test('B11 external reread is required; failed transaction retains current data, recovery and package slots',async()=>{const h=await fixture();await h.note('2026-09-12','独立旧感想\r\n全文');const before=h.base.legacy.evidence(),p=await h.preview();assert.equal((await h.host.submit({contractVersion:'v06-p0-1',commandId:'fake',expected:p.token,type:'CommitMonthlyArchive',payload:{previewId:p.previewId,verificationId:'verified:true',clearPreviewId:'fake',removalConfirmed:true}})).ok,false);assert.deepEqual(h.base.legacy.evidence(),before);const ready=await h.prepared();assert.equal(h.picks(),1);h.base.legacy.failNext();assert.equal((await h.host.submit(ready.command)).ok,false);assert.deepEqual(h.base.legacy.evidence(),before);assert.equal(h.packages.size,0);ok(await h.host.submit(ready.command));const data=ok(await h.host.loadV5()).data;validateDataV5(data);assert.equal(data.journalNotes.length,0);assert.equal(data.archiveIndex.length,1);assert.deepEqual(data.journalEntries,(before.raw as any).data.journalEntries);const replay=ok(await h.host.submit(ready.command));assert.equal(replay.replayed,true);assert.equal(ok(await h.host.archivePort.readRecoveryCoverage()).complete,true);const view=ok(await h.host.archivePort.readArchive({archiveId:ready.v.archiveId}));assert.equal(view.access,'archive');assert.equal(view.editable,false);assert.equal('token' in view,false);assert.equal(view.journal[0].notes[0].text,'独立旧感想\r\n全文');h.host.close();});
test('B11 required hashes survive active JSON restore; missing ZIP diagnoses incomplete history without blocking live reads',async()=>{const h=await fixture();await h.note('2026-09-01','旧月');const r=await h.prepared();ok(await h.host.submit(r.command));const current=ok(await h.host.loadV5()),pack=backupV5(current.data);assert.equal(pack.requiredArchives.length,1);h.packages.clear();h.host.invalidateCapabilities();assert.equal(ok(await h.host.archivePort.readRecoveryCoverage()).complete,false);assert.equal((await h.host.loadV5()).ok,true);assert.equal((await h.host.textFilePort.prepareTextDownload({kind:'journal',date:'2026-09-01',zone:'Asia/Shanghai'})).ok,false);ok(await h.host.archivePort.importArchive({zip:r.artifact.zip,filename:r.artifact.filename}));assert.equal(ok(await h.host.archivePort.readRecoveryCoverage()).complete,true);const text=ok(await h.host.textFilePort.prepareTextDownload({kind:'journal',date:'2026-09-01',zone:'Asia/Shanghai'}));assert.match(text.text,/旧月/);const denied=await h.host.submit({contractVersion:'v06-p0-1',commandId:'edit-archive',expected:await h.token(),type:'SaveJournalNote',payload:{id:null,expectedVersion:null,date:'2026-09-01',zone:'Asia/Shanghai',text:'试图修改'}});assert.equal(denied.ok,false);if(!denied.ok)assert.equal(denied.code,'ARCHIVE_READ_ONLY');h.host.close();});
test('B11 multiple packs deduplicate and lazy cache releases the previous month; foreign same-month packs do not merge into Data',async()=>{const h=await fixture();await h.note('2026-08-01','八月');await h.note('2026-09-01','九月');const a=await h.prepared('2026-08');ok(await h.host.submit(a.command));const b=await h.prepared('2026-09');ok(await h.host.submit(b.command));assert.equal(ok(await h.host.archivePort.importArchive({zip:a.artifact.zip,filename:'a.zip'})).disposition,'duplicate');ok(await h.host.archivePort.readArchive({archiveId:a.v.archiveId}));ok(await h.host.archivePort.readArchive({archiveId:b.v.archiveId}));assert.deepEqual(ok(await h.host.archivePort.readArchiveCacheState()).loadedArchiveIds,[b.v.archiveId]);ok(await h.host.archivePort.releaseArchive({archiveId:b.v.archiveId}));assert.equal(ok(await h.host.archivePort.readArchiveCacheState()).decodedBytes,0);assert.equal(h.packages.size,4);h.host.close();});
test('B11 stale revision and workspace replacement cannot clear data with old capability',async()=>{const h=await fixture();await h.note('2026-09-01','旧月');const r=await h.prepared();await h.note('2026-10-06','当前');const before=h.base.legacy.evidence();assert.equal((await h.host.submit(r.command)).ok,false);assert.deepEqual(h.base.legacy.evidence(),before);const current=(before.raw as any);h.store.__setRaw({...current,epoch:'replacement'});const fail=await h.host.submit(r.command);assert.equal(fail.ok,false);if(!fail.ok)assert.equal(fail.code,'WORKSPACE_REPLACED');h.host.close();});
test('B11 ZIP rejects corruption, unsafe names and expanded budget before registering bytes',async()=>{const h=await fixture();await h.note('2026-09-01','旧月');const r=await h.prepared(),raw=new Uint8Array(await r.artifact.zip.arrayBuffer());raw[30]^=1;assert.equal((await h.host.archivePort.importArchive({zip:new Blob([raw]),filename:'bad.zip'})).ok,false);assert.equal(h.packages.size,0);await assert.rejects(()=>decodeArchiveZip(r.artifact.zip,{...archiveCapacity,maxArchiveExpandedBytes:10}),{code:'ARCHIVE_BUDGET_EXCEEDED'});const files=await decodeArchiveZip(r.artifact.zip),manifest=JSON.parse(new TextDecoder().decode(files['manifest.json']));manifest.createdAt='2026-10-06T03:00:00Z';const conflict=await encodeArchiveZip({...files,'manifest.json':new TextEncoder().encode(JSON.stringify(manifest))});ok(await h.host.archivePort.importArchive({zip:r.artifact.zip,filename:'good.zip'}));const fail=await h.host.archivePort.importArchive({zip:conflict,filename:'conflict.zip'});assert.equal(fail.ok,false);if(!fail.ok)assert.equal(fail.code,'ARCHIVE_CONFLICT');h.host.close();});
async function simpleFact(h:Awaited<ReturnType<typeof fixture>>,start={date:'2026-10-06',time:'09:00'},end={date:'2026-10-06',time:'09:25'}){const action={...catalog.actionCards[0],id:'sealed-action',content:{...catalog.actionCards[0].content,title:'封存行动'},fields:[]};await h.submit('SaveActionCardV5',{actionCard:action,expectedVersion:null});await h.submit('TakeActionMaterial',{action:{id:action.id,version:1}});const d=ok(await h.host.loadV5()).data,instance=d.planner.instances.at(-1)!;const p=ok(await h.host.previewActual({token:await h.token(),draft:{mode:'unplanned',instanceId:instance.id,instanceVersion:instance.version,start:{...start,zone:'Asia/Shanghai'},end:{...end,zone:'Asia/Shanghai'}}}));await h.submit('ConfirmActual',{previewId:p.previewId,acknowledgedOverlap:p.acknowledgementId});return ok(await h.host.loadV5()).data.planner.facts.at(-1)!;}
test('B11 archive read model includes independent references without an active token',async()=>{const h=await fixture(),answer=await h.base.answer();const reference=ok(await h.host.previewReference({token:await h.token(),draft:{answer:{id:answer.id,version:answer.version},mode:'point',local:{date:'2026-10-06',time:'08:15',zone:'Asia/Shanghai'}}}));await h.submit('CommitReferencePlacement',{previewId:reference.previewId});await h.note('2026-10-06','独立参考仍保留在活动区');h.setNow('2026-11-01T02:00:00Z');const r=await h.prepared('2026-10');assert.ok(r.p.retained.some(ref=>ref.ref.collection==='referencePlacements'));ok(await h.host.submit(r.command));const value=ok(await h.host.readArchivedJournalProjection({archiveId:r.v.archiveId,date:'2026-10-06',zone:'Asia/Shanghai'}));assert.equal(value.editable,false);assert.equal('token' in value,false);assert.equal('token' in value.projection,false);assert.deepEqual(value.projection.rows.find(row=>row.kind==='reference')!.answer,answer.answer);h.host.close();});
test('B11 sealed manual fact, annotation, material and history move together; original library and old source versions remain',async()=>{const h=await fixture(),fact=await simpleFact(h);await h.submit('AppendAnnotation',{factId:fact.id,text:'实际批注'});const before=ok(await h.host.loadV5()).data;h.setNow('2026-11-01T02:00:00Z');const r=await h.prepared('2026-10');assert.ok(r.p.selected.some(ref=>ref.collection==='facts'&&ref.id===fact.id));ok(await h.host.submit(r.command));const after=ok(await h.host.loadV5()).data;assert.equal(after.planner.facts.length,0);assert.equal(after.planner.annotations.length,0);assert.equal(after.handCards.length,0);assert.deepEqual(after.actionCards,before.actionCards);const view=ok(await h.host.archivePort.readArchive({archiveId:r.v.archiveId}));assert.deepEqual(view.facts,before.planner.facts);assert.deepEqual(view.annotations,before.planner.annotations);assert.equal(view.journal.find(j=>j.date==='2026-10-06')!.automatic[0].title,'封存行动');validateDataV5(after);h.host.close();});
test('B11 cross-month fact remains one record; open action stays live with an explained retention reason',async()=>{const h=await fixture();h.setNow('2026-11-01T02:00:00Z');const fact=await simpleFact(h,{date:'2026-10-31',time:'23:55'},{date:'2026-11-01',time:'00:20'});await h.note('2026-10-01','可归档的十月感想');let p=await h.preview('2026-10');assert.equal(p.selected.some(r=>r.collection==='facts'&&r.id===fact.id),false);assert.ok(p.retained.some(r=>r.ref.collection==='facts'));h.setNow('2026-12-01T02:00:00Z');const r=await h.prepared('2026-11');assert.ok(r.p.manifest.coveredDates.includes('2026-10-31'));assert.ok(r.p.manifest.coveredDates.includes('2026-11-01'));ok(await h.host.submit(r.command));const view=ok(await h.host.archivePort.readArchive({archiveId:r.v.archiveId}));assert.equal(view.facts.length,1);assert.equal(view.journal.filter(j=>j.automatic.some(a=>a.sourceKind==='fact')).length,2);h.host.close();});
test('B11 generic expired unused daily stock archives without deleting the generation ledger',async()=>{const h=await fixture();await h.submit('GenerateDailyCopies',{target:'current'});h.setNow('2026-10-14T02:00:00Z');await h.submit('ArchiveDueCopies',{});const before=ok(await h.host.loadV5()).data;h.setNow('2026-11-01T02:00:00Z');const r=await h.prepared('2026-10');ok(await h.host.submit(r.command));const after=ok(await h.host.loadV5()).data;assert.equal(after.archiveLogs.length,0);assert.deepEqual(after.generationLedger,before.generationLedger);assert.equal(ok(await h.host.archivePort.readArchive({archiveId:r.v.archiveId})).editable,false);h.host.close();});

test('I1 cross-month archive blocks retained legacy edits, new plans and point references at the write boundary',async()=>{
  const h=await fixture({journalDate:'2026-10-31'});h.setNow('2026-11-02T02:00:00Z');
  await simpleFact(h,{date:'2026-10-31',time:'23:55'},{date:'2026-11-01',time:'00:20'});
  h.setNow('2026-12-01T02:00:00Z');const archive=await h.prepared('2026-11');ok(await h.host.submit(archive.command));
  const body=ok(await h.host.loadV5()).data.journalEntries[0];assert.equal(body.date,'2026-10-31');
  const before=h.base.legacy.evidence(),original=ok(await h.host.textFilePort.prepareTextDownload({kind:'journal',date:body.date,zone:body.zone})).text;
  const blocked=async(type:string,payload:unknown)=>{const evidence=h.base.legacy.evidence(),r=await h.host.submit({...(['CommitPlacement','ConfirmActual'].includes(type)?{}:{contractVersion:'v06-p0-1'}),commandId:crypto.randomUUID(),expected:await h.token(),type,payload} as any);assert.equal(r.ok,false);if(!r.ok)assert.equal(r.code,'ARCHIVE_READ_ONLY');assert.deepEqual(h.base.legacy.evidence(),evidence);};
  await blocked('SaveLegacyJournalBlock',{entry:{id:body.id,version:body.version},text:'不得改写归档日正文'});
  assert.deepEqual(h.base.legacy.evidence(),before);
  await h.submit('TakeActionMaterial',{action:{id:'sealed-action',version:1}});
  const instance=ok(await h.host.loadV5()).data.planner.instances.at(-1)!;
  const placement=ok(await h.host.previewPlacement({token:await h.token(),date:'2026-10-31',zone:'Asia/Shanghai',focusMinuteOfDay:540,subject:{kind:'hand',instanceId:instance.id,version:instance.version}}));
  await blocked('CommitPlacement',{previewId:placement.previewId,candidateId:placement.candidates[0].id,acknowledgedOverlap:placement.candidates[0].acknowledgementId??null});
  // A range in another zone can still overlap the archived day in its frozen zone.
  const actual=ok(await h.host.previewActual({token:await h.token(),draft:{mode:'unplanned',instanceId:instance.id,instanceVersion:instance.version,start:{date:'2026-10-30',time:'16:30',zone:'America/Los_Angeles'},end:{date:'2026-10-30',time:'16:55',zone:'America/Los_Angeles'}}}));
  await blocked('ConfirmActual',{previewId:actual.previewId,acknowledgedOverlap:actual.acknowledgementId});
  const answer=await h.base.answer();
  const reference=ok(await h.host.previewReference({token:await h.token(),draft:{answer:{id:answer.id,version:answer.version},mode:'point',local:{date:'2026-10-31',time:'08:15',zone:'Asia/Shanghai'}}}));
  await blocked('CommitReferencePlacement',{previewId:reference.previewId});
  assert.equal(ok(await h.host.textFilePort.prepareTextDownload({kind:'journal',date:body.date,zone:body.zone})).text,original);
  await h.note('2026-12-01','当前活动日仍可写');h.host.close();
});

test('I1 retained open plan can move to an active day and retract after archiving unrelated notes',async()=>{
  const h=await fixture(),source={...catalog.actionCards[0],id:'still-active',fields:[],content:{...catalog.actionCards[0].content,title:'未完成行动'}};
  await h.submit('SaveActionCardV5',{actionCard:source,expectedVersion:null});await h.submit('TakeActionMaterial',{action:{id:source.id,version:1}});
  const instance=ok(await h.host.loadV5()).data.planner.instances.at(-1)!;
  const place=ok(await h.host.previewPlacement({token:await h.token(),date:'2026-10-06',zone:'Asia/Shanghai',focusMinuteOfDay:540,subject:{kind:'hand',instanceId:instance.id,version:instance.version}}));
  ok(await h.host.submit({commandId:'place-retained-open',expected:place.token,type:'CommitPlacement',payload:{previewId:place.previewId,candidateId:place.candidates[0].id,acknowledgedOverlap:null}}));
  await h.note('2026-10-06','独立感想可封存');h.setNow('2026-11-01T02:00:00Z');const archive=await h.prepared('2026-10');assert.ok(archive.p.retained.some(r=>r.ref.collection==='plans'));ok(await h.host.submit(archive.command));
  const plan=ok(await h.host.loadV5()).data.planner.plans.find(p=>p.instanceId===instance.id)!;
  const move=ok(await h.host.previewPlacement({token:await h.token(),date:'2026-11-01',zone:'Asia/Shanghai',focusMinuteOfDay:540,subject:{kind:'plan',planId:plan.id,version:plan.version}}));
  ok(await h.host.submit({commandId:'move-retained-open',expected:move.token,type:'CommitPlacement',payload:{previewId:move.previewId,candidateId:move.candidates[0].id,acknowledgedOverlap:null}}));
  const moved=ok(await h.host.loadV5()).data.planner.plans.find(p=>p.id===plan.id)!;assert.equal(moved.range.localStart,'2026-11-01T09:00');
  ok(await h.host.submit({commandId:'retract-retained-open',expected:await h.token(),type:'RetractPlan',payload:{planId:moved.id,version:moved.version}}));
  assert.equal(ok(await h.host.loadV5()).data.planner.plans.find(p=>p.id===plan.id)!.status,'retracted');h.host.close();
});
test('B11 saved day overrides survive independently; cancelled sleep cannot be recreated by archive projection',async()=>{const h=await fixture();await h.submit('SaveTemplate',{template:{id:'archive-sleep',version:1,name:'睡眠',weekdays:[0,1,2,3,4,5,6],entries:[{id:'night',title:'睡眠',start:'22:00',elapsedMinutes:480,definitionId:null}],source:{kind:'manual'}},expectedVersion:null});await h.submit('PrepareDay',{date:'2026-10-06',zone:'Asia/Shanghai',templateId:'archive-sleep'});const fixed=ok(await h.host.loadV5()).data.planner.fixed[0];const unlock=ok(await h.host.unlockFixed({token:await h.token(),commitmentId:fixed.id,version:fixed.version}));await h.submit('CancelFixed',{commitment:{id:fixed.id,version:fixed.version},unlockId:unlock});await h.note('2026-10-06','睡眠已取消，保留感想');const original=ok(await h.host.readJournalProjection({date:'2026-10-06',zone:'Asia/Shanghai',token:await h.token()}));assert.equal(original.timeline.automatic.length,0);h.setNow('2026-11-01T02:00:00Z');const r=await h.prepared('2026-10');ok(await h.host.submit(r.command));const view=ok(await h.host.archivePort.readArchive({archiveId:r.v.archiveId}));assert.equal(view.journal.find(j=>j.date==='2026-10-06')!.automatic.length,0);const text=ok(await h.host.textFilePort.prepareTextDownload({kind:'journal',date:'2026-10-06',zone:'Asia/Shanghai'}));assert.doesNotMatch(text.text,/固定安排 · "睡眠"/);assert.match(text.text,/睡眠已取消/);h.host.close();});

test('B11 active backup restores exactly with missing archives diagnosed, then matching ZIP restores historical availability',async()=>{const h=await fixture();await h.note('2026-09-01','只读历史');const r=await h.prepared();ok(await h.host.submit(r.command));const target=ok(await h.host.loadV5()).data,pack=backupV5(target);await h.note('2026-10-06','恢复前活动感想');h.packages.clear();const preview=ok(await h.host.previewRestore({token:await h.token(),text:JSON.stringify(pack)}));assert.equal(preview.coverage!.complete,false);assert.equal(preview.coverage!.missing[0].archiveId,r.v.archiveId);const backup=ok(await h.host.prepareBackup());ok(await h.host.submit({commandId:'restore-active-with-required-pack',expected:preview.token,type:'RestoreWorkspace',payload:{previewId:preview.previewId,backup:{token:backup.token,dataFingerprint:backup.dataFingerprint,fileSavedConfirmed:true},discardDraftsConfirmed:true}}));assert.deepEqual(ok(await h.host.loadV5()).data,target);assert.equal((await h.host.textFilePort.prepareTextDownload({kind:'journal',date:'2026-09-01',zone:'Asia/Shanghai'})).ok,false);ok(await h.host.archivePort.importArchive({zip:r.artifact.zip,filename:r.artifact.filename}));assert.equal(ok(await h.host.archivePort.readRecoveryCoverage()).complete,true);assert.match(ok(await h.host.textFilePort.prepareTextDownload({kind:'journal',date:'2026-09-01',zone:'Asia/Shanghai'})).text,/只读历史/);h.host.close();});

test('I1 archived virtual sleep and complete text retain the frozen template and workspace zone',async()=>{
  const h=await fixture(),data=ok(await h.host.loadV5()).data;
  ok(await h.host.submit({commandId:'archive-zone',expected:await h.token(),type:'SaveSettings',payload:{settings:{...data.settings,zone:'Asia/Shanghai'}}}));
  const template={id:'frozen-virtual-sleep',version:1,name:'旧睡眠',weekdays:[0,1,2,3,4,5,6],entries:[{id:'night',title:'原睡眠',start:'00:00',elapsedMinutes:360,definitionId:null}],source:{kind:'manual' as const}};
  await h.submit('SaveTemplate',{template,expectedVersion:null});await h.note('2026-09-01','冻结日记');
  const request={kind:'journal' as const,date:'2026-09-01',zone:'Asia/Shanghai'},before=ok(await h.host.textFilePort.prepareTextDownload(request)).text,archive=await h.prepared('2026-09');ok(await h.host.submit(archive.command));
  await h.submit('SaveTemplate',{template:{...template,version:2,entries:[{...template.entries[0],title:'新睡眠',start:'01:00',elapsedMinutes:300}]},expectedVersion:1});
  assert.equal(ok(await h.host.textFilePort.prepareTextDownload(request)).text,before);
  const latest=ok(await h.host.loadV5()).data;ok(await h.host.submit({commandId:'change-current-zone',expected:await h.token(),type:'SaveSettings',payload:{settings:{...latest.settings,zone:'UTC'}}}));
  assert.equal(ok(await h.host.textFilePort.prepareTextDownload(request)).text,before);
  const readonly=ok(await h.host.readArchivedJournalProjection({archiveId:archive.v.archiveId,date:request.date,zone:request.zone}));assert.equal(readonly.projection.timeline.automatic[0].title,'原睡眠（未保存模板）');h.host.close();
});

test('I1 a display day spanning two archive contexts uses each source day frozen sleep',async()=>{
  const h=await fixture(),data=ok(await h.host.loadV5()).data;
  ok(await h.host.submit({commandId:'multi-context-zone',expected:await h.token(),type:'SaveSettings',payload:{settings:{...data.settings,zone:'Asia/Shanghai'}}}));
  const template={id:'per-day-context-sleep',version:1,name:'睡眠',weekdays:[0,1,2,3,4,5,6],entries:[{id:'night',title:'九月睡眠',start:'00:00',elapsedMinutes:360,definitionId:null}],source:{kind:'manual' as const}};
  await h.submit('SaveTemplate',{template,expectedVersion:null});
  await h.note('2026-09-30','九月随记');await h.note('2026-10-01','十月随记');
  const september=await h.prepared('2026-09');ok(await h.host.submit(september.command));
  await h.submit('SaveTemplate',{template:{...template,version:2,entries:[{...template.entries[0],title:'十月睡眠',start:'01:00',elapsedMinutes:300}]},expectedVersion:1});
  h.setNow('2026-11-01T02:00:00Z');const october=await h.prepared('2026-10');ok(await h.host.submit(october.command));
  const isolated=ok(await h.host.readArchivedJournalProjection({archiveId:october.v.archiveId,date:'2026-09-30',zone:'UTC'}));
  const expected=isolated.projection.timeline.automatic.find(row=>row.range.localStart==='2026-10-01T01:00')!;assert.ok(expected);
  const combined=ok(await h.host.readJournalProjection({token:await h.token(),date:'2026-09-30',zone:'UTC'}));
  assert.equal(combined.timeline.automatic.length,1);assert.equal(combined.timeline.automatic[0].sourceKey,expected.sourceKey);assert.deepEqual(combined.timeline.automatic[0].range,expected.range);
  const text=ok(await h.host.textFilePort.prepareTextDownload({kind:'journal',date:'2026-09-30',zone:'UTC'}));assert.match(text.text,/十月睡眠/);assert.doesNotMatch(text.text,/九月睡眠/);h.host.close();
});

test('I1 missing historical ZIP is an explicit file failure, not a transient revision race',async()=>{
  const h=await fixture();await h.note('2026-09-01','历史不能被残缺投影覆盖');const archive=await h.prepared('2026-09');ok(await h.host.submit(archive.command));
  const request={kind:'journal' as const,date:'2026-09-01',zone:'Asia/Shanghai'},complete=ok(await h.host.textFilePort.prepareTextDownload(request));
  h.packages.clear();h.host.invalidateCapabilities();
  const missing=await h.host.textFilePort.prepareTextDownload(request);assert.equal(missing.ok,false);if(!missing.ok){assert.equal(missing.code,'IO_FAILED');assert.match(missing.message,/缺失/);}
  ok(await h.host.archivePort.importArchive({zip:archive.artifact.zip,filename:archive.artifact.filename}));assert.equal(ok(await h.host.textFilePort.prepareTextDownload(request)).text,complete.text);h.host.close();
});

test('B11 fact attachment freezes the answer and moves the entire completed dependency group',async()=>{const h=await fixture(),first=await h.base.answer(true),initial=ok(await h.host.loadV5()).data,material=initial.handCards.find(c=>c.kind==='action')!,synthesis=ok(await h.host.previewSynthesis({token:await h.token(),inputs:[{id:material.id,version:material.version},{id:first.id,version:first.version}],resolutions:[]}));await h.submit('ConfirmSynthesis',{previewId:synthesis.previewId});const d=ok(await h.host.loadV5()).data,instance=d.planner.instances.at(-1)!,placement=ok(await h.host.previewPlacement({token:await h.token(),date:'2026-10-06',zone:'Asia/Shanghai',focusMinuteOfDay:540,subject:{kind:'hand',instanceId:instance.id,version:instance.version}}));ok(await h.host.submit({commandId:'place-attached-archive',expected:placement.token,type:'CommitPlacement',payload:{previewId:placement.previewId,candidateId:placement.candidates[0].id,acknowledgedOverlap:null}}));const plan=ok(await h.host.loadV5()).data.planner.plans[0];await h.base.answer();const answer=ok(await h.host.loadV5()).data.handCards.findLast(c=>c.kind==='answer'&&c.state==='available')!;const reference=ok(await h.host.previewReference({token:await h.token(),draft:{answer:{id:answer.id,version:answer.version},mode:'attached',instance:{id:instance.id,version:instance.version}}}));await h.submit('CommitReferencePlacement',{previewId:reference.previewId});const actual=ok(await h.host.previewActual({token:await h.token(),draft:{mode:'planned',instanceId:instance.id,instanceVersion:instance.version,planId:plan.id,planVersion:plan.version,start:{date:'2026-10-06',time:'09:00',zone:'Asia/Shanghai'},end:{date:'2026-10-06',time:'09:25',zone:'Asia/Shanghai'}}}));await h.submit('ConfirmActual',{previewId:actual.previewId,acknowledgedOverlap:null});const before=ok(await h.host.loadV5()).data;await h.submit('SaveCatalogEntry',{entry:{...before.catalogEntries[0],version:before.catalogEntries[0].version+1,title:'后续更新的原库'},expectedVersion:before.catalogEntries[0].version});h.setNow('2026-11-01T02:00:00Z');const r=await h.prepared('2026-10');ok(await h.host.submit(r.command));const after=ok(await h.host.loadV5()).data;assert.equal(after.factReferenceSnapshots.length,0);assert.equal(after.referencePlacements.length,0);assert.equal(after.handCards.length,0);assert.equal(after.catalogEntries[0].title,'后续更新的原库');const view=ok(await h.host.archivePort.readArchive({archiveId:r.v.archiveId}));assert.deepEqual(view.journal.find(j=>j.date==='2026-10-06')!.automatic[0].referenceAnswers,[answer.answer]);validateDataV5(after);h.host.close();});
