import test from 'node:test';
import assert from 'node:assert/strict';
import {b4Harness,ok} from '../../support/v06/b4-fixtures.ts';
import {configurationExample} from '../../../src/workspace/v5-config-example.ts';
import {parseConfigV4,validateDataV5} from '../../../src/workspace/v5-format.ts';
async function imported(h:any,config:any,mode='merge'){const p=ok(await h.host.previewCatalogImport({token:await h.token(),text:JSON.stringify(config)}));const proof=ok(await h.host.confirmBackupEvidence(await h.backup()));return h.submit('ImportCatalogV4',{previewId:p.previewId,mode,backupEvidenceId:proof.evidenceId});}
test('B10 three equal domains and independent list import/export includes the existing sleep dial template',async()=>{const h=await b4Harness(),before=await h.liveData(),sample=configurationExample();parseConfigV4(JSON.stringify(sample));await imported(h,sample);const data=await h.liveData();validateDataV5(data);assert.ok(data.actionCards.some((a:any)=>a.id==='sample-eat'));assert.ok(data.actionCards.some((a:any)=>a.id==='sample-exercise'));assert.ok(data.decks.some((d:any)=>d.id==='independent-list'));assert.equal(data.planner.templates.find((t:any)=>t.id==='sleep').entries[0].elapsedMinutes,480);for(const key of ['instances','facts','plans','fixed'])assert.deepEqual(data.planner[key],before.planner[key]);assert.deepEqual(data.journalEntries,before.journalEntries);parseConfigV4(JSON.stringify(ok(await h.host.exportConfiguration())));h.host.close();});
test('B10 duplicate packs are idempotent in entity versions; same ID updates preserve frozen material',async()=>{const h=await b4Harness();await imported(h,configurationExample());const before=await h.liveData();await imported(h,configurationExample());const repeat=await h.liveData();assert.deepEqual(repeat.actionCards,before.actionCards);assert.deepEqual(repeat.planner.templates,before.planner.templates);const pack=ok(await h.host.exportConfiguration());pack.config.catalogEntries.find((e:any)=>e.id==='sample-eat-entry').title='新午餐';await imported(h,pack);const after=await h.liveData();assert.equal(after.catalogEntries.find((e:any)=>e.id==='sample-eat-entry').version,2);assert.deepEqual(after.journalEntries,before.journalEntries);h.host.close();});
test('B10 generic daily rules work without requiring a legacy action-card head',async()=>{const h=await b4Harness(),pack=configurationExample();(pack.config as any).generationRules=[{id:'eat-daily',version:1,name:'每日吃饭',actionCardId:'sample-eat',schedule:{mode:'daily'},startDate:'2026-10-01',zone:'Asia/Shanghai',status:'active',source:{kind:'manual'}}];await imported(h,pack);validateDataV5(await h.liveData());const r=await h.host.submit({commandId:'generate-eat',expected:await h.token(),type:'GenerateDailyCopies',payload:{target:'current'}});ok(r);assert.ok((await h.liveData()).dailyCopies.some((c:any)=>c.ruleId==='eat-daily'));h.host.close();});
test('B10 reference errors and oversized decks reject without writes; aborted import preserves exact backup',async()=>{const h=await b4Harness(),before=h.legacy.evidence(),pack=configurationExample();(pack.config.decisionCards[0] as any).ownerActionId='missing';const r=await h.host.previewCatalogImport({token:await h.token(),text:JSON.stringify(pack)});assert.equal(r.ok,false);assert.deepEqual(h.legacy.evidence(),before);const p=ok(await h.host.previewCatalogImport({token:await h.token(),text:JSON.stringify(configurationExample())})),proof=ok(await h.host.confirmBackupEvidence(await h.backup()));h.legacy.failNext();const c=await h.command('ImportCatalogV4',{previewId:p.previewId,mode:'replace',backupEvidenceId:proof.evidenceId});assert.equal((await h.host.submit(c)).ok,false);assert.deepEqual(h.legacy.evidence(),before);ok(await h.host.submit(c));h.host.close();});
test('B10 old ConfigV3 maps slots into explicit fields and decisions before confirmation; old full backup stays exact',async()=>{const h=await b4Harness(),old=h.old,pack={format:'cardgrid',version:3,kind:'config',config:{settings:old.settings,definitions:old.planner.definitions,templates:old.planner.templates,rules:old.planner.rules,actionCards:old.actionCards,bookEntries:old.bookEntries,pools:old.pools,generationRules:old.generationRules}},before=h.legacy.evidence(),p=ok(await h.host.previewCatalogImport({token:await h.token(),text:JSON.stringify(pack)}));assert.deepEqual(h.legacy.evidence(),before);assert.equal(p.legacyMapping!.sourceVersion,3);assert.equal(p.legacyMapping!.decisions[0].question,'书名');assert.equal(p.legacyMapping!.fields[0].fields[0].id,'book');await imported(h,pack);assert.deepEqual((await h.liveData()).journalEntries,old.journalEntries);const backup=await h.backup(),restore=ok(await h.host.previewRestore({token:await h.token(),text:JSON.stringify({format:'cardgrid',version:4,kind:'backup',dataFormat:'action-v4',data:old})}));ok(await h.host.submit({commandId:'restore-old-v4',expected:restore.token,type:'RestoreWorkspace',payload:{previewId:restore.previewId,backup,discardDraftsConfirmed:true}}));assert.deepEqual(ok(await h.host.load()).data,old);assert.equal((await h.host.loadV5()).ok,false);h.host.close();});
test('B10 genuinely oversized incoming deck is rejected before issuing a capability',async()=>{const h=await b4Harness(),pack=configurationExample(),before=h.legacy.evidence();(pack.config as any).catalogEntries=Array.from({length:101},(_,i)=>({...pack.config.catalogEntries[0],id:'over-'+i}));(pack.config as any).decks=[{...pack.config.decks[0],memberIds:pack.config.catalogEntries.map(e=>e.id)}];(pack.config as any).decisionCards=[];assert.equal((await h.host.previewCatalogImport({token:await h.token(),text:JSON.stringify(pack)})).ok,false);assert.deepEqual(h.legacy.evidence(),before);h.host.close();});
