import test from 'node:test';
import assert from 'node:assert/strict';
import {b4Harness,ok,ref} from '../../support/v06/b4-fixtures.ts';
import {catalog,AT} from '../../support/v06/fixtures.ts';
import {validateDataV5,backupV5,parseV06Restore,parseConfigV4,activeBytes,MAX_BACKUP_BYTES,MAX_INPUT_BYTES} from '../../../src/workspace/v5-format.ts';
import {prepareV5Migration,legacyDecisionId} from '../../../src/workspace/v5-migration.ts';
import {createV06Host} from '../../../src/workspace/v06-host.ts';
import {emptyWorkspaceData,parseRestore} from '../../../src/workspace/format.ts';
const fail=(r:any,code:string)=>{assert.equal(r.ok,false,JSON.stringify(r));assert.equal(r.code,code,JSON.stringify(r));};
const point=(answer:any)=>({answer:ref(answer),mode:'point' as const,local:{date:'2026-10-06',time:'09:00',zone:'Asia/Shanghai'}});
async function synth(h:any){const answer=await h.answer();await h.submit('TakeActionMaterial',{action:ref(catalog.actionCards[0])});const action=(await h.liveData()).handCards.find((c:any)=>c.kind==='action'&&c.ownerAction.id==='read');const preview=ok(await h.host.previewSynthesis({token:await h.token(),inputs:[ref(action),ref(answer)],resolutions:[]}));return {answer,action,preview,command:await h.command('ConfirmSynthesis',{previewId:preview.previewId})};}

test('B4 explicit v4 migration preserves old planner, original library history, full CRLF journal and receipts',async()=>{
  const h=await b4Harness({catalog:false,acceptOld:true}),data=await h.liveData();validateDataV5(data);
  for(const key of ['instances','plans','facts','annotations','handOrder','templates','fixed','days'])assert.deepEqual(data.planner[key],h.old.planner[key]);
  assert.deepEqual(data.journalEntries,h.old.journalEntries);assert.deepEqual(data.planner.history.slice(0,h.old.planner.history.length),h.old.planner.history);
  assert.deepEqual(data.commandReceipts,h.old.commandReceipts);assert.deepEqual(data.dailyCopies,h.old.dailyCopies);assert.deepEqual(data.generationLedger,h.old.generationLedger);
  assert.equal(data.catalogEntries[0].attributes.author,null);assert.equal(data.decisionCards[0].mappings[0].fieldId,'book');assert.equal(data.handCards.length,1);assert.equal(data.handCards[0].actionInstanceId,h.old.planner.instances[0].id);
  assert.deepEqual(h.legacy.evidence().recovery[0].value.raw.data,h.old);
});
test('B4 legacy decision IDs and slot aliases distinguish punctuation without collisions',()=>{assert.notEqual(legacyDecisionId('a:b','c'),legacyDecisionId('a','b:c'));assert.notEqual(legacyDecisionId('a%','b'),legacyDecisionId('a','%b'));assert.doesNotThrow(()=>legacyDecisionId('\ud800','x'));assert.notEqual(legacyDecisionId('\ud800','x'),legacyDecisionId('\ufffd','x'));});
test('B4 plain v5 read, backup and preview produce no writes',async()=>{const h=await b4Harness(),before=h.legacy.evidence();await h.snapshot();await h.host.prepareBackup();await h.host.previewDecision({token:await h.token(),decision:ref(catalog.decisionCards[0]),deckIds:['books']});assert.deepEqual(h.legacy.evidence(),before);});
test('B4 migration never happens while loading old JSON and requires the session backup evidence',async()=>{
  const h=await b4Harness({catalog:false});h.legacy.store.__setRaw({schemaVersion:4,epoch:'old',revision:0,lifecycleReceipt:null,mode:'current',dataFormat:'action-v4',data:h.old});
  const before=h.legacy.evidence(),preview=ok(await h.host.previewMigrationV5({token:await h.token()}));assert.equal((await h.snapshot()).data.version,4);assert.deepEqual(h.legacy.evidence(),before);
  fail(await h.host.submit({commandId:'no-backup',type:'CommitMigration',expected:await h.token(),payload:{previewId:preview.previewId,backup:{token:await h.token(),dataFingerprint:'forged',fileSavedConfirmed:true},discardDraftsConfirmed:true}}),'BACKUP_REQUIRED');assert.deepEqual(h.legacy.evidence(),before);
});
test('B4 old full backup restores exact v4 data and a new epoch without automatic re-upgrade',async()=>{
  const h=await b4Harness(),oldText=JSON.stringify({format:'cardgrid',version:4,kind:'backup',dataFormat:'action-v4',data:h.old}),beforeToken=await h.token();
  const preview=ok(await h.host.previewRestore({token:beforeToken,text:oldText}));ok(await h.host.submit({type:'RestoreWorkspace',commandId:'restore-old',expected:beforeToken,payload:{previewId:preview.previewId,backup:await h.backup(),discardDraftsConfirmed:true}}));
  const restored=await h.snapshot();assert.notEqual(restored.token.epoch,beforeToken.epoch);assert.deepEqual(restored.data,h.old);assert.equal(restored.data.version,4);assert.deepEqual(parseRestore(oldText).data,h.old);fail(await h.host.submit(await h.command('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[0])})),'UNSUPPORTED_VERSION');
});
test('B4 v5 backup round trip retains every record and lifecycle restores the data exactly',async()=>{
  const h=await b4Harness();await h.answer(true);await h.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'新感想'});
  const before=await h.liveData(),text=JSON.stringify(backupV5(before));assert.deepEqual(parseV06Restore(text).data,before);
  const preview=ok(await h.host.previewRestore({token:await h.token(),text}));ok(await h.host.submit({commandId:'restore-v5',type:'RestoreWorkspace',expected:await h.token(),payload:{previewId:preview.previewId,backup:await h.backup(),discardDraftsConfirmed:true}}));assert.deepEqual(await h.liveData(),before);
});
for(const [name,change] of [
  ['unknown root',(d:any)=>d.extra=true],['forged nested material',(d:any)=>d.handCards[0].unexpected='x'],['consumed without output',(d:any)=>{d.handCards[0].state='consumed';d.handCards[0].consumedBy='absent';}],['missing frozen source',(d:any)=>d.handCards[0].ownerAction.version=999],
  ['broken catalog head',(d:any)=>d.catalogEntries[0].title='tampered'],['missing reflection time',(d:any)=>delete d.journalNotes[0].recordedAt],['unknown reference shape',(d:any)=>d.referencePlacements[0].extra=1],
] as const)test(`B4 strict package rejects ${name}`,async()=>{const h=await b4Harness();await h.submit('TakeActionMaterial',{action:ref(catalog.actionCards[0])});const a=await h.answer();const p=ok(await h.host.previewReference({token:await h.token(),draft:point(a)}));await h.submit('CommitReferencePlacement',{previewId:p.previewId});await h.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'note'});const data=await h.liveData();change(data);assert.throws(()=>validateDataV5(data));});
test('B4 coverage claims cannot omit required archive hashes',async()=>{const h=await b4Harness(),pack=backupV5(await h.liveData()) as any;pack.requiredArchives=[{archiveId:'fake'}];assert.throws(()=>parseV06Restore(JSON.stringify(pack)));});
test('B4 repeated taking creates distinct current materials and instances while retaining the original catalog',async()=>{const h=await b4Harness(),before=await h.liveData();await h.submit('TakeActionMaterial',{action:ref(catalog.actionCards[0])});await h.submit('TakeActionMaterial',{action:ref(catalog.actionCards[0])});await h.submit('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[0])});const after=await h.liveData();assert.equal(after.handCards.length,3);assert.equal(after.planner.instances.length-before.planner.instances.length,2);assert.deepEqual(after.actionCards,before.actionCards);assert.deepEqual(after.catalogEntries,before.catalogEntries);});
test('B4 default answer selection creates no executable action; explicit alsoTakeAction creates both atomically',async()=>{const h=await b4Harness();await h.answer();assert.equal((await h.liveData()).planner.instances.length,0);assert.equal((await h.liveData()).handCards.length,1);const p=ok(await h.host.previewDecision({token:await h.token(),decision:ref(catalog.decisionCards[1]),deckIds:['foods']}));const s=ok(await h.host.selectDecisionEntry({token:await h.token(),previewId:p.previewId,choice:{mode:'random'}}));await h.submit('AcceptDecisionAnswer',{selectionId:s.selectionId,alsoTakeAction:true});assert.equal((await h.liveData()).handCards.length,3);assert.equal((await h.liveData()).planner.instances.length,1);});
test('B4 random selection is session-stable, read and retries never reroll',async()=>{const h=await b4Harness(),p=ok(await h.host.previewDecision({token:await h.token(),decision:ref(catalog.decisionCards[0]),deckIds:['books']}));const a=ok(await h.host.selectDecisionEntry({token:await h.token(),previewId:p.previewId,choice:{mode:'random'}})),b=ok(await h.host.selectDecisionEntry({token:await h.token(),previewId:p.previewId,choice:{mode:'random'}}));assert.deepEqual(a,b);assert.equal(h.randomCalls(),1);});
test('B4 synthesis atomically consumes both materials, retires input instance, adds output/history/receipt, retains library',async()=>{
  const h=await b4Harness(),s=await synth(h),before=await h.liveData();ok(await h.host.submit(s.command));const after=await h.liveData();
  assert.equal(after.handCards.find((c:any)=>c.id===s.answer.id).state,'consumed');assert.equal(after.handCards.find((c:any)=>c.id===s.action.id).state,'consumed');
  const output=after.handCards.find((c:any)=>c.kind==='composite');assert.deepEqual(output.inputIds,[s.action.id,s.answer.id]);assert.equal(after.planner.instances.find((i:any)=>i.id===s.action.actionInstanceId).state,'withdrawn');
  assert.equal(after.planner.instances.length,before.planner.instances.length+1);assert.equal(after.commandReceipts.length,before.commandReceipts.length+1);assert.equal(after.planner.history.length,before.planner.history.length+5);assert.deepEqual(after.actionCards,before.actionCards);
  const replay=ok(await h.host.submit(s.command));assert.equal(replay.replayed,true);assert.deepEqual(await h.liveData(),after);
});
test('B4 transaction failure leaves all materials, output, history, receipts and recovery unchanged, then same command succeeds',async()=>{const h=await b4Harness(),s=await synth(h),before=h.legacy.evidence();h.legacy.failNext();fail(await h.host.submit(s.command),'STORAGE_FAILED');assert.deepEqual(h.legacy.evidence(),before);ok(await h.host.submit(s.command));assert.equal(ok(await h.host.submit(s.command)).replayed,true);});
test('B4 lost reply replays persisted receipt without consuming again',async()=>{const h=await b4Harness(),s=await synth(h);h.legacy.loseNextReply();fail(await h.host.submit(s.command),'STORAGE_FAILED');const before=h.legacy.evidence();assert.equal(ok(await h.host.submit(s.command)).replayed,true);assert.deepEqual(h.legacy.evidence(),before);});
test('B4 command ID reuse with another payload is rejected even after revision changes',async()=>{const h=await b4Harness(),cmd=await h.command('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[0])});ok(await h.host.submit(cmd));fail(await h.host.submit({...cmd,payload:{entry:ref(catalog.catalogEntries[1])}} as any),'COMMAND_ID_REUSED');});
test('B4 stale token cannot change catalog and two clients compete on the same revision',async()=>{const h=await b4Harness(),second=createV06Host({store:h.legacy.store,now:()=>AT,id:()=> 'second'}),expected=await h.token();const a=await h.command('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[0])}),b={...a,commandId:'second-cmd'};const results=await Promise.all([h.host.submit(a),second.submit(b)]);assert.equal(results.filter(r=>r.ok).length,1);fail(results.find(r=>!r.ok),'REVISION_CONFLICT');assert.equal((await h.token()).revision,expected.revision+1);});
test('B4 stored inputs use their original frozen action version after library editing',async()=>{const h=await b4Harness(),s=await synth(h);await h.submit('SaveActionCardV5',{actionCard:{...catalog.actionCards[0],version:2,content:{...catalog.actionCards[0].content,title:'编辑后的原卡 {对象}'}},expectedVersion:1});fail(await h.host.submit(s.command),'REVISION_CONFLICT');const p=ok(await h.host.previewSynthesis({token:await h.token(),inputs:[ref(s.action),ref(s.answer)],resolutions:[]}));assert.equal(p.output.ownerAction.version,1);assert.match(p.output.contentSnapshot.title,/阅读/);});
test('B4 fake preview IDs and cancelled capabilities cannot create a receipt or card',async()=>{const h=await b4Harness(),before=h.legacy.evidence();fail(await h.host.submit(await h.command('ConfirmSynthesis',{previewId:'forged'})),'PREVIEW_STALE');assert.deepEqual(h.legacy.evidence(),before);const s=await synth(h);ok(await h.host.cancelPreview({token:await h.token(),previewId:s.preview.previewId}));fail(await h.host.submit(s.command),'PREVIEW_STALE');});
test('B4 reference point occupies zero minutes; retract keeps reflection and frozen answer',async()=>{const h=await b4Harness(),a=await h.answer(),p=ok(await h.host.previewReference({token:await h.token(),draft:point(a)}));assert.equal(p.occupiedMinutes,0);await h.submit('CommitReferencePlacement',{previewId:p.previewId});await h.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'参考感想'});const before=await h.liveData();await h.submit('RetractReference',{reference:ref(before.referencePlacements[0])});const after=await h.liveData();assert.deepEqual(after.journalNotes,before.journalNotes);assert.equal(after.referencePlacements[0].state,'returned');assert.deepEqual(after.handCards,before.handCards);assert.equal(after.planner.plans.length,0);});
test('B4 reflection is timestamped once, update clears text while retaining ID/time/version and one receipt',async()=>{const h=await b4Harness();await h.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-04',zone:'Asia/Shanghai',text:'补记'});const note=(await h.liveData()).journalNotes[0];h.setNow('2026-10-06T05:00:00Z');await h.submit('SaveJournalNote',{id:note.id,expectedVersion:note.version,date:note.date,zone:note.zone,text:''});const after=(await h.liveData()).journalNotes[0];assert.equal(after.recordedAt,note.recordedAt);assert.equal(after.createdAt,note.createdAt);assert.equal(after.id,note.id);assert.equal(after.version,2);assert.equal(after.text,'');});
test('B4 future notes and stale note versions abort without side effects',async()=>{const h=await b4Harness(),before=h.legacy.evidence();fail(await h.host.submit(await h.command('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-07',zone:'Asia/Shanghai',text:'未来'})),'FUTURE_DATE');assert.deepEqual(h.legacy.evidence(),before);await h.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'note'});const n=(await h.liveData()).journalNotes[0];fail(await h.host.submit(await h.command('SaveJournalNote',{id:n.id,expectedVersion:2,date:n.date,zone:n.zone,text:'edit'})),'ENTRY_STALE');});
test('B4 legacy block edit preserves original creation metadata and entire original text in append-only history',async()=>{const h=await b4Harness(),before=(await h.liveData()).journalEntries[0];await h.submit('SaveLegacyJournalBlock',{entry:ref(before),text:'新全文\r\n'});const after=await h.liveData();assert.equal(after.journalEntries[0].createdAt,before.createdAt);assert.equal(after.journalEntries[0].date,before.date);assert.equal(after.planner.history.at(-1).before.text,before.text);});
test('B4 directory move preserves shared original entry and changes both decks in one receipt',async()=>{const h=await b4Harness(),before=await h.liveData();await h.submit('MoveDeckMember',{entry:ref(catalog.catalogEntries[0]),from:ref(catalog.decks[0]),to:ref(catalog.decks[3]),targetIndex:1});const after=await h.liveData();assert.deepEqual(after.catalogEntries,before.catalogEntries);assert.deepEqual(after.decks.find((d:any)=>d.id==='books').memberIds,[]);assert.deepEqual(after.decks.find((d:any)=>d.id==='loose-list').memberIds,['link-a','book-a']);assert.equal(after.commandReceipts.length,before.commandReceipts.length+1);});
test('B4 invalid catalog edit cannot break owner/member references or drop the original source',async()=>{const h=await b4Harness(),before=h.legacy.evidence();fail(await h.host.submit(await h.command('SaveDeck',{deck:{...catalog.decks[0],version:2,memberIds:['absent']},expectedVersion:1})),'UNKNOWN_FORMAT');assert.deepEqual(h.legacy.evidence(),before);fail(await h.host.submit(await h.command('SaveCatalogEntry',{entry:{...catalog.catalogEntries[0],version:2,source:{kind:'capture',id:'forged'}},expectedVersion:1})),'INVALID_INPUT');});
test('B4 JSON gates share 32 MiB active and 64 MiB input; old gate no longer blocks valid >5 MiB backups',()=>{assert.equal(MAX_BACKUP_BYTES,32*1024*1024);assert.equal(MAX_INPUT_BYTES,64*1024*1024);const old=emptyWorkspaceData();(old as any).journalEntries=[{id:'large',version:1,date:'2026-10-06',zone:'UTC',text:'x'.repeat(6*1024*1024),createdAt:AT,updatedAt:AT}];const pack={format:'cardgrid',version:4,kind:'backup',dataFormat:'action-v4',data:old};assert.deepEqual(parseV06Restore(JSON.stringify(pack)).data,old);});
test('B4 format distinguishes backup v4 from config v4 and rejects malformed configs',async()=>{const h=await b4Harness(),data=await h.liveData();const config={format:'cardgrid',version:4,kind:'config',config:{...catalog,settings:data.settings,definitions:[],templates:[],rules:[],generationRules:[]}};assert.deepEqual(parseConfigV4(JSON.stringify(config)),config);assert.throws(()=>parseV06Restore(JSON.stringify(config)));assert.throws(()=>parseConfigV4(JSON.stringify({...config,kind:'backup'})));});
test('B4 old unproven hand identity is preserved without inventing action ownership',()=>{const old=emptyWorkspaceData();(old as any).planner.instances=[{id:'unproven',version:1,definition:null,creationSnapshot:catalog.actionCards[0].content,currentContent:catalog.actionCards[0].content,source:{kind:'manual'},createdAt:AT,targetDate:null,state:'open',occurrenceId:null,makeupOf:null}];(old as any).planner.handOrder=['unproven'];const migrated=prepareV5Migration(old,{workspaceId:'workspace',commandId:'migration',at:AT});assert.equal(migrated.handCards.length,0);assert.deepEqual(migrated.planner.instances,old.planner.instances);assert.deepEqual(migrated.planner.handOrder,old.planner.handOrder);});
test('B4 migrated oversized pools retain all members and remain selectable; subsequent oversized edits reject',async()=>{
  const h=await b4Harness({catalog:false}),old=structuredClone(h.old) as any;
  for(let i=1;i<=100;i++){const book={...old.bookEntries[0],id:`grandfather-${i}`,title:`合成 ${i}`};old.bookEntries.push(book);old.planner.history.push({id:`grandfather-history-${i}`,commandId:`grandfather-command-${i}`,at:AT,date:'2026-10-06',type:'SaveBookEntry',entity:{kind:'book-entry',id:book.id},before:null,after:book});}
  const pool=old.pools[0],next={...pool,version:2,memberIds:old.bookEntries.map((b:any)=>b.id)};old.pools[0]=next;old.planner.history.push({id:'pool-update',commandId:'pool-update',at:AT,date:'2026-10-06',type:'SavePool',entity:{kind:'pool',id:pool.id},before:pool,after:next});
  const migrated=prepareV5Migration(old,{workspaceId:'large-pool',commandId:'migrate-large',at:AT});h.legacy.store.__setRaw({schemaVersion:4,epoch:'large-epoch',revision:1,lifecycleReceipt:null,mode:'current',dataFormat:'action-v5',data:migrated});
  const decision=migrated.decisionCards[0],p=ok(await h.host.previewDecision({token:await h.token(),decision:ref(decision),deckIds:['old-books']}));assert.equal(p.candidates.length,101);
  const selected=ok(await h.host.selectDecisionEntry({token:await h.token(),previewId:p.previewId,choice:{mode:'manual',entry:ref(migrated.catalogEntries.at(-1))}}));await h.submit('AcceptDecisionAnswer',{selectionId:selected.selectionId,alsoTakeAction:false});
  assert.equal((await h.liveData()).decks[0].memberIds.length,101);fail(await h.host.submit(await h.command('SaveDeck',{deck:{...migrated.decks[0],version:3,name:'修改超限牌堆'},expectedVersion:2})),'POOL_CAPACITY_EXCEEDED');
});
test('B4 typed config import needs generated backup evidence and never replaces instances or journal',async()=>{
  const h=await b4Harness(),data=await h.liveData(),config={format:'cardgrid',version:4,kind:'config',config:{actionCards:data.actionCards,catalogEntries:data.catalogEntries,decks:data.decks,decisionCards:data.decisionCards,settings:data.settings,definitions:data.planner.definitions,templates:data.planner.templates,rules:data.planner.rules,generationRules:data.generationRules}};
  config.config.catalogEntries=[...data.catalogEntries,{...catalog.catalogEntries[0],id:'new-entry',title:'新条目'}];
  const preview=ok(await h.host.previewCatalogImport({token:await h.token(),text:JSON.stringify(config)})),before=h.legacy.evidence();fail(await h.host.submit(await h.command('ImportCatalogV4',{previewId:preview.previewId,mode:'merge',backupEvidenceId:'forged'})),'BACKUP_REQUIRED');assert.deepEqual(h.legacy.evidence(),before);
  const evidence=ok(await h.host.confirmBackupEvidence(await h.backup()));await h.submit('ImportCatalogV4',{previewId:preview.previewId,mode:'merge',backupEvidenceId:evidence.evidenceId});const after=await h.liveData();assert.ok(after.catalogEntries.some((e:any)=>e.id==='new-entry'));assert.deepEqual(after.journalEntries,data.journalEntries);assert.deepEqual(after.planner.instances,data.planner.instances);
});
test('B4 package cannot forge reflection text, answer provenance or migration catalog seeds',async()=>{
  const h=await b4Harness();await h.answer();await h.submit('SaveJournalNote',{id:null,expectedVersion:null,date:'2026-10-06',zone:'Asia/Shanghai',text:'原感想'});const valid=await h.liveData();
  let changed=structuredClone(valid);changed.journalNotes[0].text='篡改';assert.throws(()=>validateDataV5(changed));
  changed=structuredClone(valid);const card=changed.handCards[0];card.answer.entry.title='伪造候选';assert.throws(()=>validateDataV5(changed));
  changed=structuredClone(valid);changed.catalogEntries[0].title='伪造迁移';changed.planner.history.find((h:any)=>h.type==='MigrateCatalogV5'&&h.entity.kind==='catalog-entry').after.title='伪造迁移';assert.throws(()=>validateDataV5(changed));
});
test('B4 hand ordering is a permutation of available cards and does not resurrect consumed inputs',async()=>{
  const h=await b4Harness(),s=await synth(h);ok(await h.host.submit(s.command));await h.submit('TakeEntryMaterial',{entry:ref(catalog.catalogEntries[0])});const before=await h.liveData(),ids=before.handCards.filter((c:any)=>c.state==='available').map((c:any)=>c.id).reverse();await h.submit('ReorderUnifiedHand',{cardIds:ids});const after=await h.liveData();assert.deepEqual(after.handCards.filter((c:any)=>c.state==='available').map((c:any)=>c.id),ids);assert.equal(after.handCards.find((c:any)=>c.id===s.action.id).state,'consumed');fail(await h.host.submit(await h.command('ReorderUnifiedHand',{cardIds:[...ids,s.action.id]})),'INVALID_INPUT');
});
