import {emptyPlanner,validatePlanner,type Planner} from './planner.ts';
import {fromLegacy} from './planner-migration.ts';
export type Preferences = { theme:'paper'|'night'; density:'comfortable'|'compact'; startHour:number; endHour:number; defaultMinutes:number };
export type Category = { id:string; name:string; color:string };
export type Card = { id:string; title:string; kind:'habit'|'temporary'|'increment'; minutes:number; categoryId:string|null; parentId:string|null; steps:string; enabled:boolean };
export type Source = { workbook:string; sheet:string; range:string };
export type Schedule = { id:string; name:string; entries:{cardId:string; start:string; minutes:number}[]; source?:Source };
export type Config = { preferences:Preferences; categories:Category[]; cards:Card[]; schedules:Schedule[] };
export type Legacy = { id:string; importedAt:string; payload:Record<string,unknown> };
export type Project = { id:string; name:string; status:'active'|'paused'|'archived'|'completed' };
export type InboxItem = { id:string; text:string; createdAt:string; status:'inbox'|'converted'|'discarded'; targetId?:string };
export type Routine = { id:string; title:string; cardId:string; weekdays:number[]; enabled:boolean };
export type RoutineOccurrence = { id:string; routineId:string; cardId:string; plannedDate:string; status:'pending'|'done'|'skipped'|'missed'; completedAt?:string; makeupOf?:string };
export type DayRecord = { date:string; top3:string[]; minimumMode:boolean; scheduleId?:string; overrides:Record<string,{start:string;minutes:number}> };
export type EventLog = { id:string; type:string; entityId:string; at:string; date:string; details?:Record<string,unknown> };
export type Data = { config:Config; legacyArchives:Legacy[]; projects:Project[]; inbox:InboxItem[]; routines:Routine[]; occurrences:RoutineOccurrence[]; days:DayRecord[]; events:EventLog[]; planner:Planner };
export type Envelope = { schemaVersion:3; revision:number; data:Data };
export type Pack = { format:'cardgrid'; version:1; kind:'config'; config:Config } | {format:'cardgrid';version:1;kind:'backup';data:Data};
export const emptyConfig=():Config=>({preferences:{theme:'paper',density:'comfortable',startHour:8,endHour:23,defaultMinutes:15},categories:[],cards:[],schedules:[]});
export const emptyData=():Data=>({config:emptyConfig(),legacyArchives:[],projects:[],inbox:[],routines:[],occurrences:[],days:[],events:[],planner:emptyPlanner()});
export class ValidationError extends Error {}
function fail(at:string,message:string):never{throw new ValidationError(`${at}：${message}`)}
function obj(v:unknown,at:string):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))fail(at,'需要对象');return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,allowed:string[],at:string){for(const k of Object.keys(v))if(!allowed.includes(k))fail(`${at}.${k}`,'不支持的字段')}
function str(v:unknown,at:string,max=120,blank=false):string{if(typeof v!=='string'||v.length>max||(!blank&&!v.trim()))fail(at,`需要${blank?'':'非空'}文本，最多${max}字`);return v}
function integer(v:unknown,at:string,min:number,max:number):number{if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)fail(at,`需要${min}—${max}之间的整数`);return v}
function flag(v:unknown,at:string):boolean{if(typeof v!=='boolean')fail(at,'需要true或false');return v}
function list(v:unknown,at:string,max=2000):unknown[]{if(!Array.isArray(v)||v.length>max)fail(at,`需要数组，最多${max}项`);return v}
function id(v:unknown,at:string):string{const s=str(v,at,100);if(!/^[\w-]+$/.test(s))fail(at,'标识只能含字母、数字、下划线和连字符');return s}
function choice<T extends string>(v:unknown,values:T[],at:string):T{if(!values.includes(v as T))fail(at,`可选 ${values.join(' / ')}`);return v as T}
function unique(items:{id:string}[],at:string){const s=new Set();for(const x of items){if(s.has(x.id))fail(at,`标识重复：${x.id}`);s.add(x.id)}}
export function validateConfig(value:unknown):Config{
 const c=obj(value,'配置');keys(c,['preferences','categories','cards','schedules'],'配置');
 const p=obj(c.preferences,'偏好');keys(p,['theme','density','startHour','endHour','defaultMinutes'],'偏好');
 const preferences:Preferences={theme:choice(p.theme,['paper','night'],'主题'),density:choice(p.density,['comfortable','compact'],'密度'),startHour:integer(p.startHour,'开始小时',0,23),endHour:integer(p.endHour,'结束小时',1,24),defaultMinutes:integer(p.defaultMinutes,'指导分钟',1,1440)};
 if(preferences.endHour<=preferences.startHour)fail('时间范围','结束小时必须晚于开始小时');
 const categories=list(c.categories,'分类').map((v,i)=>{const x=obj(v,`分类${i+1}`);keys(x,['id','name','color'],'分类');const color=str(x.color,'颜色');if(!/^#[0-9a-f]{6}$/i.test(color))fail('颜色','使用六位十六进制颜色');return {id:id(x.id,'分类ID'),name:str(x.name,'分类名称'),color}});unique(categories,'分类');
 const cards:Card[]=list(c.cards,'卡片定义').map((v,i)=>{const x=obj(v,`卡片${i+1}`);keys(x,['id','title','kind','minutes','categoryId','parentId','steps','enabled'],'卡片');return {id:id(x.id,'卡片ID'),title:str(x.title,'名称'),kind:choice(x.kind,['habit','temporary','increment'],'种类'),minutes:integer(x.minutes,'卡面分钟',1,1440),categoryId:x.categoryId===null?null:id(x.categoryId,'分类关联'),parentId:x.parentId===null?null:id(x.parentId,'原卡关联'),steps:str(x.steps,'完成标准',3000,true),enabled:flag(x.enabled,'启用')}});unique(cards,'卡片定义');
 for(const c of cards){if(c.categoryId&&!categories.some(x=>x.id===c.categoryId))fail(c.title,'分类不存在');if(c.kind==='increment'){if(!c.parentId||!cards.some(x=>x.id===c.parentId))fail(c.title,'增量卡必须关联存在的原卡')}else if(c.parentId!==null)fail(c.title,'只有增量卡可填写原卡关联');let node:Card|undefined=c;const seen=new Set();while(node?.parentId){if(seen.has(node.id))fail(c.title,'原卡关联不能形成环');seen.add(node.id);node=cards.find(x=>x.id===node!.parentId)}}
 const schedules:Schedule[]=list(c.schedules,'日程模板').map((v,i)=>{const x=obj(v,`日程模板${i+1}`);keys(x,['id','name','entries','source'],'日程模板');let source:Source|undefined;if(x.source!==undefined){const s=obj(x.source,'来源');keys(s,['workbook','sheet','range'],'来源');source={workbook:str(s.workbook,'工作簿',300),sheet:str(s.sheet,'工作表'),range:str(s.range,'范围')}}const entries=list(x.entries,'日程条目').map(v=>{const e=obj(v,'日程条目');keys(e,['cardId','start','minutes'],'日程条目');const cardId=id(e.cardId,'任务关联');if(!cards.some(c=>c.id===cardId))fail('任务关联',`${cardId}不存在`);const start=str(e.start,'开始时间');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(start))fail('开始时间','格式应为HH:mm');const minutes=integer(e.minutes,'计划分钟',1,1440);const [h,m]=start.split(':').map(Number);if(h*60+m+minutes>1440)fail('日程条目','不能超过当天24:00，请拆成两条');return {cardId,start,minutes}});return {id:id(x.id,'模板ID'),name:str(x.name,'模板名称'),entries,...(source?{source}:{})}});unique(schedules,'日程模板');
 return {preferences,categories,cards,schedules};
}
export function validateLegacy(value:unknown):Record<string,unknown>{const x=obj(value,'旧版记录');if(x.version===2){const days=obj(x.days,'旧版日期');list(x.daily,'旧版每日选择');list(x.customTemplates,'旧版模板');for(const [date,v] of Object.entries(days)){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))fail('旧版日期','格式不正确');const d=obj(v,'旧版当日记录');list(d.items,'旧版事项')}}else if(typeof x.date==='string'&&Array.isArray(x.enabled)&&Array.isArray(x.done)){}else fail('文件','不是支持的旧版备份');return x}
export function validateData(value:unknown):Data{const d=obj(value,'备份数据');keys(d,['config','legacyArchives','projects','inbox','routines','occurrences','days','events','planner'],'备份数据');const config=validateConfig(d.config);const legacyArchives=list(d.legacyArchives,'旧版档案',100).map(v=>{const x=obj(v,'旧版档案');keys(x,['id','importedAt','payload'],'旧版档案');const importedAt=str(x.importedAt,'导入时间');if(!Number.isFinite(Date.parse(importedAt)))fail('导入时间','无效时间');return {id:id(x.id,'档案ID'),importedAt,payload:validateLegacy(x.payload)}});unique(legacyArchives,'旧版档案');
 const projects=list(d.projects??[],'项目',1000).map((v,i)=>{const x=obj(v,`项目${i+1}`);keys(x,['id','name','status'],'项目');return {id:id(x.id,'项目ID'),name:str(x.name,'项目名称'),status:choice(x.status,['active','paused','archived','completed'],'项目状态')}});unique(projects,'项目');
 const inbox=list(d.inbox??[],'收件箱',5000).map((v,i)=>{const x=obj(v,`收件箱${i+1}`);keys(x,['id','text','createdAt','status','targetId'],'收件箱');return {id:id(x.id,'收件箱ID'),text:str(x.text,'捕获内容',5000),createdAt:str(x.createdAt,'创建时间',80),status:choice(x.status,['inbox','converted','discarded'],'收件箱状态'),...(x.targetId===undefined?{}:{targetId:id(x.targetId,'目标ID')})}});unique(inbox,'收件箱');
 const routines=list(d.routines??[],'例行规则',1000).map((v,i)=>{const x=obj(v,`例行规则${i+1}`);keys(x,['id','title','cardId','weekdays','enabled'],'例行规则');return {id:id(x.id,'例行规则ID'),title:str(x.title,'例行名称'),cardId:id(x.cardId,'例行卡片ID'),weekdays:list(x.weekdays,'星期',7).map(n=>integer(n,'星期',0,6)),enabled:flag(x.enabled,'例行启用')}});unique(routines,'例行规则');
 const occurrences=list(d.occurrences??[],'例行实例',10000).map((v,i)=>{const x=obj(v,`例行实例${i+1}`);keys(x,['id','routineId','cardId','plannedDate','status','completedAt','makeupOf'],'例行实例');return {id:id(x.id,'实例ID'),routineId:id(x.routineId,'例行规则ID'),cardId:id(x.cardId,'实例卡片ID'),plannedDate:str(x.plannedDate,'计划日期'),status:choice(x.status,['pending','done','skipped','missed'],'实例状态'),...(x.completedAt===undefined?{}:{completedAt:str(x.completedAt,'完成时间',80)}),...(x.makeupOf===undefined?{}:{makeupOf:id(x.makeupOf,'补做实例ID')})}});unique(occurrences,'例行实例');
 const days=list(d.days??[],'每日记录',1000).map((v,i)=>{const x=obj(v,`每日记录${i+1}`);keys(x,['date','top3','minimumMode','scheduleId','overrides'],'每日记录');return {date:str(x.date,'日期'),top3:list(x.top3??[],'Top3',3).map(z=>id(z,'Top3卡片ID')),minimumMode:flag(x.minimumMode??false,'最低运行模式'),...(x.scheduleId===undefined?{}:{scheduleId:id(x.scheduleId,'日程模板ID')}),overrides:obj(x.overrides??{},'日程例外') as Record<string,{start:string;minutes:number}>}});
 const events=list(d.events??[],'事件历史',20000).map((v,i)=>{const x=obj(v,`事件${i+1}`);keys(x,['id','type','entityId','at','date','details'],'事件');return {id:id(x.id,'事件ID'),type:str(x.type,'事件类型'),entityId:id(x.entityId,'事件对象'),at:str(x.at,'事件时间',80),date:str(x.date,'事件日期'),...(x.details===undefined?{}:{details:obj(x.details,'事件详情')})}});
 const base={config,legacyArchives,projects,inbox,routines,occurrences,days,events};return {...base,planner:d.planner===undefined?fromLegacy(base):validatePlanner(d.planner)}}
export function parseImport(text:string):Pack|{kind:'legacy';payload:Record<string,unknown>}{if(new TextEncoder().encode(text).length>5*1024*1024)fail('文件','超过5MB限制');let v:unknown;try{v=JSON.parse(text)}catch{fail('JSON','格式错误，请检查逗号、引号和括号')}const x=obj(v,'文件');if(x.format==='cardgrid'){if(x.version!==1)fail('文件版本','当前仅支持1，不会修改现有数据');if(x.kind==='config'){keys(x,['format','version','kind','config'],'配置包');return {format:'cardgrid',version:1,kind:'config',config:validateConfig(x.config)}}if(x.kind==='backup'){keys(x,['format','version','kind','data'],'备份');return {format:'cardgrid',version:1,kind:'backup',data:validateData(x.data)}}fail('文件种类','不支持')}return {kind:'legacy',payload:validateLegacy(x)}}
export function configPack(config:Config):Pack{return {format:'cardgrid',version:1,kind:'config',config:validateConfig(config)}}
export function backupPack(data:Data):Pack{return {format:'cardgrid',version:1,kind:'backup',data:validateData(data)}}
export function mergeConfig(a:Config,b:Config):Config{const merge=<T extends {id:string}>(x:T[],y:T[])=>[...new Map([...x,...y].map(v=>[v.id,v])).values()];return validateConfig({preferences:b.preferences,categories:merge(a.categories,b.categories),cards:merge(a.cards,b.cards),schedules:merge(a.schedules,b.schedules)})}
export function applyImport(current:Data,pack:ReturnType<typeof parseImport>,mode:'merge'|'replace'):Data{if(pack.kind==='backup')return validateData(pack.data);if(pack.kind==='config')return {...current,config:mode==='merge'?mergeConfig(current.config,pack.config):pack.config};const serialized=JSON.stringify(pack.payload);if(current.legacyArchives.some(x=>JSON.stringify(x.payload)===serialized))return current;return validateData({...current,legacyArchives:[...current.legacyArchives,{id:crypto.randomUUID(),importedAt:new Date().toISOString(),payload:pack.payload}]})}
export function readEnvelope(v:unknown):Envelope{const x=obj(v,'本地数据');if(x.schemaVersion!==3&&x.schemaVersion!==2)fail('本地版本','不支持此版本，请导出原始数据并使用兼容版本');return {schemaVersion:3,revision:integer(x.revision,'数据修订',0,Number.MAX_SAFE_INTEGER),data:validateData(x.data)}}
export function migrateV1(v:unknown):Envelope{const x=obj(v,'旧结构');if(x.schemaVersion!==1)fail('旧结构','版本不支持');return {schemaVersion:3,revision:integer(x.revision,'修订',0,Number.MAX_SAFE_INTEGER),data:{config:validateConfig(x.config),legacyArchives:[],projects:[],inbox:[],routines:[],occurrences:[],days:[],events:[],planner:emptyPlanner()}}}
