import React,{useRef,useState} from 'react';
import type {Data} from './domain';
import {changeStatus,createCapture,makeup,top3,setTodayMode,localDate,type Task} from './planner';

type Props={data:Data;date:string;onSave:(data:Data,message:string)=>Promise<boolean>;onDateChange:(delta:number)=>void};
const clone=<T,>(v:T):T=>structuredClone(v);
const clock=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
export function Today({data,date,onSave,onDateChange}:Props){
 const [capture,setCapture]=useState(''); const [saving,setSaving]=useState(false); const lock=useRef(false); const [error,setError]=useState(''); const actualToday=localDate(); const readonly=date!==actualToday;
 const planner=data.planner; const day=planner.days.find(x=>x.date===date); const minimum=day?.minimum??false;
 const tasks=planner.tasks.filter(t=>t.date===date&&t.status!=='cancelled');
 const occurrences=planner.occurrences.filter(o=>o.date===date).map(o=>({occurrence:o,task:planner.tasks.find(t=>t.id===o.task)})).filter(x=>x.task) as {occurrence:typeof planner.occurrences[number];task:Task}[];
 const topTasks=(day?.top3||[]).map(id=>planner.tasks.find(t=>t.id===id)).filter(Boolean) as Task[];
 const candidates=tasks.filter(t=>!(day?.top3||[]).includes(t.id)).slice(0,8);
 const blocks=(day?.blocks||[]).filter(b=>!b.cancelled).sort((a,b)=>a.start-b.start);
 const missed=planner.tasks.filter(t=>t.date&&t.date<actualToday&&t.occurrence).map(task=>({task,occurrence:planner.occurrences.find(o=>o.id===task.occurrence)!})).filter(x=>x.occurrence&&['missed','skipped'].includes(x.occurrence.status));
 async function run(mut:(p:typeof planner)=>void,msg:string):Promise<boolean>{
  if(lock.current)return false;lock.current=true;setSaving(true);setError('');
  try{const next=clone(data);mut(next.planner);const ok=await onSave(next,msg);if(!ok)setError('未保存，请保留输入并重新载入最新数据后重试。');return ok}
  catch(e){setError((e as Error).message);return false}finally{lock.current=false;setSaving(false)}
 }
 async function captureItem(){const text=capture.trim();if(!text)return;if(await run(p=>{createCapture(p,text)},'已放入收件箱'))setCapture('')}
 async function toggle(task:Task){await run(p=>changeStatus(p,task.id,task.status==='done'?'planned':'done',actualToday),task.status==='done'?'已恢复任务':'已完成任务')}
 async function chooseTop(id:string){const ids=[...(day?.top3||[])];if(!ids.includes(id)&&ids.length===3){setError('最多选择 3 项，请先移出一项。');return}const next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];await run(p=>top3(p,date,next,actualToday),'已更新 Top3')}
 async function toggleMinimum(){await run(p=>setTodayMode(p,date,!minimum,actualToday),minimum?'已恢复正常日程':'已进入 Minimum Day')}
 async function doMakeup(id:string){await run(p=>makeup(p,id,actualToday),'已创建补做事项')}
 return <>{error&&<p role="alert" className="message">{error}</p>}{readonly&&<p className="message">当前查看历史或未来日期；任务操作请回到今天。</p>}
  <section className="heading"><div className="eyebrow">TODAY · P1A</div><div className="headingline"><div><h1>{new Date(date+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</h1><p>{minimum?'Minimum Day · 只保护最低版本':'打开 → 看一眼 → 微调 → 开始今天'}</p></div><div className="datecontrols"><button aria-label="前一天" onClick={()=>onDateChange(-1)}>‹</button><span className="todaybadge">{minimum?'最低运行模式':day?.name||'未准备日型'}</span><button aria-label="后一天" onClick={()=>onDateChange(1)}>›</button></div></div></section>
  <section className="top3panel panel"><div className="sectiontitle"><div><h2>今天最重要的 3 件事</h2><p className="muted">由你确认，Planner 只提供候选。</p></div><button className={minimum?'primary':''} disabled={saving||readonly} onClick={()=>void toggleMinimum()}>{minimum?'恢复正常日程':'切换 Minimum Day'}</button></div><div className="top3list">{[0,1,2].map((i)=>{const t=topTasks[i];return <button key={i} className="top3item" disabled={saving||readonly} onClick={()=>t&&void chooseTop(t.id)}><b>{i+1}</b><span>{t?.title||'选择今天要保护的任务'}</span></button>})}</div><div className="candidate-list">{candidates.map(t=><button key={t.id} className="candidate" disabled={saving||readonly} onClick={()=>void chooseTop(t.id)}>＋ {t.title}</button>)}</div></section>
  <div className="todaycolumns"><section className="panel"><div className="sectiontitle"><div><h2>今日日程</h2><p className="muted">固定安排与弹性任务分开显示。</p></div></div>{blocks.length?<div className="schedulelist">{blocks.map(b=><div className={`scheduleitem ${b.kind}`} key={b.id}><time>{clock(b.start)}</time><span className={`block ${b.kind}`}><strong>{b.kind==='fixed'?'固定':'弹性'}</strong> {b.title}<small>{clock(b.start)}–{clock(b.end)}</small></span></div>)}</div>:<p className="emptyline">还没有今天的 Planner 安排。可以到 Schedule 页面应用日型。</p>}</section>
  <section className="panel"><div className="sectiontitle"><div><h2>今日例行</h2><p className="muted">昨天没做不会偷偷搬到今天。</p></div></div>{occurrences.length?<div className="routine-list">{[...occurrences].sort((a,b)=>minimum?Number(b.task.minimum)-Number(a.task.minimum):0).map(({occurrence,task})=><div className="routineitem" key={occurrence.id}><label className="checkbox"><input type="checkbox" checked={task.status==='done'} disabled={saving||readonly} onChange={()=>void toggle(task)}/><span>{minimum&&task.minimum?'最低事项 · ':''}{task.title}</span></label><button disabled={saving||readonly||task.status==='skipped'||task.status==='done'} onClick={()=>void run(p=>changeStatus(p,task.id,'skipped',actualToday),'已跳过例行')}>跳过</button><small>{occurrence.status==='completed'?'已完成':occurrence.status==='skipped'?'已跳过':occurrence.status==='missed'?'已错过':occurrence.status==='cancelled'?'已取消':'待完成'}</small></div>)}</div>:<p className="emptyline">还没有今天的 Planner 例行事项。</p>}</section></div>
  <section className="panel"><div className="sectiontitle"><div><h2>昨日遗留</h2><p className="muted">由你决定补做或稍后处理。</p></div></div>{missed.length?<div className="carry-list">{missed.slice(0,8).map(({task,occurrence})=><div className="carryitem" key={task.id}><span>□ {task.title} <small>{occurrence.date}</small></span><button disabled={saving||readonly||planner.tasks.some(t=>t.makeupOf===occurrence.id)} onClick={()=>void doMakeup(occurrence.id)}>补做</button></div>)}</div>:<p className="emptyline">没有昨日遗留。</p>}</section>
  <section className="panel"><h2>当天事项</h2>{tasks.filter(t=>!t.occurrence).map(task=><label className="routineitem" key={task.id}><input type="checkbox" checked={task.status==='done'} disabled={saving||readonly} onChange={()=>void toggle(task)}/><span>{task.title}</span></label>)}</section><section className="capture panel"><div className="sectiontitle"><div><h2>快速记录</h2><p className="muted">先放进 Inbox，之后再整理，不打断当前工作。</p></div><span className="capturehint">约 10 秒</span></div><div className="captureline"><input disabled={saving} aria-label="快速记录" placeholder="我突然想到……" value={capture} onChange={e=>setCapture(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void captureItem()}}/><button className="primary" disabled={saving} onClick={()=>void captureItem()}>放入 Inbox</button></div>{planner.captures.filter(x=>x.status==='unprocessed').length>0&&<div className="inboxpreview">最近收件箱：{planner.captures.filter(x=>x.status==='unprocessed').slice(-3).reverse().map(x=><span key={x.id}>{x.text}</span>)}</div>}</section>
 </>;
}
