import type {RefObject} from 'react';
import type {MigrationPreview} from '../contracts.ts';
import type {WorkspaceClient,BackupPreparation} from '../client.ts';
import type {WorkspacePreview} from '../session-types.ts';
type Props={client:WorkspaceClient;readOnly:boolean;dataVersion?:2|3|4;backup:BackupPreparation|null;saved:boolean;setSaved:(value:boolean)=>void;
 file:RefObject<HTMLInputElement|null>;merge:'merge'|'replace';setMerge:(value:'merge'|'replace')=>void;setPending:(value:WorkspacePreview|null)=>void;
 fileText:string;previewFile:(value:string)=>Promise<void>;prepareBackup:()=>Promise<void>;setMessage:(value:string)=>void;download:(name:string,value:unknown)=>void;
 recovery:readonly {key:IDBValidKey;value:unknown}[];zone:string;setZone:(value:string)=>void;offsets:string;setOffsets:(value:string)=>void;
 migration:()=>Promise<void>;pending:WorkspacePreview|null;readonlyPaths:string[];setReadonlyPaths:(value:string[])=>void;
 resetText:string;setResetText:(value:string)=>void;discard:boolean;setDiscard:(value:boolean)=>void;busy:boolean;execute:()=>Promise<void>;};
export function DataPage({client,readOnly,dataVersion,backup,saved,setSaved,file,merge,setMerge,setPending,fileText,previewFile,prepareBackup,setMessage,download,recovery,zone,setZone,offsets,setOffsets,migration,pending,readonlyPaths,setReadonlyPaths,resetText,setResetText,discard,setDiscard,busy,execute}:Props){return <>
 <div className="datagrid"><section className="panel"><h2>完整备份</h2><button onClick={()=>void prepareBackup()}>下载完整备份</button><p>应用生成文件后，需要你确认已保存。</p>{backup&&<label className="checkbox"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>我已保存这份完整备份</label>}</section>
 <section className="panel"><h2>配置与恢复</h2><button onClick={()=>file.current?.click()}>导入文件</button><button disabled={readOnly} onClick={()=>void client.exportDefinitions().then(r=>{if(r.ok)download('CardGrid-配置.json',r.value);else setMessage(r.message);})}>导出配置</button><label>配置导入方式<select value={merge} onChange={e=>{setMerge(e.target.value as 'merge'|'replace');setPending(null);}}><option value="merge">合并</option><option value="replace">替换目录（保留历史身份）</option></select></label>{fileText&&<button onClick={()=>void previewFile(fileText)}>重新预览文件</button>}</section>
 <section className="panel"><h2>本机恢复点</h2>{recovery.length?recovery.map((point,i)=><button key={i} onClick={()=>void client.exportRecovery(point.key).then(r=>{if(r.ok)download('CardGrid-恢复点-'+String(point.key)+'.json',r.value);else setMessage(r.message);})}>导出 {String(point.key)} 原文</button>):<p>尚无恢复点。</p>}<p>清空或恢复会移除全部本机恢复点。</p></section></div>
 {readOnly&&<section className="panel"><h2>显式升级旧工作区</h2><label>旧记录原时区<input aria-label="旧记录原时区" value={zone} onChange={e=>{setZone(e.target.value);setPending(null);}}/></label><p>请确认原时区。迁移报告会列出保持只读和必须处理的来源。</p><label>起止偏移选择（来源路径对应 start/end，例如 -04:00）<textarea aria-label="迁移偏移选择" value={offsets} onChange={e=>{setOffsets(e.target.value);setPending(null);}}/></label><button onClick={()=>void migration()}>预览升级</button></section>}
 {dataVersion===2&&<section className="panel"><h2>升级以启用工坊与每日库存</h2><p>先下载并保存完整备份。升级会保留现有行动、排期、事实和设置，加入空的工坊与库存；不会生成示例数据。</p><button disabled={busy} onClick={()=>void migration()}>预览升级</button></section>}
 {dataVersion===3&&<section className="panel"><h2>升级以启用日记</h2><p>先下载并保存完整备份。升级保留现有全部数据，加入空的日记集合；不会生成示例数据。</p><button disabled={busy} onClick={()=>void migration()}>预览升级</button></section>}
 {pending&&<section className="panel"><h2>{pending.type==='CommitMigration'?'迁移预览':pending.type==='RestoreWorkspace'?'恢复预览':'配置导入预览'}</h2>{pending.type==='CommitMigration'?<><p>{(pending.details as MigrationPreview).upgrade?'升级后保留':'迁移结果'}：定义 {(pending.details as MigrationPreview).targetSummary.definitions} · 行动 {(pending.details as MigrationPreview).targetSummary.instances} · 计划 {(pending.details as MigrationPreview).targetSummary.plans} · 事实 {(pending.details as MigrationPreview).targetSummary.facts}。升级不会生成新事实。</p>{(pending.details as MigrationPreview).issues.map((issue,i)=><p key={i} role={issue.blocking?'alert':undefined}>{issue.blocking?'需处理：':'保留说明：'}{issue.message}</p>)}</>:<p>{pending.type==='RestoreWorkspace'?'恢复会用备份完整替换当前工作区；保留文件中的记录顺序与字段。':'仅更新定义目录与偏好；既有行动、事实和批注保持。请展开详情检查前后差异。'}</p>}<details><summary>查看来源与前后差异</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:420,overflow:'auto'}}>{JSON.stringify(pending.details,null,2)}</pre></details>{pending.type==='CommitMigration'&&(pending.details as MigrationPreview).issues.filter(i=>i.code==='MULTIPLE_BLOCKS').map(issue=><label className="checkbox" key={issue.source.path}><input type="checkbox" checked={readonlyPaths.includes(issue.source.path)} onChange={e=>{setReadonlyPaths(e.target.checked?[...readonlyPaths,issue.source.path]:readonlyPaths.filter(p=>p!==issue.source.path));setPending(null);}}/>保留只读：{issue.source.path}</label>)}{pending.blocked&&<p role="alert">请解决报告中的阻断项后重新预览。</p>}<button onClick={()=>{client.invalidateCapabilities();setPending(null);}}>取消预览</button></section>}
 <section className="panel dangerpanel"><h2>清空或执行预览</h2>{!pending&&<label>清空当前工作区请输入“清空”<input aria-label="清空确认文字" value={resetText} onChange={e=>setResetText(e.target.value)}/></label>}<label className="checkbox"><input type="checkbox" checked={discard} onChange={e=>setDiscard(e.target.checked)}/>确认放弃未提交草稿并执行以上操作</label><button className="danger" disabled={busy||!backup||!saved||!discard||pending?.blocked||(!pending&&resetText!=='清空')} onClick={()=>void execute()}>{pending?'执行已预览操作':'清空工作台'}</button></section></>;}
